// Code generated by protoc-gen-go.
// source: gopkg.in/freddierice/go-hproto.v1/hdfs/datatransfer.proto
// DO NOT EDIT!

package hproto_hdfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hproto_common "gopkg.in/freddierice/go-hproto.v1/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Status is a 4-bit enum
type Status int32

const (
	Status_SUCCESS            Status = 0
	Status_ERROR              Status = 1
	Status_ERROR_CHECKSUM     Status = 2
	Status_ERROR_INVALID      Status = 3
	Status_ERROR_EXISTS       Status = 4
	Status_ERROR_ACCESS_TOKEN Status = 5
	Status_CHECKSUM_OK        Status = 6
	Status_ERROR_UNSUPPORTED  Status = 7
	Status_OOB_RESTART        Status = 8
	Status_OOB_RESERVED1      Status = 9
	Status_OOB_RESERVED2      Status = 10
	Status_OOB_RESERVED3      Status = 11
	Status_IN_PROGRESS        Status = 12
)

var Status_name = map[int32]string{
	0:  "SUCCESS",
	1:  "ERROR",
	2:  "ERROR_CHECKSUM",
	3:  "ERROR_INVALID",
	4:  "ERROR_EXISTS",
	5:  "ERROR_ACCESS_TOKEN",
	6:  "CHECKSUM_OK",
	7:  "ERROR_UNSUPPORTED",
	8:  "OOB_RESTART",
	9:  "OOB_RESERVED1",
	10: "OOB_RESERVED2",
	11: "OOB_RESERVED3",
	12: "IN_PROGRESS",
}
var Status_value = map[string]int32{
	"SUCCESS":            0,
	"ERROR":              1,
	"ERROR_CHECKSUM":     2,
	"ERROR_INVALID":      3,
	"ERROR_EXISTS":       4,
	"ERROR_ACCESS_TOKEN": 5,
	"CHECKSUM_OK":        6,
	"ERROR_UNSUPPORTED":  7,
	"OOB_RESTART":        8,
	"OOB_RESERVED1":      9,
	"OOB_RESERVED2":      10,
	"OOB_RESERVED3":      11,
	"IN_PROGRESS":        12,
}

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}
func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (x *Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Status_value, data, "Status")
	if err != nil {
		return err
	}
	*x = Status(value)
	return nil
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

type ShortCircuitFdResponse int32

const (
	ShortCircuitFdResponse_DO_NOT_USE_RECEIPT_VERIFICATION ShortCircuitFdResponse = 0
	ShortCircuitFdResponse_USE_RECEIPT_VERIFICATION        ShortCircuitFdResponse = 1
)

var ShortCircuitFdResponse_name = map[int32]string{
	0: "DO_NOT_USE_RECEIPT_VERIFICATION",
	1: "USE_RECEIPT_VERIFICATION",
}
var ShortCircuitFdResponse_value = map[string]int32{
	"DO_NOT_USE_RECEIPT_VERIFICATION": 0,
	"USE_RECEIPT_VERIFICATION":        1,
}

func (x ShortCircuitFdResponse) Enum() *ShortCircuitFdResponse {
	p := new(ShortCircuitFdResponse)
	*p = x
	return p
}
func (x ShortCircuitFdResponse) String() string {
	return proto.EnumName(ShortCircuitFdResponse_name, int32(x))
}
func (x *ShortCircuitFdResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ShortCircuitFdResponse_value, data, "ShortCircuitFdResponse")
	if err != nil {
		return err
	}
	*x = ShortCircuitFdResponse(value)
	return nil
}
func (ShortCircuitFdResponse) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

type DataTransferEncryptorMessageProto_DataTransferEncryptorStatus int32

const (
	DataTransferEncryptorMessageProto_SUCCESS           DataTransferEncryptorMessageProto_DataTransferEncryptorStatus = 0
	DataTransferEncryptorMessageProto_ERROR_UNKNOWN_KEY DataTransferEncryptorMessageProto_DataTransferEncryptorStatus = 1
	DataTransferEncryptorMessageProto_ERROR             DataTransferEncryptorMessageProto_DataTransferEncryptorStatus = 2
)

var DataTransferEncryptorMessageProto_DataTransferEncryptorStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR_UNKNOWN_KEY",
	2: "ERROR",
}
var DataTransferEncryptorMessageProto_DataTransferEncryptorStatus_value = map[string]int32{
	"SUCCESS":           0,
	"ERROR_UNKNOWN_KEY": 1,
	"ERROR":             2,
}

func (x DataTransferEncryptorMessageProto_DataTransferEncryptorStatus) Enum() *DataTransferEncryptorMessageProto_DataTransferEncryptorStatus {
	p := new(DataTransferEncryptorMessageProto_DataTransferEncryptorStatus)
	*p = x
	return p
}
func (x DataTransferEncryptorMessageProto_DataTransferEncryptorStatus) String() string {
	return proto.EnumName(DataTransferEncryptorMessageProto_DataTransferEncryptorStatus_name, int32(x))
}
func (x *DataTransferEncryptorMessageProto_DataTransferEncryptorStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DataTransferEncryptorMessageProto_DataTransferEncryptorStatus_value, data, "DataTransferEncryptorMessageProto_DataTransferEncryptorStatus")
	if err != nil {
		return err
	}
	*x = DataTransferEncryptorMessageProto_DataTransferEncryptorStatus(value)
	return nil
}
func (DataTransferEncryptorMessageProto_DataTransferEncryptorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor10, []int{0, 0}
}

type OpWriteBlockProto_BlockConstructionStage int32

const (
	OpWriteBlockProto_PIPELINE_SETUP_APPEND OpWriteBlockProto_BlockConstructionStage = 0
	// pipeline set up for failed PIPELINE_SETUP_APPEND recovery
	OpWriteBlockProto_PIPELINE_SETUP_APPEND_RECOVERY OpWriteBlockProto_BlockConstructionStage = 1
	// data streaming
	OpWriteBlockProto_DATA_STREAMING OpWriteBlockProto_BlockConstructionStage = 2
	// pipeline setup for failed data streaming recovery
	OpWriteBlockProto_PIPELINE_SETUP_STREAMING_RECOVERY OpWriteBlockProto_BlockConstructionStage = 3
	// close the block and pipeline
	OpWriteBlockProto_PIPELINE_CLOSE OpWriteBlockProto_BlockConstructionStage = 4
	// Recover a failed PIPELINE_CLOSE
	OpWriteBlockProto_PIPELINE_CLOSE_RECOVERY OpWriteBlockProto_BlockConstructionStage = 5
	// pipeline set up for block creation
	OpWriteBlockProto_PIPELINE_SETUP_CREATE OpWriteBlockProto_BlockConstructionStage = 6
	// transfer RBW for adding datanodes
	OpWriteBlockProto_TRANSFER_RBW OpWriteBlockProto_BlockConstructionStage = 7
	// transfer Finalized for adding datanodes
	OpWriteBlockProto_TRANSFER_FINALIZED OpWriteBlockProto_BlockConstructionStage = 8
)

var OpWriteBlockProto_BlockConstructionStage_name = map[int32]string{
	0: "PIPELINE_SETUP_APPEND",
	1: "PIPELINE_SETUP_APPEND_RECOVERY",
	2: "DATA_STREAMING",
	3: "PIPELINE_SETUP_STREAMING_RECOVERY",
	4: "PIPELINE_CLOSE",
	5: "PIPELINE_CLOSE_RECOVERY",
	6: "PIPELINE_SETUP_CREATE",
	7: "TRANSFER_RBW",
	8: "TRANSFER_FINALIZED",
}
var OpWriteBlockProto_BlockConstructionStage_value = map[string]int32{
	"PIPELINE_SETUP_APPEND":             0,
	"PIPELINE_SETUP_APPEND_RECOVERY":    1,
	"DATA_STREAMING":                    2,
	"PIPELINE_SETUP_STREAMING_RECOVERY": 3,
	"PIPELINE_CLOSE":                    4,
	"PIPELINE_CLOSE_RECOVERY":           5,
	"PIPELINE_SETUP_CREATE":             6,
	"TRANSFER_RBW":                      7,
	"TRANSFER_FINALIZED":                8,
}

func (x OpWriteBlockProto_BlockConstructionStage) Enum() *OpWriteBlockProto_BlockConstructionStage {
	p := new(OpWriteBlockProto_BlockConstructionStage)
	*p = x
	return p
}
func (x OpWriteBlockProto_BlockConstructionStage) String() string {
	return proto.EnumName(OpWriteBlockProto_BlockConstructionStage_name, int32(x))
}
func (x *OpWriteBlockProto_BlockConstructionStage) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OpWriteBlockProto_BlockConstructionStage_value, data, "OpWriteBlockProto_BlockConstructionStage")
	if err != nil {
		return err
	}
	*x = OpWriteBlockProto_BlockConstructionStage(value)
	return nil
}
func (OpWriteBlockProto_BlockConstructionStage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor10, []int{7, 0}
}

type DataTransferEncryptorMessageProto struct {
	Status           *DataTransferEncryptorMessageProto_DataTransferEncryptorStatus `protobuf:"varint,1,req,name=status,enum=hproto.hdfs.DataTransferEncryptorMessageProto_DataTransferEncryptorStatus" json:"status,omitempty"`
	Payload          []byte                                                         `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	Message          *string                                                        `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	CipherOption     []*CipherOptionProto                                           `protobuf:"bytes,4,rep,name=cipherOption" json:"cipherOption,omitempty"`
	XXX_unrecognized []byte                                                         `json:"-"`
}

func (m *DataTransferEncryptorMessageProto) Reset()         { *m = DataTransferEncryptorMessageProto{} }
func (m *DataTransferEncryptorMessageProto) String() string { return proto.CompactTextString(m) }
func (*DataTransferEncryptorMessageProto) ProtoMessage()    {}
func (*DataTransferEncryptorMessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor10, []int{0}
}

func (m *DataTransferEncryptorMessageProto) GetStatus() DataTransferEncryptorMessageProto_DataTransferEncryptorStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return DataTransferEncryptorMessageProto_SUCCESS
}

func (m *DataTransferEncryptorMessageProto) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DataTransferEncryptorMessageProto) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *DataTransferEncryptorMessageProto) GetCipherOption() []*CipherOptionProto {
	if m != nil {
		return m.CipherOption
	}
	return nil
}

type BaseHeaderProto struct {
	Block            *ExtendedBlockProto         `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	Token            *hproto_common.TokenProto   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	TraceInfo        *DataTransferTraceInfoProto `protobuf:"bytes,3,opt,name=traceInfo" json:"traceInfo,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *BaseHeaderProto) Reset()                    { *m = BaseHeaderProto{} }
func (m *BaseHeaderProto) String() string            { return proto.CompactTextString(m) }
func (*BaseHeaderProto) ProtoMessage()               {}
func (*BaseHeaderProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func (m *BaseHeaderProto) GetBlock() *ExtendedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BaseHeaderProto) GetToken() *hproto_common.TokenProto {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *BaseHeaderProto) GetTraceInfo() *DataTransferTraceInfoProto {
	if m != nil {
		return m.TraceInfo
	}
	return nil
}

type DataTransferTraceInfoProto struct {
	TraceId          *uint64 `protobuf:"varint,1,req,name=traceId" json:"traceId,omitempty"`
	ParentId         *uint64 `protobuf:"varint,2,req,name=parentId" json:"parentId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DataTransferTraceInfoProto) Reset()                    { *m = DataTransferTraceInfoProto{} }
func (m *DataTransferTraceInfoProto) String() string            { return proto.CompactTextString(m) }
func (*DataTransferTraceInfoProto) ProtoMessage()               {}
func (*DataTransferTraceInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

func (m *DataTransferTraceInfoProto) GetTraceId() uint64 {
	if m != nil && m.TraceId != nil {
		return *m.TraceId
	}
	return 0
}

func (m *DataTransferTraceInfoProto) GetParentId() uint64 {
	if m != nil && m.ParentId != nil {
		return *m.ParentId
	}
	return 0
}

type ClientOperationHeaderProto struct {
	BaseHeader       *BaseHeaderProto `protobuf:"bytes,1,req,name=baseHeader" json:"baseHeader,omitempty"`
	ClientName       *string          `protobuf:"bytes,2,req,name=clientName" json:"clientName,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ClientOperationHeaderProto) Reset()                    { *m = ClientOperationHeaderProto{} }
func (m *ClientOperationHeaderProto) String() string            { return proto.CompactTextString(m) }
func (*ClientOperationHeaderProto) ProtoMessage()               {}
func (*ClientOperationHeaderProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{3} }

func (m *ClientOperationHeaderProto) GetBaseHeader() *BaseHeaderProto {
	if m != nil {
		return m.BaseHeader
	}
	return nil
}

func (m *ClientOperationHeaderProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

type CachingStrategyProto struct {
	DropBehind       *bool  `protobuf:"varint,1,opt,name=dropBehind" json:"dropBehind,omitempty"`
	Readahead        *int64 `protobuf:"varint,2,opt,name=readahead" json:"readahead,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CachingStrategyProto) Reset()                    { *m = CachingStrategyProto{} }
func (m *CachingStrategyProto) String() string            { return proto.CompactTextString(m) }
func (*CachingStrategyProto) ProtoMessage()               {}
func (*CachingStrategyProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{4} }

func (m *CachingStrategyProto) GetDropBehind() bool {
	if m != nil && m.DropBehind != nil {
		return *m.DropBehind
	}
	return false
}

func (m *CachingStrategyProto) GetReadahead() int64 {
	if m != nil && m.Readahead != nil {
		return *m.Readahead
	}
	return 0
}

type OpReadBlockProto struct {
	Header           *ClientOperationHeaderProto `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	Offset           *uint64                     `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	Len              *uint64                     `protobuf:"varint,3,req,name=len" json:"len,omitempty"`
	SendChecksums    *bool                       `protobuf:"varint,4,opt,name=sendChecksums,def=1" json:"sendChecksums,omitempty"`
	CachingStrategy  *CachingStrategyProto       `protobuf:"bytes,5,opt,name=cachingStrategy" json:"cachingStrategy,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *OpReadBlockProto) Reset()                    { *m = OpReadBlockProto{} }
func (m *OpReadBlockProto) String() string            { return proto.CompactTextString(m) }
func (*OpReadBlockProto) ProtoMessage()               {}
func (*OpReadBlockProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{5} }

const Default_OpReadBlockProto_SendChecksums bool = true

func (m *OpReadBlockProto) GetHeader() *ClientOperationHeaderProto {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *OpReadBlockProto) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *OpReadBlockProto) GetLen() uint64 {
	if m != nil && m.Len != nil {
		return *m.Len
	}
	return 0
}

func (m *OpReadBlockProto) GetSendChecksums() bool {
	if m != nil && m.SendChecksums != nil {
		return *m.SendChecksums
	}
	return Default_OpReadBlockProto_SendChecksums
}

func (m *OpReadBlockProto) GetCachingStrategy() *CachingStrategyProto {
	if m != nil {
		return m.CachingStrategy
	}
	return nil
}

type ChecksumProto struct {
	Type             *ChecksumTypeProto `protobuf:"varint,1,req,name=type,enum=hproto.hdfs.ChecksumTypeProto" json:"type,omitempty"`
	BytesPerChecksum *uint32            `protobuf:"varint,2,req,name=bytesPerChecksum" json:"bytesPerChecksum,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ChecksumProto) Reset()                    { *m = ChecksumProto{} }
func (m *ChecksumProto) String() string            { return proto.CompactTextString(m) }
func (*ChecksumProto) ProtoMessage()               {}
func (*ChecksumProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{6} }

func (m *ChecksumProto) GetType() ChecksumTypeProto {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ChecksumTypeProto_CHECKSUM_NULL
}

func (m *ChecksumProto) GetBytesPerChecksum() uint32 {
	if m != nil && m.BytesPerChecksum != nil {
		return *m.BytesPerChecksum
	}
	return 0
}

type OpWriteBlockProto struct {
	Header                *ClientOperationHeaderProto               `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	Targets               []*DatanodeInfoProto                      `protobuf:"bytes,2,rep,name=targets" json:"targets,omitempty"`
	Source                *DatanodeInfoProto                        `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`
	Stage                 *OpWriteBlockProto_BlockConstructionStage `protobuf:"varint,4,req,name=stage,enum=hproto.hdfs.OpWriteBlockProto_BlockConstructionStage" json:"stage,omitempty"`
	PipelineSize          *uint32                                   `protobuf:"varint,5,req,name=pipelineSize" json:"pipelineSize,omitempty"`
	MinBytesRcvd          *uint64                                   `protobuf:"varint,6,req,name=minBytesRcvd" json:"minBytesRcvd,omitempty"`
	MaxBytesRcvd          *uint64                                   `protobuf:"varint,7,req,name=maxBytesRcvd" json:"maxBytesRcvd,omitempty"`
	LatestGenerationStamp *uint64                                   `protobuf:"varint,8,req,name=latestGenerationStamp" json:"latestGenerationStamp,omitempty"`
	// *
	// The requested checksum mechanism for this block write.
	RequestedChecksum  *ChecksumProto        `protobuf:"bytes,9,req,name=requestedChecksum" json:"requestedChecksum,omitempty"`
	CachingStrategy    *CachingStrategyProto `protobuf:"bytes,10,opt,name=cachingStrategy" json:"cachingStrategy,omitempty"`
	StorageType        *StorageTypeProto     `protobuf:"varint,11,opt,name=storageType,enum=hproto.hdfs.StorageTypeProto,def=1" json:"storageType,omitempty"`
	TargetStorageTypes []StorageTypeProto    `protobuf:"varint,12,rep,name=targetStorageTypes,enum=hproto.hdfs.StorageTypeProto" json:"targetStorageTypes,omitempty"`
	// *
	// Hint to the DataNode that the block can be allocated on transient
	// storage i.e. memory and written to disk lazily. The DataNode is free
	// to ignore this hint.
	AllowLazyPersist *bool `protobuf:"varint,13,opt,name=allowLazyPersist,def=0" json:"allowLazyPersist,omitempty"`
	// whether to pin the block, so Balancer won't move it.
	Pinning          *bool  `protobuf:"varint,14,opt,name=pinning,def=0" json:"pinning,omitempty"`
	TargetPinnings   []bool `protobuf:"varint,15,rep,name=targetPinnings" json:"targetPinnings,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OpWriteBlockProto) Reset()                    { *m = OpWriteBlockProto{} }
func (m *OpWriteBlockProto) String() string            { return proto.CompactTextString(m) }
func (*OpWriteBlockProto) ProtoMessage()               {}
func (*OpWriteBlockProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{7} }

const Default_OpWriteBlockProto_StorageType StorageTypeProto = StorageTypeProto_DISK
const Default_OpWriteBlockProto_AllowLazyPersist bool = false
const Default_OpWriteBlockProto_Pinning bool = false

func (m *OpWriteBlockProto) GetHeader() *ClientOperationHeaderProto {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *OpWriteBlockProto) GetTargets() []*DatanodeInfoProto {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *OpWriteBlockProto) GetSource() *DatanodeInfoProto {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *OpWriteBlockProto) GetStage() OpWriteBlockProto_BlockConstructionStage {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return OpWriteBlockProto_PIPELINE_SETUP_APPEND
}

func (m *OpWriteBlockProto) GetPipelineSize() uint32 {
	if m != nil && m.PipelineSize != nil {
		return *m.PipelineSize
	}
	return 0
}

func (m *OpWriteBlockProto) GetMinBytesRcvd() uint64 {
	if m != nil && m.MinBytesRcvd != nil {
		return *m.MinBytesRcvd
	}
	return 0
}

func (m *OpWriteBlockProto) GetMaxBytesRcvd() uint64 {
	if m != nil && m.MaxBytesRcvd != nil {
		return *m.MaxBytesRcvd
	}
	return 0
}

func (m *OpWriteBlockProto) GetLatestGenerationStamp() uint64 {
	if m != nil && m.LatestGenerationStamp != nil {
		return *m.LatestGenerationStamp
	}
	return 0
}

func (m *OpWriteBlockProto) GetRequestedChecksum() *ChecksumProto {
	if m != nil {
		return m.RequestedChecksum
	}
	return nil
}

func (m *OpWriteBlockProto) GetCachingStrategy() *CachingStrategyProto {
	if m != nil {
		return m.CachingStrategy
	}
	return nil
}

func (m *OpWriteBlockProto) GetStorageType() StorageTypeProto {
	if m != nil && m.StorageType != nil {
		return *m.StorageType
	}
	return Default_OpWriteBlockProto_StorageType
}

func (m *OpWriteBlockProto) GetTargetStorageTypes() []StorageTypeProto {
	if m != nil {
		return m.TargetStorageTypes
	}
	return nil
}

func (m *OpWriteBlockProto) GetAllowLazyPersist() bool {
	if m != nil && m.AllowLazyPersist != nil {
		return *m.AllowLazyPersist
	}
	return Default_OpWriteBlockProto_AllowLazyPersist
}

func (m *OpWriteBlockProto) GetPinning() bool {
	if m != nil && m.Pinning != nil {
		return *m.Pinning
	}
	return Default_OpWriteBlockProto_Pinning
}

func (m *OpWriteBlockProto) GetTargetPinnings() []bool {
	if m != nil {
		return m.TargetPinnings
	}
	return nil
}

type OpTransferBlockProto struct {
	Header             *ClientOperationHeaderProto `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	Targets            []*DatanodeInfoProto        `protobuf:"bytes,2,rep,name=targets" json:"targets,omitempty"`
	TargetStorageTypes []StorageTypeProto          `protobuf:"varint,3,rep,name=targetStorageTypes,enum=hproto.hdfs.StorageTypeProto" json:"targetStorageTypes,omitempty"`
	XXX_unrecognized   []byte                      `json:"-"`
}

func (m *OpTransferBlockProto) Reset()                    { *m = OpTransferBlockProto{} }
func (m *OpTransferBlockProto) String() string            { return proto.CompactTextString(m) }
func (*OpTransferBlockProto) ProtoMessage()               {}
func (*OpTransferBlockProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{8} }

func (m *OpTransferBlockProto) GetHeader() *ClientOperationHeaderProto {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *OpTransferBlockProto) GetTargets() []*DatanodeInfoProto {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *OpTransferBlockProto) GetTargetStorageTypes() []StorageTypeProto {
	if m != nil {
		return m.TargetStorageTypes
	}
	return nil
}

type OpReplaceBlockProto struct {
	Header           *BaseHeaderProto   `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	DelHint          *string            `protobuf:"bytes,2,req,name=delHint" json:"delHint,omitempty"`
	Source           *DatanodeInfoProto `protobuf:"bytes,3,req,name=source" json:"source,omitempty"`
	StorageType      *StorageTypeProto  `protobuf:"varint,4,opt,name=storageType,enum=hproto.hdfs.StorageTypeProto,def=1" json:"storageType,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *OpReplaceBlockProto) Reset()                    { *m = OpReplaceBlockProto{} }
func (m *OpReplaceBlockProto) String() string            { return proto.CompactTextString(m) }
func (*OpReplaceBlockProto) ProtoMessage()               {}
func (*OpReplaceBlockProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{9} }

const Default_OpReplaceBlockProto_StorageType StorageTypeProto = StorageTypeProto_DISK

func (m *OpReplaceBlockProto) GetHeader() *BaseHeaderProto {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *OpReplaceBlockProto) GetDelHint() string {
	if m != nil && m.DelHint != nil {
		return *m.DelHint
	}
	return ""
}

func (m *OpReplaceBlockProto) GetSource() *DatanodeInfoProto {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *OpReplaceBlockProto) GetStorageType() StorageTypeProto {
	if m != nil && m.StorageType != nil {
		return *m.StorageType
	}
	return Default_OpReplaceBlockProto_StorageType
}

type OpCopyBlockProto struct {
	Header           *BaseHeaderProto `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *OpCopyBlockProto) Reset()                    { *m = OpCopyBlockProto{} }
func (m *OpCopyBlockProto) String() string            { return proto.CompactTextString(m) }
func (*OpCopyBlockProto) ProtoMessage()               {}
func (*OpCopyBlockProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{10} }

func (m *OpCopyBlockProto) GetHeader() *BaseHeaderProto {
	if m != nil {
		return m.Header
	}
	return nil
}

type OpBlockChecksumProto struct {
	Header           *BaseHeaderProto `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *OpBlockChecksumProto) Reset()                    { *m = OpBlockChecksumProto{} }
func (m *OpBlockChecksumProto) String() string            { return proto.CompactTextString(m) }
func (*OpBlockChecksumProto) ProtoMessage()               {}
func (*OpBlockChecksumProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{11} }

func (m *OpBlockChecksumProto) GetHeader() *BaseHeaderProto {
	if m != nil {
		return m.Header
	}
	return nil
}

type OpBlockGroupChecksumProto struct {
	Header    *BaseHeaderProto    `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	Datanodes *DatanodeInfosProto `protobuf:"bytes,2,req,name=datanodes" json:"datanodes,omitempty"`
	// each internal block has a block token
	BlockTokens       []*hproto_common.TokenProto `protobuf:"bytes,3,rep,name=blockTokens" json:"blockTokens,omitempty"`
	EcPolicy          *ErasureCodingPolicyProto   `protobuf:"bytes,4,req,name=ecPolicy" json:"ecPolicy,omitempty"`
	BlockIndices      []uint32                    `protobuf:"varint,5,rep,name=blockIndices" json:"blockIndices,omitempty"`
	RequestedNumBytes *uint64                     `protobuf:"varint,6,req,name=requestedNumBytes" json:"requestedNumBytes,omitempty"`
	XXX_unrecognized  []byte                      `json:"-"`
}

func (m *OpBlockGroupChecksumProto) Reset()                    { *m = OpBlockGroupChecksumProto{} }
func (m *OpBlockGroupChecksumProto) String() string            { return proto.CompactTextString(m) }
func (*OpBlockGroupChecksumProto) ProtoMessage()               {}
func (*OpBlockGroupChecksumProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{12} }

func (m *OpBlockGroupChecksumProto) GetHeader() *BaseHeaderProto {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *OpBlockGroupChecksumProto) GetDatanodes() *DatanodeInfosProto {
	if m != nil {
		return m.Datanodes
	}
	return nil
}

func (m *OpBlockGroupChecksumProto) GetBlockTokens() []*hproto_common.TokenProto {
	if m != nil {
		return m.BlockTokens
	}
	return nil
}

func (m *OpBlockGroupChecksumProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

func (m *OpBlockGroupChecksumProto) GetBlockIndices() []uint32 {
	if m != nil {
		return m.BlockIndices
	}
	return nil
}

func (m *OpBlockGroupChecksumProto) GetRequestedNumBytes() uint64 {
	if m != nil && m.RequestedNumBytes != nil {
		return *m.RequestedNumBytes
	}
	return 0
}

// *
// An ID uniquely identifying a shared memory segment.
type ShortCircuitShmIdProto struct {
	Hi               *int64 `protobuf:"varint,1,req,name=hi" json:"hi,omitempty"`
	Lo               *int64 `protobuf:"varint,2,req,name=lo" json:"lo,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ShortCircuitShmIdProto) Reset()                    { *m = ShortCircuitShmIdProto{} }
func (m *ShortCircuitShmIdProto) String() string            { return proto.CompactTextString(m) }
func (*ShortCircuitShmIdProto) ProtoMessage()               {}
func (*ShortCircuitShmIdProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{13} }

func (m *ShortCircuitShmIdProto) GetHi() int64 {
	if m != nil && m.Hi != nil {
		return *m.Hi
	}
	return 0
}

func (m *ShortCircuitShmIdProto) GetLo() int64 {
	if m != nil && m.Lo != nil {
		return *m.Lo
	}
	return 0
}

// *
// An ID uniquely identifying a slot within a shared memory segment.
type ShortCircuitShmSlotProto struct {
	ShmId            *ShortCircuitShmIdProto `protobuf:"bytes,1,req,name=shmId" json:"shmId,omitempty"`
	SlotIdx          *int32                  `protobuf:"varint,2,req,name=slotIdx" json:"slotIdx,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ShortCircuitShmSlotProto) Reset()                    { *m = ShortCircuitShmSlotProto{} }
func (m *ShortCircuitShmSlotProto) String() string            { return proto.CompactTextString(m) }
func (*ShortCircuitShmSlotProto) ProtoMessage()               {}
func (*ShortCircuitShmSlotProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{14} }

func (m *ShortCircuitShmSlotProto) GetShmId() *ShortCircuitShmIdProto {
	if m != nil {
		return m.ShmId
	}
	return nil
}

func (m *ShortCircuitShmSlotProto) GetSlotIdx() int32 {
	if m != nil && m.SlotIdx != nil {
		return *m.SlotIdx
	}
	return 0
}

type OpRequestShortCircuitAccessProto struct {
	Header *BaseHeaderProto `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	// * In order to get short-circuit access to block data, clients must set this
	// to the highest version of the block data that they can understand.
	// Currently 1 is the only version, but more versions may exist in the future
	// if the on-disk format changes.
	MaxVersion *uint32 `protobuf:"varint,2,req,name=maxVersion" json:"maxVersion,omitempty"`
	// *
	// The shared memory slot to use, if we are using one.
	SlotId *ShortCircuitShmSlotProto `protobuf:"bytes,3,opt,name=slotId" json:"slotId,omitempty"`
	// *
	// True if the client supports verifying that the file descriptor has been
	// sent successfully.
	SupportsReceiptVerification *bool  `protobuf:"varint,4,opt,name=supportsReceiptVerification,def=0" json:"supportsReceiptVerification,omitempty"`
	XXX_unrecognized            []byte `json:"-"`
}

func (m *OpRequestShortCircuitAccessProto) Reset()         { *m = OpRequestShortCircuitAccessProto{} }
func (m *OpRequestShortCircuitAccessProto) String() string { return proto.CompactTextString(m) }
func (*OpRequestShortCircuitAccessProto) ProtoMessage()    {}
func (*OpRequestShortCircuitAccessProto) Descriptor() ([]byte, []int) {
	return fileDescriptor10, []int{15}
}

const Default_OpRequestShortCircuitAccessProto_SupportsReceiptVerification bool = false

func (m *OpRequestShortCircuitAccessProto) GetHeader() *BaseHeaderProto {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *OpRequestShortCircuitAccessProto) GetMaxVersion() uint32 {
	if m != nil && m.MaxVersion != nil {
		return *m.MaxVersion
	}
	return 0
}

func (m *OpRequestShortCircuitAccessProto) GetSlotId() *ShortCircuitShmSlotProto {
	if m != nil {
		return m.SlotId
	}
	return nil
}

func (m *OpRequestShortCircuitAccessProto) GetSupportsReceiptVerification() bool {
	if m != nil && m.SupportsReceiptVerification != nil {
		return *m.SupportsReceiptVerification
	}
	return Default_OpRequestShortCircuitAccessProto_SupportsReceiptVerification
}

type ReleaseShortCircuitAccessRequestProto struct {
	SlotId           *ShortCircuitShmSlotProto   `protobuf:"bytes,1,req,name=slotId" json:"slotId,omitempty"`
	TraceInfo        *DataTransferTraceInfoProto `protobuf:"bytes,2,opt,name=traceInfo" json:"traceInfo,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *ReleaseShortCircuitAccessRequestProto) Reset()         { *m = ReleaseShortCircuitAccessRequestProto{} }
func (m *ReleaseShortCircuitAccessRequestProto) String() string { return proto.CompactTextString(m) }
func (*ReleaseShortCircuitAccessRequestProto) ProtoMessage()    {}
func (*ReleaseShortCircuitAccessRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor10, []int{16}
}

func (m *ReleaseShortCircuitAccessRequestProto) GetSlotId() *ShortCircuitShmSlotProto {
	if m != nil {
		return m.SlotId
	}
	return nil
}

func (m *ReleaseShortCircuitAccessRequestProto) GetTraceInfo() *DataTransferTraceInfoProto {
	if m != nil {
		return m.TraceInfo
	}
	return nil
}

type ReleaseShortCircuitAccessResponseProto struct {
	Status           *Status `protobuf:"varint,1,req,name=status,enum=hproto.hdfs.Status" json:"status,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReleaseShortCircuitAccessResponseProto) Reset() {
	*m = ReleaseShortCircuitAccessResponseProto{}
}
func (m *ReleaseShortCircuitAccessResponseProto) String() string { return proto.CompactTextString(m) }
func (*ReleaseShortCircuitAccessResponseProto) ProtoMessage()    {}
func (*ReleaseShortCircuitAccessResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor10, []int{17}
}

func (m *ReleaseShortCircuitAccessResponseProto) GetStatus() Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Status_SUCCESS
}

func (m *ReleaseShortCircuitAccessResponseProto) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type ShortCircuitShmRequestProto struct {
	// The name of the client requesting the shared memory segment.  This is
	// purely for logging / debugging purposes.
	ClientName       *string                     `protobuf:"bytes,1,req,name=clientName" json:"clientName,omitempty"`
	TraceInfo        *DataTransferTraceInfoProto `protobuf:"bytes,2,opt,name=traceInfo" json:"traceInfo,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *ShortCircuitShmRequestProto) Reset()                    { *m = ShortCircuitShmRequestProto{} }
func (m *ShortCircuitShmRequestProto) String() string            { return proto.CompactTextString(m) }
func (*ShortCircuitShmRequestProto) ProtoMessage()               {}
func (*ShortCircuitShmRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{18} }

func (m *ShortCircuitShmRequestProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *ShortCircuitShmRequestProto) GetTraceInfo() *DataTransferTraceInfoProto {
	if m != nil {
		return m.TraceInfo
	}
	return nil
}

type ShortCircuitShmResponseProto struct {
	Status           *Status                 `protobuf:"varint,1,req,name=status,enum=hproto.hdfs.Status" json:"status,omitempty"`
	Error            *string                 `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Id               *ShortCircuitShmIdProto `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ShortCircuitShmResponseProto) Reset()                    { *m = ShortCircuitShmResponseProto{} }
func (m *ShortCircuitShmResponseProto) String() string            { return proto.CompactTextString(m) }
func (*ShortCircuitShmResponseProto) ProtoMessage()               {}
func (*ShortCircuitShmResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{19} }

func (m *ShortCircuitShmResponseProto) GetStatus() Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Status_SUCCESS
}

func (m *ShortCircuitShmResponseProto) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *ShortCircuitShmResponseProto) GetId() *ShortCircuitShmIdProto {
	if m != nil {
		return m.Id
	}
	return nil
}

type PacketHeaderProto struct {
	// All fields must be fixed-length!
	OffsetInBlock     *int64 `protobuf:"fixed64,1,req,name=offsetInBlock" json:"offsetInBlock,omitempty"`
	Seqno             *int64 `protobuf:"fixed64,2,req,name=seqno" json:"seqno,omitempty"`
	LastPacketInBlock *bool  `protobuf:"varint,3,req,name=lastPacketInBlock" json:"lastPacketInBlock,omitempty"`
	DataLen           *int32 `protobuf:"fixed32,4,req,name=dataLen" json:"dataLen,omitempty"`
	SyncBlock         *bool  `protobuf:"varint,5,opt,name=syncBlock,def=0" json:"syncBlock,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (m *PacketHeaderProto) Reset()                    { *m = PacketHeaderProto{} }
func (m *PacketHeaderProto) String() string            { return proto.CompactTextString(m) }
func (*PacketHeaderProto) ProtoMessage()               {}
func (*PacketHeaderProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{20} }

const Default_PacketHeaderProto_SyncBlock bool = false

func (m *PacketHeaderProto) GetOffsetInBlock() int64 {
	if m != nil && m.OffsetInBlock != nil {
		return *m.OffsetInBlock
	}
	return 0
}

func (m *PacketHeaderProto) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *PacketHeaderProto) GetLastPacketInBlock() bool {
	if m != nil && m.LastPacketInBlock != nil {
		return *m.LastPacketInBlock
	}
	return false
}

func (m *PacketHeaderProto) GetDataLen() int32 {
	if m != nil && m.DataLen != nil {
		return *m.DataLen
	}
	return 0
}

func (m *PacketHeaderProto) GetSyncBlock() bool {
	if m != nil && m.SyncBlock != nil {
		return *m.SyncBlock
	}
	return Default_PacketHeaderProto_SyncBlock
}

type PipelineAckProto struct {
	Seqno                  *int64   `protobuf:"zigzag64,1,req,name=seqno" json:"seqno,omitempty"`
	Reply                  []Status `protobuf:"varint,2,rep,name=reply,enum=hproto.hdfs.Status" json:"reply,omitempty"`
	DownstreamAckTimeNanos *uint64  `protobuf:"varint,3,opt,name=downstreamAckTimeNanos,def=0" json:"downstreamAckTimeNanos,omitempty"`
	Flag                   []uint32 `protobuf:"varint,4,rep,packed,name=flag" json:"flag,omitempty"`
	XXX_unrecognized       []byte   `json:"-"`
}

func (m *PipelineAckProto) Reset()                    { *m = PipelineAckProto{} }
func (m *PipelineAckProto) String() string            { return proto.CompactTextString(m) }
func (*PipelineAckProto) ProtoMessage()               {}
func (*PipelineAckProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{21} }

const Default_PipelineAckProto_DownstreamAckTimeNanos uint64 = 0

func (m *PipelineAckProto) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *PipelineAckProto) GetReply() []Status {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *PipelineAckProto) GetDownstreamAckTimeNanos() uint64 {
	if m != nil && m.DownstreamAckTimeNanos != nil {
		return *m.DownstreamAckTimeNanos
	}
	return Default_PipelineAckProto_DownstreamAckTimeNanos
}

func (m *PipelineAckProto) GetFlag() []uint32 {
	if m != nil {
		return m.Flag
	}
	return nil
}

// *
// Sent as part of the BlockOpResponseProto
// for READ_BLOCK and COPY_BLOCK operations.
type ReadOpChecksumInfoProto struct {
	Checksum *ChecksumProto `protobuf:"bytes,1,req,name=checksum" json:"checksum,omitempty"`
	// *
	// The offset into the block at which the first packet
	// will start. This is necessary since reads will align
	// backwards to a checksum chunk boundary.
	ChunkOffset      *uint64 `protobuf:"varint,2,req,name=chunkOffset" json:"chunkOffset,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReadOpChecksumInfoProto) Reset()                    { *m = ReadOpChecksumInfoProto{} }
func (m *ReadOpChecksumInfoProto) String() string            { return proto.CompactTextString(m) }
func (*ReadOpChecksumInfoProto) ProtoMessage()               {}
func (*ReadOpChecksumInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{22} }

func (m *ReadOpChecksumInfoProto) GetChecksum() *ChecksumProto {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *ReadOpChecksumInfoProto) GetChunkOffset() uint64 {
	if m != nil && m.ChunkOffset != nil {
		return *m.ChunkOffset
	}
	return 0
}

type BlockOpResponseProto struct {
	Status             *Status                       `protobuf:"varint,1,req,name=status,enum=hproto.hdfs.Status" json:"status,omitempty"`
	FirstBadLink       *string                       `protobuf:"bytes,2,opt,name=firstBadLink" json:"firstBadLink,omitempty"`
	ChecksumResponse   *OpBlockChecksumResponseProto `protobuf:"bytes,3,opt,name=checksumResponse" json:"checksumResponse,omitempty"`
	ReadOpChecksumInfo *ReadOpChecksumInfoProto      `protobuf:"bytes,4,opt,name=readOpChecksumInfo" json:"readOpChecksumInfo,omitempty"`
	// * explanatory text which may be useful to log on the client side
	Message *string `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
	// * If the server chooses to agree to the request of a client for
	// short-circuit access, it will send a response message with the relevant
	// file descriptors attached.
	//
	// In the body of the message, this version number will be set to the
	// specific version number of the block data that the client is about to
	// read.
	ShortCircuitAccessVersion *uint32 `protobuf:"varint,6,opt,name=shortCircuitAccessVersion" json:"shortCircuitAccessVersion,omitempty"`
	XXX_unrecognized          []byte  `json:"-"`
}

func (m *BlockOpResponseProto) Reset()                    { *m = BlockOpResponseProto{} }
func (m *BlockOpResponseProto) String() string            { return proto.CompactTextString(m) }
func (*BlockOpResponseProto) ProtoMessage()               {}
func (*BlockOpResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{23} }

func (m *BlockOpResponseProto) GetStatus() Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Status_SUCCESS
}

func (m *BlockOpResponseProto) GetFirstBadLink() string {
	if m != nil && m.FirstBadLink != nil {
		return *m.FirstBadLink
	}
	return ""
}

func (m *BlockOpResponseProto) GetChecksumResponse() *OpBlockChecksumResponseProto {
	if m != nil {
		return m.ChecksumResponse
	}
	return nil
}

func (m *BlockOpResponseProto) GetReadOpChecksumInfo() *ReadOpChecksumInfoProto {
	if m != nil {
		return m.ReadOpChecksumInfo
	}
	return nil
}

func (m *BlockOpResponseProto) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *BlockOpResponseProto) GetShortCircuitAccessVersion() uint32 {
	if m != nil && m.ShortCircuitAccessVersion != nil {
		return *m.ShortCircuitAccessVersion
	}
	return 0
}

// *
// Message sent from the client to the DN after reading the entire
// read request.
type ClientReadStatusProto struct {
	Status           *Status `protobuf:"varint,1,req,name=status,enum=hproto.hdfs.Status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ClientReadStatusProto) Reset()                    { *m = ClientReadStatusProto{} }
func (m *ClientReadStatusProto) String() string            { return proto.CompactTextString(m) }
func (*ClientReadStatusProto) ProtoMessage()               {}
func (*ClientReadStatusProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{24} }

func (m *ClientReadStatusProto) GetStatus() Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Status_SUCCESS
}

type DNTransferAckProto struct {
	Status           *Status `protobuf:"varint,1,req,name=status,enum=hproto.hdfs.Status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DNTransferAckProto) Reset()                    { *m = DNTransferAckProto{} }
func (m *DNTransferAckProto) String() string            { return proto.CompactTextString(m) }
func (*DNTransferAckProto) ProtoMessage()               {}
func (*DNTransferAckProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{25} }

func (m *DNTransferAckProto) GetStatus() Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Status_SUCCESS
}

type OpBlockChecksumResponseProto struct {
	BytesPerCrc      *uint32            `protobuf:"varint,1,req,name=bytesPerCrc" json:"bytesPerCrc,omitempty"`
	CrcPerBlock      *uint64            `protobuf:"varint,2,req,name=crcPerBlock" json:"crcPerBlock,omitempty"`
	Md5              []byte             `protobuf:"bytes,3,req,name=md5" json:"md5,omitempty"`
	CrcType          *ChecksumTypeProto `protobuf:"varint,4,opt,name=crcType,enum=hproto.hdfs.ChecksumTypeProto" json:"crcType,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *OpBlockChecksumResponseProto) Reset()                    { *m = OpBlockChecksumResponseProto{} }
func (m *OpBlockChecksumResponseProto) String() string            { return proto.CompactTextString(m) }
func (*OpBlockChecksumResponseProto) ProtoMessage()               {}
func (*OpBlockChecksumResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{26} }

func (m *OpBlockChecksumResponseProto) GetBytesPerCrc() uint32 {
	if m != nil && m.BytesPerCrc != nil {
		return *m.BytesPerCrc
	}
	return 0
}

func (m *OpBlockChecksumResponseProto) GetCrcPerBlock() uint64 {
	if m != nil && m.CrcPerBlock != nil {
		return *m.CrcPerBlock
	}
	return 0
}

func (m *OpBlockChecksumResponseProto) GetMd5() []byte {
	if m != nil {
		return m.Md5
	}
	return nil
}

func (m *OpBlockChecksumResponseProto) GetCrcType() ChecksumTypeProto {
	if m != nil && m.CrcType != nil {
		return *m.CrcType
	}
	return ChecksumTypeProto_CHECKSUM_NULL
}

type OpCustomProto struct {
	CustomId         *string `protobuf:"bytes,1,req,name=customId" json:"customId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OpCustomProto) Reset()                    { *m = OpCustomProto{} }
func (m *OpCustomProto) String() string            { return proto.CompactTextString(m) }
func (*OpCustomProto) ProtoMessage()               {}
func (*OpCustomProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{27} }

func (m *OpCustomProto) GetCustomId() string {
	if m != nil && m.CustomId != nil {
		return *m.CustomId
	}
	return ""
}

func init() {
	proto.RegisterType((*DataTransferEncryptorMessageProto)(nil), "hproto.hdfs.DataTransferEncryptorMessageProto")
	proto.RegisterType((*BaseHeaderProto)(nil), "hproto.hdfs.BaseHeaderProto")
	proto.RegisterType((*DataTransferTraceInfoProto)(nil), "hproto.hdfs.DataTransferTraceInfoProto")
	proto.RegisterType((*ClientOperationHeaderProto)(nil), "hproto.hdfs.ClientOperationHeaderProto")
	proto.RegisterType((*CachingStrategyProto)(nil), "hproto.hdfs.CachingStrategyProto")
	proto.RegisterType((*OpReadBlockProto)(nil), "hproto.hdfs.OpReadBlockProto")
	proto.RegisterType((*ChecksumProto)(nil), "hproto.hdfs.ChecksumProto")
	proto.RegisterType((*OpWriteBlockProto)(nil), "hproto.hdfs.OpWriteBlockProto")
	proto.RegisterType((*OpTransferBlockProto)(nil), "hproto.hdfs.OpTransferBlockProto")
	proto.RegisterType((*OpReplaceBlockProto)(nil), "hproto.hdfs.OpReplaceBlockProto")
	proto.RegisterType((*OpCopyBlockProto)(nil), "hproto.hdfs.OpCopyBlockProto")
	proto.RegisterType((*OpBlockChecksumProto)(nil), "hproto.hdfs.OpBlockChecksumProto")
	proto.RegisterType((*OpBlockGroupChecksumProto)(nil), "hproto.hdfs.OpBlockGroupChecksumProto")
	proto.RegisterType((*ShortCircuitShmIdProto)(nil), "hproto.hdfs.ShortCircuitShmIdProto")
	proto.RegisterType((*ShortCircuitShmSlotProto)(nil), "hproto.hdfs.ShortCircuitShmSlotProto")
	proto.RegisterType((*OpRequestShortCircuitAccessProto)(nil), "hproto.hdfs.OpRequestShortCircuitAccessProto")
	proto.RegisterType((*ReleaseShortCircuitAccessRequestProto)(nil), "hproto.hdfs.ReleaseShortCircuitAccessRequestProto")
	proto.RegisterType((*ReleaseShortCircuitAccessResponseProto)(nil), "hproto.hdfs.ReleaseShortCircuitAccessResponseProto")
	proto.RegisterType((*ShortCircuitShmRequestProto)(nil), "hproto.hdfs.ShortCircuitShmRequestProto")
	proto.RegisterType((*ShortCircuitShmResponseProto)(nil), "hproto.hdfs.ShortCircuitShmResponseProto")
	proto.RegisterType((*PacketHeaderProto)(nil), "hproto.hdfs.PacketHeaderProto")
	proto.RegisterType((*PipelineAckProto)(nil), "hproto.hdfs.PipelineAckProto")
	proto.RegisterType((*ReadOpChecksumInfoProto)(nil), "hproto.hdfs.ReadOpChecksumInfoProto")
	proto.RegisterType((*BlockOpResponseProto)(nil), "hproto.hdfs.BlockOpResponseProto")
	proto.RegisterType((*ClientReadStatusProto)(nil), "hproto.hdfs.ClientReadStatusProto")
	proto.RegisterType((*DNTransferAckProto)(nil), "hproto.hdfs.DNTransferAckProto")
	proto.RegisterType((*OpBlockChecksumResponseProto)(nil), "hproto.hdfs.OpBlockChecksumResponseProto")
	proto.RegisterType((*OpCustomProto)(nil), "hproto.hdfs.OpCustomProto")
	proto.RegisterEnum("hproto.hdfs.Status", Status_name, Status_value)
	proto.RegisterEnum("hproto.hdfs.ShortCircuitFdResponse", ShortCircuitFdResponse_name, ShortCircuitFdResponse_value)
	proto.RegisterEnum("hproto.hdfs.DataTransferEncryptorMessageProto_DataTransferEncryptorStatus", DataTransferEncryptorMessageProto_DataTransferEncryptorStatus_name, DataTransferEncryptorMessageProto_DataTransferEncryptorStatus_value)
	proto.RegisterEnum("hproto.hdfs.OpWriteBlockProto_BlockConstructionStage", OpWriteBlockProto_BlockConstructionStage_name, OpWriteBlockProto_BlockConstructionStage_value)
}

func init() {
	proto.RegisterFile("gopkg.in/freddierice/go-hproto.v1/hdfs/datatransfer.proto", fileDescriptor10)
}

var fileDescriptor10 = []byte{
	// 2103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x58, 0x4f, 0x77, 0xdb, 0xc6,
	0x11, 0x2f, 0x28, 0x51, 0x16, 0x87, 0x92, 0x0c, 0x6f, 0x6c, 0x87, 0x96, 0xdd, 0xd8, 0x86, 0xe3,
	0xd4, 0x71, 0x5a, 0xa9, 0x56, 0xe2, 0x34, 0x71, 0xd3, 0xf6, 0xf1, 0x0f, 0x6c, 0xb3, 0x92, 0x09,
	0xbe, 0x05, 0x64, 0xf7, 0xcf, 0x81, 0x0f, 0x06, 0x96, 0x22, 0x9e, 0x48, 0x00, 0x01, 0xc0, 0xc4,
	0xf4, 0xa9, 0x87, 0x1e, 0xfa, 0x09, 0x7a, 0xee, 0xa9, 0xb7, 0xf6, 0x13, 0xf4, 0xd0, 0x2f, 0xd0,
	0xef, 0xd0, 0xd7, 0xd7, 0x4b, 0xdf, 0xeb, 0xb1, 0xaf, 0xe7, 0xce, 0xee, 0x02, 0x24, 0x40, 0x52,
	0x52, 0xac, 0xf8, 0xd0, 0x0b, 0x1f, 0x77, 0x76, 0x66, 0x30, 0xf3, 0xdb, 0xd9, 0xf9, 0xb3, 0xf0,
	0xf9, 0x51, 0x10, 0x1e, 0x1f, 0xed, 0x78, 0xfe, 0x6e, 0x3f, 0x62, 0xae, 0xeb, 0xb1, 0xc8, 0x73,
	0xd8, 0xee, 0x51, 0xf0, 0x83, 0x41, 0x18, 0x05, 0x49, 0xb0, 0xf3, 0xd5, 0x83, 0xdd, 0x81, 0xdb,
	0x8f, 0x77, 0x5d, 0x3b, 0xb1, 0x93, 0xc8, 0xf6, 0xe3, 0x3e, 0x8b, 0x76, 0xc4, 0x16, 0xa9, 0xa6,
	0x2c, 0x7c, 0x7f, 0xfb, 0x47, 0x67, 0xeb, 0x71, 0x82, 0xd1, 0x28, 0xf0, 0x77, 0x4d, 0xe6, 0x8c,
	0x23, 0x2f, 0x99, 0x48, 0x2d, 0xdb, 0x0f, 0xbe, 0xa1, 0x01, 0xfc, 0x47, 0x8a, 0x68, 0x7f, 0x2b,
	0xc1, 0xed, 0x16, 0xda, 0x63, 0xa5, 0xf6, 0xe8, 0xbe, 0x13, 0x4d, 0xc2, 0x24, 0x88, 0x9e, 0xb1,
	0x38, 0xb6, 0x8f, 0x58, 0x57, 0x98, 0xf7, 0x12, 0xd6, 0x62, 0xb4, 0x79, 0x1c, 0xd7, 0x94, 0x5b,
	0xa5, 0x7b, 0x5b, 0x7b, 0x3f, 0xdf, 0xc9, 0xd9, 0xbb, 0x73, 0xa6, 0xfc, 0x72, 0x0e, 0x53, 0x68,
	0xa4, 0xa9, 0x66, 0x52, 0x83, 0x0b, 0xa1, 0x3d, 0x19, 0x06, 0xb6, 0x5b, 0x2b, 0xdd, 0x52, 0xee,
	0x6d, 0xd0, 0x6c, 0xc9, 0x77, 0x46, 0x52, 0x5b, 0x6d, 0x05, 0x77, 0x2a, 0x34, 0x5b, 0x92, 0x06,
	0x6c, 0x38, 0x5e, 0x38, 0x60, 0x91, 0x11, 0x26, 0x5e, 0xe0, 0xd7, 0x56, 0x6f, 0xad, 0xdc, 0xab,
	0xee, 0xbd, 0x57, 0xb0, 0xae, 0x99, 0x63, 0x10, 0xd6, 0xd0, 0x82, 0x8c, 0x76, 0x00, 0xd7, 0x4f,
	0x31, 0x8f, 0x54, 0xe1, 0x82, 0x79, 0xd8, 0x6c, 0xea, 0xa6, 0xa9, 0x7e, 0x87, 0x5c, 0x81, 0x4b,
	0x3a, 0xa5, 0x06, 0xed, 0x1d, 0x76, 0xf6, 0x3b, 0xc6, 0x8b, 0x4e, 0x6f, 0x5f, 0xff, 0xa5, 0xaa,
	0x90, 0x0a, 0x94, 0x05, 0x59, 0x2d, 0x69, 0x7f, 0x55, 0xe0, 0x62, 0xc3, 0x8e, 0xd9, 0x53, 0x66,
	0xbb, 0x2c, 0x92, 0xe8, 0x3d, 0x84, 0xf2, 0xcb, 0x61, 0xe0, 0x1c, 0x0b, 0xf0, 0xaa, 0x7b, 0x37,
	0x0b, 0xe6, 0xe9, 0xaf, 0x12, 0xe6, 0xbb, 0xcc, 0x6d, 0x70, 0x0e, 0x69, 0x9f, 0xe4, 0x26, 0xbb,
	0x50, 0x4e, 0x82, 0x63, 0xe6, 0x0b, 0x38, 0xaa, 0x7b, 0xd7, 0x32, 0x31, 0x79, 0xf6, 0x3b, 0x16,
	0xdf, 0x4b, 0x05, 0x04, 0x1f, 0xd1, 0xa1, 0x82, 0x61, 0xe5, 0xb0, 0xb6, 0xdf, 0x0f, 0x04, 0x52,
	0xd5, 0xbd, 0xef, 0x9d, 0x78, 0x50, 0x56, 0xc6, 0x29, 0x55, 0xcc, 0x24, 0x35, 0x0a, 0xdb, 0x27,
	0x33, 0xf2, 0xc3, 0x90, 0xac, 0xae, 0x70, 0x67, 0x95, 0x66, 0x4b, 0xb2, 0x0d, 0xeb, 0xa1, 0x1d,
	0x31, 0x3f, 0x69, 0xf3, 0x13, 0xe4, 0x5b, 0xd3, 0xb5, 0xf6, 0x1a, 0xb6, 0x9b, 0x43, 0x0f, 0xff,
	0x1b, 0x21, 0x8b, 0x6c, 0x8e, 0x7b, 0x1e, 0xa0, 0x2f, 0x00, 0x5e, 0x4e, 0x31, 0x4b, 0x51, 0xba,
	0x51, 0xb0, 0x7c, 0x0e, 0x52, 0x9a, 0xe3, 0x27, 0xef, 0x01, 0x38, 0x42, 0x77, 0xc7, 0x1e, 0x31,
	0xf1, 0xe5, 0x0a, 0xcd, 0x51, 0x34, 0x0b, 0x2e, 0x37, 0x6d, 0x67, 0xe0, 0xf9, 0x47, 0x26, 0x9a,
	0x9a, 0xb0, 0xa3, 0x89, 0xfc, 0x2a, 0xca, 0xb9, 0x51, 0x10, 0x36, 0x18, 0x6e, 0x71, 0x67, 0x94,
	0x7b, 0xeb, 0x34, 0x47, 0x21, 0x37, 0xa0, 0x12, 0xe1, 0x17, 0xec, 0x01, 0x4b, 0x43, 0x72, 0x85,
	0xce, 0x08, 0xda, 0x7f, 0x15, 0x50, 0x8d, 0x90, 0xe2, 0xdf, 0xd9, 0xc9, 0x91, 0x9f, 0xc1, 0xda,
	0x20, 0xef, 0x44, 0x11, 0xfe, 0x93, 0x11, 0xa0, 0xa9, 0x18, 0xb9, 0x0a, 0x6b, 0x41, 0xbf, 0x1f,
	0xb3, 0x24, 0x45, 0x30, 0x5d, 0x11, 0x15, 0x56, 0x86, 0x18, 0x09, 0x2b, 0x82, 0xc8, 0xff, 0x92,
	0xfb, 0xb0, 0x19, 0x63, 0xe0, 0x34, 0x07, 0xcc, 0x39, 0x8e, 0xc7, 0xa3, 0x18, 0x63, 0x1f, 0x1d,
	0x78, 0xb4, 0x9a, 0x44, 0x63, 0x46, 0x8b, 0x5b, 0x64, 0x1f, 0x2e, 0x3a, 0x45, 0x04, 0x6a, 0x65,
	0x11, 0x1e, 0xb7, 0x8b, 0xf6, 0x2d, 0x41, 0x89, 0xce, 0x4b, 0x6a, 0x01, 0x6c, 0x66, 0x9a, 0xa5,
	0xd3, 0x7b, 0xb0, 0x9a, 0x4c, 0x42, 0x96, 0xa6, 0x86, 0xb9, 0xcb, 0x97, 0x72, 0x5a, 0xc8, 0x20,
	0xf5, 0x09, 0x5e, 0xb4, 0x5e, 0x7d, 0x39, 0x49, 0x58, 0xdc, 0x65, 0x51, 0xc6, 0x22, 0x3c, 0xde,
	0xa4, 0x0b, 0x74, 0xed, 0x5f, 0xeb, 0x70, 0xc9, 0x08, 0x5f, 0x60, 0x9e, 0x63, 0x6f, 0x13, 0xea,
	0xcf, 0x30, 0x90, 0xed, 0xe8, 0x88, 0x25, 0x31, 0x7e, 0x79, 0x31, 0x6d, 0xf0, 0x2b, 0xe0, 0x07,
	0x6e, 0xee, 0x8a, 0x64, 0xec, 0xe4, 0x53, 0xcc, 0x86, 0xc1, 0x38, 0x72, 0x58, 0x7a, 0xc9, 0xce,
	0x12, 0x4c, 0xb9, 0xf1, 0x18, 0xca, 0x98, 0xeb, 0x30, 0x8b, 0xad, 0x0a, 0xa4, 0x1e, 0x16, 0xc4,
	0x16, 0x3c, 0xdc, 0x11, 0x7f, 0x9b, 0x81, 0x1f, 0xe3, 0x91, 0x3a, 0xdc, 0x0b, 0x93, 0x0b, 0x53,
	0xa9, 0x83, 0x68, 0xb0, 0x11, 0x7a, 0x21, 0x1b, 0x7a, 0x3e, 0x33, 0xbd, 0xd7, 0x0c, 0x0f, 0x94,
	0xa3, 0x57, 0xa0, 0x71, 0x9e, 0x91, 0xe7, 0x37, 0x38, 0xa0, 0xd4, 0xf9, 0xca, 0xad, 0xad, 0x89,
	0xf0, 0x29, 0xd0, 0x04, 0x8f, 0xfd, 0x6a, 0xc6, 0x73, 0x21, 0xe5, 0xc9, 0xd1, 0xc8, 0x27, 0x70,
	0x65, 0x88, 0x87, 0x1f, 0x27, 0x4f, 0x98, 0x9f, 0x22, 0x8a, 0xb6, 0x8c, 0xc2, 0xda, 0xba, 0x60,
	0x5e, 0xbe, 0x49, 0x9e, 0xc2, 0xa5, 0x88, 0x7d, 0x39, 0xc6, 0x1d, 0x36, 0x8d, 0xc5, 0x5a, 0x45,
	0x1c, 0xd6, 0xf6, 0xd2, 0x20, 0x91, 0x68, 0x2d, 0x0a, 0x2d, 0x8b, 0x5f, 0x38, 0x6f, 0xfc, 0x62,
	0x96, 0xac, 0xc6, 0x98, 0xde, 0x11, 0x43, 0x1e, 0x94, 0xb5, 0x2a, 0x2a, 0xda, 0xda, 0xfb, 0x6e,
	0x41, 0x91, 0x39, 0xdb, 0x17, 0x4a, 0x1e, 0xad, 0xb6, 0xda, 0xe6, 0x3e, 0xcd, 0xcb, 0x91, 0x67,
	0x40, 0x64, 0x3c, 0xe4, 0x98, 0xe3, 0xda, 0x06, 0x46, 0xd2, 0x59, 0xda, 0xe8, 0x12, 0x41, 0xf2,
	0x00, 0x54, 0x7b, 0x38, 0x0c, 0xbe, 0x3e, 0xb0, 0x5f, 0x4f, 0x30, 0xf8, 0x63, 0x2f, 0x4e, 0x6a,
	0x9b, 0xe2, 0x46, 0x97, 0xfb, 0xf6, 0x30, 0x66, 0x74, 0x61, 0x9b, 0xdc, 0xc4, 0x82, 0xe9, 0xf9,
	0x3e, 0xfa, 0x56, 0xdb, 0xca, 0x73, 0x66, 0x54, 0xf2, 0x01, 0x6c, 0xc9, 0x2f, 0x75, 0x25, 0x21,
	0xae, 0x5d, 0x44, 0xf3, 0xd6, 0xe9, 0x1c, 0x55, 0xfb, 0x5d, 0x09, 0xae, 0x2e, 0x0f, 0x36, 0x72,
	0x0d, 0xae, 0x74, 0xdb, 0x5d, 0xfd, 0xa0, 0xdd, 0xd1, 0x7b, 0xa6, 0x6e, 0x1d, 0x76, 0x7b, 0xf5,
	0x6e, 0x57, 0xef, 0xb4, 0xb0, 0x16, 0x6a, 0xf0, 0xde, 0xd2, 0xad, 0x1e, 0xd5, 0x9b, 0xc6, 0x73,
	0x9d, 0xf2, 0xc2, 0x48, 0x60, 0xab, 0x55, 0xb7, 0xea, 0x3d, 0xd3, 0xa2, 0x7a, 0xfd, 0x59, 0xbb,
	0xf3, 0x44, 0x2d, 0x91, 0xbb, 0x70, 0x7b, 0x4e, 0x6e, 0xba, 0x3b, 0x13, 0x5d, 0xe1, 0xa2, 0x53,
	0xb6, 0xe6, 0x81, 0x61, 0xea, 0xea, 0x2a, 0xb9, 0x0e, 0xef, 0x16, 0x69, 0x33, 0x81, 0xf2, 0x12,
	0x53, 0x9b, 0xa8, 0xd6, 0xd2, 0xd5, 0x35, 0xcc, 0x9e, 0x1b, 0x16, 0xad, 0x77, 0xcc, 0xc7, 0x3a,
	0xed, 0xd1, 0xc6, 0x0b, 0xf5, 0x02, 0xe6, 0x59, 0x32, 0xa5, 0x3c, 0x6e, 0x77, 0xea, 0x07, 0xed,
	0x5f, 0xe9, 0x2d, 0x75, 0x5d, 0xfb, 0xbb, 0x02, 0x97, 0x8d, 0x30, 0x2b, 0x7d, 0xff, 0x1f, 0xe9,
	0x66, 0x79, 0xa4, 0xad, 0x9c, 0x33, 0xd2, 0xb4, 0x7f, 0x2a, 0xf0, 0x0e, 0x2f, 0x5c, 0xe1, 0x10,
	0xcb, 0x76, 0xce, 0xc3, 0x4f, 0xe6, 0x3c, 0x3c, 0xbd, 0x00, 0x67, 0x6e, 0x61, 0x3b, 0xe0, 0xb2,
	0xe1, 0x53, 0xcf, 0x4f, 0xd2, 0xca, 0x9b, 0x2d, 0x0b, 0x59, 0xb2, 0xf4, 0x06, 0x59, 0x72, 0xee,
	0x7e, 0xae, 0x9e, 0xef, 0x7e, 0x6a, 0x4f, 0x79, 0x79, 0x6e, 0x06, 0xe1, 0xe4, 0xdb, 0xba, 0x88,
	0x0d, 0x22, 0x86, 0x84, 0xbc, 0x1f, 0x85, 0xba, 0x77, 0x3e, 0x6d, 0xff, 0x28, 0xc1, 0xb5, 0x54,
	0xdd, 0x93, 0x28, 0x18, 0x87, 0x6f, 0x41, 0x27, 0xf9, 0x09, 0x54, 0xdc, 0x14, 0xcf, 0x58, 0x1c,
	0xc3, 0x7c, 0x93, 0x99, 0x47, 0x3b, 0x4e, 0x1b, 0xbe, 0xa9, 0x04, 0xf9, 0x31, 0x54, 0x45, 0xc7,
	0x29, 0x3a, 0x4a, 0x19, 0x59, 0xa7, 0xb6, 0x9b, 0x79, 0x6e, 0x52, 0x87, 0x75, 0xe6, 0x74, 0x83,
	0xa1, 0xe7, 0x4c, 0x44, 0x5d, 0xab, 0xee, 0xdd, 0x2d, 0xf6, 0xb7, 0x91, 0x1d, 0x8f, 0x23, 0xd6,
	0x0c, 0x5c, 0xcc, 0x35, 0x92, 0x4f, 0x6a, 0x99, 0x8a, 0xf1, 0x12, 0x24, 0x34, 0xb6, 0x7d, 0x17,
	0xe7, 0x95, 0x18, 0x4b, 0xd9, 0x0a, 0x2f, 0x65, 0x79, 0x1a, 0xf9, 0x7e, 0xae, 0x98, 0x74, 0xc6,
	0x23, 0x51, 0x9b, 0xd2, 0x7a, 0xb6, 0xb8, 0xa1, 0x7d, 0x06, 0x57, 0xcd, 0x41, 0x10, 0x25, 0x4d,
	0x2f, 0x72, 0xc6, 0x5e, 0x62, 0x0e, 0x46, 0x6d, 0x57, 0x02, 0xbc, 0x05, 0xa5, 0x81, 0x27, 0xc0,
	0x5d, 0xa1, 0xf8, 0x8f, 0xaf, 0x87, 0x81, 0xc0, 0x0c, 0xd7, 0xc3, 0x00, 0xbb, 0x9b, 0xda, 0x9c,
	0xa4, 0x39, 0x0c, 0x12, 0x29, 0xfb, 0x39, 0xd6, 0x6f, 0xae, 0x29, 0x3d, 0x9b, 0x3b, 0xc5, 0x98,
	0x5c, 0xfa, 0x3d, 0x2a, 0x25, 0xf8, 0x35, 0x89, 0x51, 0x4f, 0xdb, 0x7d, 0x25, 0xbe, 0x55, 0xa6,
	0xd9, 0x52, 0xfb, 0x4d, 0x09, 0x6e, 0xf1, 0xeb, 0x28, 0x5c, 0xc8, 0x2b, 0xa9, 0x3b, 0xe8, 0x77,
	0xfc, 0x6d, 0xc2, 0x02, 0x1b, 0x5c, 0x2c, 0xe3, 0xcf, 0x79, 0xb9, 0x08, 0xfc, 0xb4, 0xbd, 0xca,
	0x51, 0x30, 0x6c, 0xd6, 0xa4, 0x15, 0x69, 0x1f, 0x73, 0xf7, 0x34, 0x87, 0xa6, 0x30, 0xd0, 0x54,
	0x88, 0x3c, 0x81, 0xeb, 0xf1, 0x38, 0x0c, 0x91, 0x2b, 0xa6, 0xcc, 0x61, 0x5e, 0x98, 0xa0, 0x62,
	0xaf, 0xef, 0x39, 0x76, 0x3a, 0x8b, 0xe5, 0x6a, 0xd2, 0x69, 0x9c, 0xda, 0x9f, 0x14, 0xb8, 0x4b,
	0xd9, 0x90, 0xa1, 0x1b, 0x8b, 0x00, 0xa4, 0xc8, 0x48, 0x1c, 0x66, 0x16, 0x2b, 0x4b, 0x42, 0xed,
	0x4c, 0x8b, 0x0b, 0x03, 0x52, 0xe9, 0xdc, 0x03, 0xd2, 0x31, 0x7c, 0x70, 0x8a, 0xb9, 0x71, 0x88,
	0x55, 0x34, 0x9d, 0x9b, 0x3f, 0x9a, 0x9b, 0x9b, 0xdf, 0x99, 0x4b, 0x63, 0x85, 0x01, 0xf8, 0x32,
	0x94, 0x59, 0x14, 0x05, 0x91, 0xb0, 0xac, 0x42, 0xe5, 0x42, 0xfb, 0xad, 0x02, 0xd7, 0xe7, 0x1c,
	0x2b, 0x40, 0x52, 0x9c, 0x7e, 0x94, 0xf9, 0xe9, 0xe7, 0x6d, 0xf9, 0xfc, 0x7b, 0x05, 0x6e, 0x2c,
	0x98, 0xf1, 0x76, 0x5d, 0x25, 0x1f, 0x43, 0xc9, 0xcb, 0x62, 0xf1, 0x1b, 0x5d, 0x2e, 0x64, 0xd7,
	0xfe, 0xa2, 0xc0, 0xa5, 0xae, 0xed, 0x1c, 0xb3, 0x24, 0x3f, 0x51, 0xbe, 0x0f, 0x9b, 0x72, 0x72,
	0x6a, 0xfb, 0x8d, 0xe9, 0xe8, 0xad, 0xd2, 0x22, 0x91, 0x9b, 0x11, 0xb3, 0x2f, 0x7d, 0x79, 0xff,
	0x55, 0x2a, 0x17, 0x3c, 0xd5, 0x0c, 0x6d, 0x84, 0x57, 0x28, 0xcd, 0xe4, 0x79, 0x0d, 0x5b, 0xa7,
	0x8b, 0x1b, 0xa2, 0x00, 0x22, 0x82, 0x07, 0xcc, 0x17, 0xe9, 0xef, 0x22, 0xcd, 0x96, 0xe4, 0x0e,
	0x54, 0xe2, 0x89, 0xef, 0x48, 0xf9, 0x72, 0xfe, 0x36, 0xcc, 0xe8, 0xda, 0x1f, 0x71, 0x8c, 0xec,
	0xa6, 0x3d, 0x7b, 0x3d, 0xab, 0x53, 0x53, 0xbb, 0xb8, 0xd5, 0x24, 0xb3, 0xeb, 0x43, 0x28, 0x47,
	0x58, 0xb5, 0x27, 0xa2, 0x7f, 0x38, 0x01, 0x60, 0xc9, 0x81, 0x99, 0xea, 0xaa, 0x1b, 0x7c, 0xcd,
	0x9b, 0x39, 0x66, 0x8f, 0x50, 0xad, 0xe5, 0x8d, 0x58, 0x07, 0xb3, 0x7d, 0x2c, 0xd0, 0x5d, 0x7d,
	0xa4, 0xfc, 0x90, 0x9e, 0xc0, 0x80, 0x9d, 0xd1, 0x6a, 0x7f, 0x68, 0x1f, 0x89, 0xa7, 0x94, 0xcd,
	0x46, 0x49, 0x55, 0xa8, 0x58, 0x6b, 0x31, 0xbc, 0xcb, 0x87, 0x5d, 0x63, 0x5a, 0xb0, 0x66, 0x4f,
	0x02, 0x9f, 0xc2, 0xba, 0x93, 0xf5, 0xf7, 0xca, 0x99, 0xfd, 0xfd, 0x94, 0x97, 0xdc, 0x82, 0xaa,
	0x33, 0x18, 0xfb, 0xc7, 0x46, 0x7e, 0xe2, 0xcd, 0x93, 0xb4, 0x7f, 0x97, 0xe0, 0xb2, 0xc0, 0x89,
	0x67, 0xc8, 0x73, 0x47, 0x1b, 0xd6, 0x97, 0xbe, 0x17, 0xc5, 0x49, 0xc3, 0x76, 0x0f, 0x3c, 0xff,
	0x38, 0x0d, 0xba, 0x02, 0x8d, 0x1c, 0x82, 0x9a, 0xd9, 0x95, 0x7d, 0x29, 0x8d, 0xc4, 0x0f, 0xe7,
	0xc6, 0xb4, 0x42, 0x27, 0x50, 0xb0, 0x8a, 0x2e, 0xa8, 0x20, 0x16, 0x90, 0x68, 0x01, 0x35, 0x91,
	0x1a, 0xab, 0x7b, 0xef, 0x17, 0x14, 0x9f, 0x00, 0x2e, 0x5d, 0x22, 0x9f, 0x7f, 0x10, 0x2b, 0x17,
	0x1f, 0xc4, 0xbe, 0x80, 0x6b, 0xf1, 0x42, 0x4e, 0xca, 0x2a, 0xc0, 0x1a, 0xf2, 0x6e, 0xd2, 0x93,
	0x19, 0xb4, 0x16, 0x5c, 0x91, 0x9d, 0x2c, 0x37, 0x46, 0x82, 0xf8, 0xe6, 0x70, 0x6b, 0x75, 0x20,
	0xad, 0x4e, 0x96, 0x51, 0xa6, 0x31, 0xfd, 0x46, 0x2a, 0xfe, 0x8c, 0xd9, 0xe6, 0x34, 0xa4, 0x79,
	0xe8, 0x4c, 0xdf, 0x09, 0x22, 0x47, 0xa8, 0xdc, 0xa4, 0x79, 0x92, 0x08, 0xae, 0xc8, 0xe9, 0xa6,
	0x4d, 0xfc, 0x34, 0xb8, 0x66, 0x24, 0xfe, 0xa6, 0x32, 0x72, 0x1f, 0x8a, 0x9b, 0xbd, 0x41, 0xf9,
	0x5f, 0xde, 0xa3, 0x23, 0x43, 0xae, 0xed, 0x3c, 0xeb, 0x31, 0x23, 0x63, 0xd7, 0x3e, 0x82, 0x4d,
	0x3c, 0xa3, 0x31, 0x36, 0xa0, 0x69, 0x23, 0xb7, 0x8d, 0x77, 0x42, 0x2c, 0xd3, 0x5a, 0x55, 0xa1,
	0xd3, 0xf5, 0xfd, 0xff, 0x28, 0xb0, 0xb6, 0xec, 0x75, 0x71, 0xfa, 0x8c, 0x28, 0x06, 0x27, 0xf9,
	0xd0, 0xd8, 0x7c, 0xaa, 0x37, 0xf7, 0xcd, 0xc3, 0x67, 0x38, 0x38, 0x5d, 0x82, 0x4d, 0x49, 0x6b,
	0x77, 0x9e, 0xe3, 0xc0, 0xd2, 0xc2, 0x21, 0x09, 0x07, 0x1b, 0x49, 0xd2, 0x7f, 0xd1, 0x36, 0x2d,
	0x13, 0x47, 0x24, 0x1c, 0x6c, 0x24, 0xa5, 0x2e, 0xb4, 0xf6, 0x2c, 0x63, 0x5f, 0xef, 0xe0, 0x74,
	0x74, 0x11, 0xaa, 0x99, 0xaa, 0x9e, 0xb1, 0x8f, 0x33, 0x51, 0xee, 0x29, 0xd3, 0x3c, 0xec, 0x76,
	0x0d, 0x6a, 0xe1, 0x00, 0x74, 0x81, 0xf3, 0x19, 0x46, 0x03, 0xe7, 0x2a, 0xd3, 0xaa, 0x53, 0x4b,
	0x5d, 0xe7, 0x5f, 0x4d, 0x09, 0x3a, 0x7d, 0xae, 0xb7, 0x1e, 0xa8, 0x95, 0x79, 0xd2, 0x9e, 0x0a,
	0xf3, 0xa4, 0x8f, 0xd5, 0x2a, 0xd7, 0xd4, 0xee, 0xf4, 0xba, 0xd4, 0x78, 0x42, 0xb9, 0x7b, 0x1b,
	0xf7, 0x7f, 0x5d, 0x6c, 0xca, 0x1e, 0xbb, 0xd3, 0x5b, 0x72, 0x07, 0x6e, 0xb6, 0x8c, 0x5e, 0xc7,
	0xb0, 0x7a, 0x87, 0x72, 0xa6, 0xd3, 0xdb, 0x5d, 0xab, 0x87, 0x73, 0x5d, 0xfb, 0x71, 0xbb, 0x59,
	0xb7, 0xda, 0x46, 0x07, 0xd1, 0xb9, 0x01, 0xb5, 0x13, 0x77, 0x95, 0xc6, 0x4f, 0xe1, 0x6e, 0x10,
	0x1d, 0xed, 0xd8, 0x21, 0x4e, 0xfb, 0xac, 0x70, 0x6a, 0xe2, 0xaf, 0x13, 0x0c, 0xe5, 0x9f, 0x06,
	0xc9, 0xd7, 0x3b, 0x71, 0x56, 0xf1, 0x1f, 0x14, 0xe5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d,
	0xf1, 0x36, 0xd5, 0xbc, 0x17, 0x00, 0x00,
}
