// Code generated by protoc-gen-go.
// source: gopkg.in/freddierice/go-hproto.v1/hdfs/erasurecoding.proto
// DO NOT EDIT!

package hproto_hdfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SetErasureCodingPolicyRequestProto struct {
	Src              *string                   `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	EcPolicy         *ErasureCodingPolicyProto `protobuf:"bytes,2,opt,name=ecPolicy" json:"ecPolicy,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *SetErasureCodingPolicyRequestProto) Reset()         { *m = SetErasureCodingPolicyRequestProto{} }
func (m *SetErasureCodingPolicyRequestProto) String() string { return proto.CompactTextString(m) }
func (*SetErasureCodingPolicyRequestProto) ProtoMessage()    {}
func (*SetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{0}
}

func (m *SetErasureCodingPolicyRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *SetErasureCodingPolicyRequestProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

type SetErasureCodingPolicyResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetErasureCodingPolicyResponseProto) Reset()         { *m = SetErasureCodingPolicyResponseProto{} }
func (m *SetErasureCodingPolicyResponseProto) String() string { return proto.CompactTextString(m) }
func (*SetErasureCodingPolicyResponseProto) ProtoMessage()    {}
func (*SetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{1}
}

type GetErasureCodingPoliciesRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetErasureCodingPoliciesRequestProto) Reset()         { *m = GetErasureCodingPoliciesRequestProto{} }
func (m *GetErasureCodingPoliciesRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPoliciesRequestProto) ProtoMessage()    {}
func (*GetErasureCodingPoliciesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{2}
}

type GetErasureCodingPoliciesResponseProto struct {
	EcPolicies       []*ErasureCodingPolicyProto `protobuf:"bytes,1,rep,name=ecPolicies" json:"ecPolicies,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *GetErasureCodingPoliciesResponseProto) Reset()         { *m = GetErasureCodingPoliciesResponseProto{} }
func (m *GetErasureCodingPoliciesResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPoliciesResponseProto) ProtoMessage()    {}
func (*GetErasureCodingPoliciesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{3}
}

func (m *GetErasureCodingPoliciesResponseProto) GetEcPolicies() []*ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicies
	}
	return nil
}

type GetErasureCodingPolicyRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetErasureCodingPolicyRequestProto) Reset()         { *m = GetErasureCodingPolicyRequestProto{} }
func (m *GetErasureCodingPolicyRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPolicyRequestProto) ProtoMessage()    {}
func (*GetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{4}
}

func (m *GetErasureCodingPolicyRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type GetErasureCodingPolicyResponseProto struct {
	EcPolicy         *ErasureCodingPolicyProto `protobuf:"bytes,1,opt,name=ecPolicy" json:"ecPolicy,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *GetErasureCodingPolicyResponseProto) Reset()         { *m = GetErasureCodingPolicyResponseProto{} }
func (m *GetErasureCodingPolicyResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPolicyResponseProto) ProtoMessage()    {}
func (*GetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{5}
}

func (m *GetErasureCodingPolicyResponseProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

// *
// Block erasure coding reconstruction info
type BlockECReconstructionInfoProto struct {
	Block              *ExtendedBlockProto       `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	SourceDnInfos      *DatanodeInfosProto       `protobuf:"bytes,2,req,name=sourceDnInfos" json:"sourceDnInfos,omitempty"`
	TargetDnInfos      *DatanodeInfosProto       `protobuf:"bytes,3,req,name=targetDnInfos" json:"targetDnInfos,omitempty"`
	TargetStorageUuids *StorageUuidsProto        `protobuf:"bytes,4,req,name=targetStorageUuids" json:"targetStorageUuids,omitempty"`
	TargetStorageTypes *StorageTypesProto        `protobuf:"bytes,5,req,name=targetStorageTypes" json:"targetStorageTypes,omitempty"`
	LiveBlockIndices   []byte                    `protobuf:"bytes,6,req,name=liveBlockIndices" json:"liveBlockIndices,omitempty"`
	EcPolicy           *ErasureCodingPolicyProto `protobuf:"bytes,7,req,name=ecPolicy" json:"ecPolicy,omitempty"`
	XXX_unrecognized   []byte                    `json:"-"`
}

func (m *BlockECReconstructionInfoProto) Reset()                    { *m = BlockECReconstructionInfoProto{} }
func (m *BlockECReconstructionInfoProto) String() string            { return proto.CompactTextString(m) }
func (*BlockECReconstructionInfoProto) ProtoMessage()               {}
func (*BlockECReconstructionInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{6} }

func (m *BlockECReconstructionInfoProto) GetBlock() *ExtendedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetSourceDnInfos() *DatanodeInfosProto {
	if m != nil {
		return m.SourceDnInfos
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetTargetDnInfos() *DatanodeInfosProto {
	if m != nil {
		return m.TargetDnInfos
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetTargetStorageUuids() *StorageUuidsProto {
	if m != nil {
		return m.TargetStorageUuids
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetTargetStorageTypes() *StorageTypesProto {
	if m != nil {
		return m.TargetStorageTypes
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetLiveBlockIndices() []byte {
	if m != nil {
		return m.LiveBlockIndices
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

func init() {
	proto.RegisterType((*SetErasureCodingPolicyRequestProto)(nil), "hproto.hdfs.SetErasureCodingPolicyRequestProto")
	proto.RegisterType((*SetErasureCodingPolicyResponseProto)(nil), "hproto.hdfs.SetErasureCodingPolicyResponseProto")
	proto.RegisterType((*GetErasureCodingPoliciesRequestProto)(nil), "hproto.hdfs.GetErasureCodingPoliciesRequestProto")
	proto.RegisterType((*GetErasureCodingPoliciesResponseProto)(nil), "hproto.hdfs.GetErasureCodingPoliciesResponseProto")
	proto.RegisterType((*GetErasureCodingPolicyRequestProto)(nil), "hproto.hdfs.GetErasureCodingPolicyRequestProto")
	proto.RegisterType((*GetErasureCodingPolicyResponseProto)(nil), "hproto.hdfs.GetErasureCodingPolicyResponseProto")
	proto.RegisterType((*BlockECReconstructionInfoProto)(nil), "hproto.hdfs.BlockECReconstructionInfoProto")
}

func init() {
	proto.RegisterFile("gopkg.in/freddierice/go-hproto.v1/hdfs/erasurecoding.proto", fileDescriptor12)
}

var fileDescriptor12 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x95, 0x86, 0xf2, 0x67, 0x16, 0xa4, 0x2a, 0x5c, 0x22, 0x0e, 0xa5, 0x72, 0x09, 0xaa,
	0x90, 0x48, 0xd4, 0x4a, 0x70, 0xe0, 0x82, 0xd8, 0x76, 0xb5, 0xea, 0x05, 0x55, 0x29, 0x3c, 0x40,
	0xb0, 0x67, 0x13, 0xab, 0x91, 0x1d, 0x6c, 0xa7, 0x62, 0xdf, 0x86, 0x87, 0xe4, 0x01, 0x70, 0xec,
	0x82, 0x62, 0x6d, 0x56, 0x2c, 0xbd, 0x44, 0xd6, 0xcc, 0xf7, 0xfd, 0x66, 0x3c, 0x9e, 0xc0, 0x87,
	0x5a, 0x76, 0x37, 0x75, 0xce, 0x45, 0xb1, 0x52, 0xc8, 0x18, 0x47, 0xc5, 0x29, 0x16, 0xb5, 0x7c,
	0xdb, 0x74, 0x4a, 0x1a, 0x99, 0xdf, 0x9e, 0x16, 0x0d, 0x5b, 0xe9, 0x02, 0x55, 0xa5, 0x7b, 0x85,
	0x54, 0x32, 0x2e, 0xea, 0xdc, 0xe5, 0x92, 0xd9, 0x9d, 0x66, 0x10, 0xbc, 0x38, 0xdd, 0x11, 0x34,
	0x7c, 0xbc, 0x9f, 0xac, 0x81, 0x5c, 0xa3, 0x59, 0x78, 0xf2, 0xb9, 0x23, 0x5f, 0xc9, 0x96, 0xd3,
	0x75, 0x89, 0xdf, 0x7b, 0xd4, 0xe6, 0xca, 0x55, 0x39, 0x80, 0x58, 0x2b, 0x9a, 0x46, 0x47, 0x7b,
	0x27, 0x4f, 0xca, 0xe1, 0x98, 0x7c, 0x82, 0xc7, 0x48, 0xbd, 0x32, 0xdd, 0x3b, 0x8a, 0x4e, 0x66,
	0x67, 0x59, 0x3e, 0x6a, 0x25, 0x9f, 0x20, 0x3a, 0x54, 0xf9, 0xd7, 0x46, 0x32, 0x38, 0xde, 0x56,
	0x5a, 0x77, 0x52, 0x68, 0x74, 0x06, 0xf2, 0x1a, 0x5e, 0x2d, 0xa7, 0x64, 0x1c, 0xf5, 0xb8, 0x47,
	0x22, 0x20, 0xdb, 0xae, 0x1b, 0x01, 0x93, 0x05, 0xc0, 0x5d, 0x0f, 0x36, 0x65, 0xef, 0x14, 0xef,
	0xde, 0xfc, 0xc8, 0x48, 0xde, 0x03, 0x59, 0xde, 0x63, 0x72, 0xa4, 0x81, 0xe3, 0xe5, 0xbf, 0xaf,
	0x1d, 0x0c, 0x38, 0xba, 0xdf, 0x80, 0x7f, 0xc5, 0x70, 0x38, 0x6f, 0x25, 0xbd, 0x59, 0x9c, 0x97,
	0x76, 0x6b, 0x84, 0x36, 0xaa, 0xa7, 0x86, 0x4b, 0x71, 0x29, 0x56, 0xd2, 0x57, 0x79, 0x07, 0xfb,
	0xdf, 0x06, 0x85, 0x6b, 0x70, 0x76, 0xf6, 0x32, 0x2c, 0xf1, 0xc3, 0xa0, 0x60, 0xc8, 0x1c, 0xc3,
	0xc3, 0xbd, 0xda, 0x8e, 0xf0, 0x99, 0x96, 0xbd, 0xa2, 0x78, 0xe1, 0x58, 0xda, 0xae, 0xc0, 0xa6,
	0xfd, 0xa2, 0x32, 0x95, 0x90, 0x0c, 0x9d, 0xc2, 0xdb, 0x43, 0xd7, 0x80, 0x31, 0x95, 0xaa, 0xd1,
	0xfc, 0xc1, 0xc4, 0x3b, 0x62, 0x02, 0x57, 0xf2, 0x19, 0x12, 0x1f, 0xb8, 0x36, 0x52, 0x55, 0x35,
	0x7e, 0xed, 0x39, 0xd3, 0xe9, 0x03, 0xc7, 0x3a, 0x0c, 0x58, 0x63, 0x81, 0x47, 0x4d, 0x38, 0x37,
	0x78, 0x5f, 0xd6, 0x9d, 0x5d, 0x94, 0xfd, 0xed, 0x3c, 0x27, 0x98, 0xe2, 0xb9, 0x44, 0xf2, 0x06,
	0x0e, 0x5a, 0x7e, 0x8b, 0x6e, 0x8c, 0x97, 0x82, 0xd9, 0x7f, 0x52, 0xa7, 0x0f, 0x2d, 0xed, 0x69,
	0xb9, 0x11, 0x0f, 0x9e, 0xfd, 0x91, 0xab, 0xf8, 0xbf, 0xcf, 0x3e, 0xff, 0x08, 0x99, 0x54, 0x75,
	0x5e, 0x75, 0x15, 0x6d, 0x30, 0x30, 0xbb, 0x23, 0x95, 0xad, 0x3f, 0xcc, 0x9f, 0x87, 0xb0, 0x21,
	0xa6, 0x7f, 0x46, 0xd1, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xc3, 0x16, 0x96, 0x90, 0x04,
	0x00, 0x00,
}
