// Code generated by protoc-gen-go.
// source: gopkg.in/freddierice/go-hproto.v1/hdfs/hdfs.proto
// DO NOT EDIT!

package hproto_hdfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hproto_common "gopkg.in/freddierice/go-hproto.v1/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// *
// Types of recognized storage media.
type StorageTypeProto int32

const (
	StorageTypeProto_DISK     StorageTypeProto = 1
	StorageTypeProto_SSD      StorageTypeProto = 2
	StorageTypeProto_ARCHIVE  StorageTypeProto = 3
	StorageTypeProto_RAM_DISK StorageTypeProto = 4
)

var StorageTypeProto_name = map[int32]string{
	1: "DISK",
	2: "SSD",
	3: "ARCHIVE",
	4: "RAM_DISK",
}
var StorageTypeProto_value = map[string]int32{
	"DISK":     1,
	"SSD":      2,
	"ARCHIVE":  3,
	"RAM_DISK": 4,
}

func (x StorageTypeProto) Enum() *StorageTypeProto {
	p := new(StorageTypeProto)
	*p = x
	return p
}
func (x StorageTypeProto) String() string {
	return proto.EnumName(StorageTypeProto_name, int32(x))
}
func (x *StorageTypeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StorageTypeProto_value, data, "StorageTypeProto")
	if err != nil {
		return err
	}
	*x = StorageTypeProto(value)
	return nil
}
func (StorageTypeProto) EnumDescriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

// *
// Cipher suite.
type CipherSuiteProto int32

const (
	CipherSuiteProto_UNKNOWN           CipherSuiteProto = 1
	CipherSuiteProto_AES_CTR_NOPADDING CipherSuiteProto = 2
)

var CipherSuiteProto_name = map[int32]string{
	1: "UNKNOWN",
	2: "AES_CTR_NOPADDING",
}
var CipherSuiteProto_value = map[string]int32{
	"UNKNOWN":           1,
	"AES_CTR_NOPADDING": 2,
}

func (x CipherSuiteProto) Enum() *CipherSuiteProto {
	p := new(CipherSuiteProto)
	*p = x
	return p
}
func (x CipherSuiteProto) String() string {
	return proto.EnumName(CipherSuiteProto_name, int32(x))
}
func (x *CipherSuiteProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CipherSuiteProto_value, data, "CipherSuiteProto")
	if err != nil {
		return err
	}
	*x = CipherSuiteProto(value)
	return nil
}
func (CipherSuiteProto) EnumDescriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

// *
// Crypto protocol version used to access encrypted files.
type CryptoProtocolVersionProto int32

const (
	CryptoProtocolVersionProto_UNKNOWN_PROTOCOL_VERSION CryptoProtocolVersionProto = 1
	CryptoProtocolVersionProto_ENCRYPTION_ZONES         CryptoProtocolVersionProto = 2
)

var CryptoProtocolVersionProto_name = map[int32]string{
	1: "UNKNOWN_PROTOCOL_VERSION",
	2: "ENCRYPTION_ZONES",
}
var CryptoProtocolVersionProto_value = map[string]int32{
	"UNKNOWN_PROTOCOL_VERSION": 1,
	"ENCRYPTION_ZONES":         2,
}

func (x CryptoProtocolVersionProto) Enum() *CryptoProtocolVersionProto {
	p := new(CryptoProtocolVersionProto)
	*p = x
	return p
}
func (x CryptoProtocolVersionProto) String() string {
	return proto.EnumName(CryptoProtocolVersionProto_name, int32(x))
}
func (x *CryptoProtocolVersionProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CryptoProtocolVersionProto_value, data, "CryptoProtocolVersionProto")
	if err != nil {
		return err
	}
	*x = CryptoProtocolVersionProto(value)
	return nil
}
func (CryptoProtocolVersionProto) EnumDescriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

// *
// Checksum algorithms/types used in HDFS
// Make sure this enum's integer values match enum values' id properties defined
// in org.apache.hadoop.util.DataChecksum.Type
type ChecksumTypeProto int32

const (
	ChecksumTypeProto_CHECKSUM_NULL   ChecksumTypeProto = 0
	ChecksumTypeProto_CHECKSUM_CRC32  ChecksumTypeProto = 1
	ChecksumTypeProto_CHECKSUM_CRC32C ChecksumTypeProto = 2
)

var ChecksumTypeProto_name = map[int32]string{
	0: "CHECKSUM_NULL",
	1: "CHECKSUM_CRC32",
	2: "CHECKSUM_CRC32C",
}
var ChecksumTypeProto_value = map[string]int32{
	"CHECKSUM_NULL":   0,
	"CHECKSUM_CRC32":  1,
	"CHECKSUM_CRC32C": 2,
}

func (x ChecksumTypeProto) Enum() *ChecksumTypeProto {
	p := new(ChecksumTypeProto)
	*p = x
	return p
}
func (x ChecksumTypeProto) String() string {
	return proto.EnumName(ChecksumTypeProto_name, int32(x))
}
func (x *ChecksumTypeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChecksumTypeProto_value, data, "ChecksumTypeProto")
	if err != nil {
		return err
	}
	*x = ChecksumTypeProto(value)
	return nil
}
func (ChecksumTypeProto) EnumDescriptor() ([]byte, []int) { return fileDescriptor13, []int{3} }

type DatanodeInfoProto_AdminState int32

const (
	DatanodeInfoProto_NORMAL                  DatanodeInfoProto_AdminState = 0
	DatanodeInfoProto_DECOMMISSION_INPROGRESS DatanodeInfoProto_AdminState = 1
	DatanodeInfoProto_DECOMMISSIONED          DatanodeInfoProto_AdminState = 2
	DatanodeInfoProto_ENTERING_MAINTENANCE    DatanodeInfoProto_AdminState = 3
	DatanodeInfoProto_IN_MAINTENANCE          DatanodeInfoProto_AdminState = 4
)

var DatanodeInfoProto_AdminState_name = map[int32]string{
	0: "NORMAL",
	1: "DECOMMISSION_INPROGRESS",
	2: "DECOMMISSIONED",
	3: "ENTERING_MAINTENANCE",
	4: "IN_MAINTENANCE",
}
var DatanodeInfoProto_AdminState_value = map[string]int32{
	"NORMAL":                  0,
	"DECOMMISSION_INPROGRESS": 1,
	"DECOMMISSIONED":          2,
	"ENTERING_MAINTENANCE":    3,
	"IN_MAINTENANCE":          4,
}

func (x DatanodeInfoProto_AdminState) Enum() *DatanodeInfoProto_AdminState {
	p := new(DatanodeInfoProto_AdminState)
	*p = x
	return p
}
func (x DatanodeInfoProto_AdminState) String() string {
	return proto.EnumName(DatanodeInfoProto_AdminState_name, int32(x))
}
func (x *DatanodeInfoProto_AdminState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DatanodeInfoProto_AdminState_value, data, "DatanodeInfoProto_AdminState")
	if err != nil {
		return err
	}
	*x = DatanodeInfoProto_AdminState(value)
	return nil
}
func (DatanodeInfoProto_AdminState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{4, 0}
}

type DatanodeStorageProto_StorageState int32

const (
	DatanodeStorageProto_NORMAL           DatanodeStorageProto_StorageState = 0
	DatanodeStorageProto_READ_ONLY_SHARED DatanodeStorageProto_StorageState = 1
)

var DatanodeStorageProto_StorageState_name = map[int32]string{
	0: "NORMAL",
	1: "READ_ONLY_SHARED",
}
var DatanodeStorageProto_StorageState_value = map[string]int32{
	"NORMAL":           0,
	"READ_ONLY_SHARED": 1,
}

func (x DatanodeStorageProto_StorageState) Enum() *DatanodeStorageProto_StorageState {
	p := new(DatanodeStorageProto_StorageState)
	*p = x
	return p
}
func (x DatanodeStorageProto_StorageState) String() string {
	return proto.EnumName(DatanodeStorageProto_StorageState_name, int32(x))
}
func (x *DatanodeStorageProto_StorageState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DatanodeStorageProto_StorageState_value, data, "DatanodeStorageProto_StorageState")
	if err != nil {
		return err
	}
	*x = DatanodeStorageProto_StorageState(value)
	return nil
}
func (DatanodeStorageProto_StorageState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{5, 0}
}

type HdfsFileStatusProto_FileType int32

const (
	HdfsFileStatusProto_IS_DIR     HdfsFileStatusProto_FileType = 1
	HdfsFileStatusProto_IS_FILE    HdfsFileStatusProto_FileType = 2
	HdfsFileStatusProto_IS_SYMLINK HdfsFileStatusProto_FileType = 3
)

var HdfsFileStatusProto_FileType_name = map[int32]string{
	1: "IS_DIR",
	2: "IS_FILE",
	3: "IS_SYMLINK",
}
var HdfsFileStatusProto_FileType_value = map[string]int32{
	"IS_DIR":     1,
	"IS_FILE":    2,
	"IS_SYMLINK": 3,
}

func (x HdfsFileStatusProto_FileType) Enum() *HdfsFileStatusProto_FileType {
	p := new(HdfsFileStatusProto_FileType)
	*p = x
	return p
}
func (x HdfsFileStatusProto_FileType) String() string {
	return proto.EnumName(HdfsFileStatusProto_FileType_name, int32(x))
}
func (x *HdfsFileStatusProto_FileType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HdfsFileStatusProto_FileType_value, data, "HdfsFileStatusProto_FileType")
	if err != nil {
		return err
	}
	*x = HdfsFileStatusProto_FileType(value)
	return nil
}
func (HdfsFileStatusProto_FileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{25, 0}
}

// *
// Extended block idenfies a block
type ExtendedBlockProto struct {
	PoolId           *string `protobuf:"bytes,1,req,name=poolId" json:"poolId,omitempty"`
	BlockId          *uint64 `protobuf:"varint,2,req,name=blockId" json:"blockId,omitempty"`
	GenerationStamp  *uint64 `protobuf:"varint,3,req,name=generationStamp" json:"generationStamp,omitempty"`
	NumBytes         *uint64 `protobuf:"varint,4,opt,name=numBytes,def=0" json:"numBytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExtendedBlockProto) Reset()                    { *m = ExtendedBlockProto{} }
func (m *ExtendedBlockProto) String() string            { return proto.CompactTextString(m) }
func (*ExtendedBlockProto) ProtoMessage()               {}
func (*ExtendedBlockProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

const Default_ExtendedBlockProto_NumBytes uint64 = 0

func (m *ExtendedBlockProto) GetPoolId() string {
	if m != nil && m.PoolId != nil {
		return *m.PoolId
	}
	return ""
}

func (m *ExtendedBlockProto) GetBlockId() uint64 {
	if m != nil && m.BlockId != nil {
		return *m.BlockId
	}
	return 0
}

func (m *ExtendedBlockProto) GetGenerationStamp() uint64 {
	if m != nil && m.GenerationStamp != nil {
		return *m.GenerationStamp
	}
	return 0
}

func (m *ExtendedBlockProto) GetNumBytes() uint64 {
	if m != nil && m.NumBytes != nil {
		return *m.NumBytes
	}
	return Default_ExtendedBlockProto_NumBytes
}

// *
// Identifies a Datanode
type DatanodeIDProto struct {
	IpAddr       *string `protobuf:"bytes,1,req,name=ipAddr" json:"ipAddr,omitempty"`
	HostName     *string `protobuf:"bytes,2,req,name=hostName" json:"hostName,omitempty"`
	DatanodeUuid *string `protobuf:"bytes,3,req,name=datanodeUuid" json:"datanodeUuid,omitempty"`
	// upgraded clusters this is the same
	// as the original StorageID of the
	// Datanode.
	XferPort         *uint32 `protobuf:"varint,4,req,name=xferPort" json:"xferPort,omitempty"`
	InfoPort         *uint32 `protobuf:"varint,5,req,name=infoPort" json:"infoPort,omitempty"`
	IpcPort          *uint32 `protobuf:"varint,6,req,name=ipcPort" json:"ipcPort,omitempty"`
	InfoSecurePort   *uint32 `protobuf:"varint,7,opt,name=infoSecurePort,def=0" json:"infoSecurePort,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DatanodeIDProto) Reset()                    { *m = DatanodeIDProto{} }
func (m *DatanodeIDProto) String() string            { return proto.CompactTextString(m) }
func (*DatanodeIDProto) ProtoMessage()               {}
func (*DatanodeIDProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

const Default_DatanodeIDProto_InfoSecurePort uint32 = 0

func (m *DatanodeIDProto) GetIpAddr() string {
	if m != nil && m.IpAddr != nil {
		return *m.IpAddr
	}
	return ""
}

func (m *DatanodeIDProto) GetHostName() string {
	if m != nil && m.HostName != nil {
		return *m.HostName
	}
	return ""
}

func (m *DatanodeIDProto) GetDatanodeUuid() string {
	if m != nil && m.DatanodeUuid != nil {
		return *m.DatanodeUuid
	}
	return ""
}

func (m *DatanodeIDProto) GetXferPort() uint32 {
	if m != nil && m.XferPort != nil {
		return *m.XferPort
	}
	return 0
}

func (m *DatanodeIDProto) GetInfoPort() uint32 {
	if m != nil && m.InfoPort != nil {
		return *m.InfoPort
	}
	return 0
}

func (m *DatanodeIDProto) GetIpcPort() uint32 {
	if m != nil && m.IpcPort != nil {
		return *m.IpcPort
	}
	return 0
}

func (m *DatanodeIDProto) GetInfoSecurePort() uint32 {
	if m != nil && m.InfoSecurePort != nil {
		return *m.InfoSecurePort
	}
	return Default_DatanodeIDProto_InfoSecurePort
}

// *
// Datanode local information
type DatanodeLocalInfoProto struct {
	SoftwareVersion  *string `protobuf:"bytes,1,req,name=softwareVersion" json:"softwareVersion,omitempty"`
	ConfigVersion    *string `protobuf:"bytes,2,req,name=configVersion" json:"configVersion,omitempty"`
	Uptime           *uint64 `protobuf:"varint,3,req,name=uptime" json:"uptime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DatanodeLocalInfoProto) Reset()                    { *m = DatanodeLocalInfoProto{} }
func (m *DatanodeLocalInfoProto) String() string            { return proto.CompactTextString(m) }
func (*DatanodeLocalInfoProto) ProtoMessage()               {}
func (*DatanodeLocalInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

func (m *DatanodeLocalInfoProto) GetSoftwareVersion() string {
	if m != nil && m.SoftwareVersion != nil {
		return *m.SoftwareVersion
	}
	return ""
}

func (m *DatanodeLocalInfoProto) GetConfigVersion() string {
	if m != nil && m.ConfigVersion != nil {
		return *m.ConfigVersion
	}
	return ""
}

func (m *DatanodeLocalInfoProto) GetUptime() uint64 {
	if m != nil && m.Uptime != nil {
		return *m.Uptime
	}
	return 0
}

// *
// DatanodeInfo array
type DatanodeInfosProto struct {
	Datanodes        []*DatanodeInfoProto `protobuf:"bytes,1,rep,name=datanodes" json:"datanodes,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *DatanodeInfosProto) Reset()                    { *m = DatanodeInfosProto{} }
func (m *DatanodeInfosProto) String() string            { return proto.CompactTextString(m) }
func (*DatanodeInfosProto) ProtoMessage()               {}
func (*DatanodeInfosProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{3} }

func (m *DatanodeInfosProto) GetDatanodes() []*DatanodeInfoProto {
	if m != nil {
		return m.Datanodes
	}
	return nil
}

// *
// The status of a Datanode
type DatanodeInfoProto struct {
	Id                  *DatanodeIDProto              `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Capacity            *uint64                       `protobuf:"varint,2,opt,name=capacity,def=0" json:"capacity,omitempty"`
	DfsUsed             *uint64                       `protobuf:"varint,3,opt,name=dfsUsed,def=0" json:"dfsUsed,omitempty"`
	Remaining           *uint64                       `protobuf:"varint,4,opt,name=remaining,def=0" json:"remaining,omitempty"`
	BlockPoolUsed       *uint64                       `protobuf:"varint,5,opt,name=blockPoolUsed,def=0" json:"blockPoolUsed,omitempty"`
	LastUpdate          *uint64                       `protobuf:"varint,6,opt,name=lastUpdate,def=0" json:"lastUpdate,omitempty"`
	XceiverCount        *uint32                       `protobuf:"varint,7,opt,name=xceiverCount,def=0" json:"xceiverCount,omitempty"`
	Location            *string                       `protobuf:"bytes,8,opt,name=location" json:"location,omitempty"`
	AdminState          *DatanodeInfoProto_AdminState `protobuf:"varint,10,opt,name=adminState,enum=hproto.hdfs.DatanodeInfoProto_AdminState,def=0" json:"adminState,omitempty"`
	CacheCapacity       *uint64                       `protobuf:"varint,11,opt,name=cacheCapacity,def=0" json:"cacheCapacity,omitempty"`
	CacheUsed           *uint64                       `protobuf:"varint,12,opt,name=cacheUsed,def=0" json:"cacheUsed,omitempty"`
	LastUpdateMonotonic *uint64                       `protobuf:"varint,13,opt,name=lastUpdateMonotonic,def=0" json:"lastUpdateMonotonic,omitempty"`
	UpgradeDomain       *string                       `protobuf:"bytes,14,opt,name=upgradeDomain" json:"upgradeDomain,omitempty"`
	XXX_unrecognized    []byte                        `json:"-"`
}

func (m *DatanodeInfoProto) Reset()                    { *m = DatanodeInfoProto{} }
func (m *DatanodeInfoProto) String() string            { return proto.CompactTextString(m) }
func (*DatanodeInfoProto) ProtoMessage()               {}
func (*DatanodeInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{4} }

const Default_DatanodeInfoProto_Capacity uint64 = 0
const Default_DatanodeInfoProto_DfsUsed uint64 = 0
const Default_DatanodeInfoProto_Remaining uint64 = 0
const Default_DatanodeInfoProto_BlockPoolUsed uint64 = 0
const Default_DatanodeInfoProto_LastUpdate uint64 = 0
const Default_DatanodeInfoProto_XceiverCount uint32 = 0
const Default_DatanodeInfoProto_AdminState DatanodeInfoProto_AdminState = DatanodeInfoProto_NORMAL
const Default_DatanodeInfoProto_CacheCapacity uint64 = 0
const Default_DatanodeInfoProto_CacheUsed uint64 = 0
const Default_DatanodeInfoProto_LastUpdateMonotonic uint64 = 0

func (m *DatanodeInfoProto) GetId() *DatanodeIDProto {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DatanodeInfoProto) GetCapacity() uint64 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return Default_DatanodeInfoProto_Capacity
}

func (m *DatanodeInfoProto) GetDfsUsed() uint64 {
	if m != nil && m.DfsUsed != nil {
		return *m.DfsUsed
	}
	return Default_DatanodeInfoProto_DfsUsed
}

func (m *DatanodeInfoProto) GetRemaining() uint64 {
	if m != nil && m.Remaining != nil {
		return *m.Remaining
	}
	return Default_DatanodeInfoProto_Remaining
}

func (m *DatanodeInfoProto) GetBlockPoolUsed() uint64 {
	if m != nil && m.BlockPoolUsed != nil {
		return *m.BlockPoolUsed
	}
	return Default_DatanodeInfoProto_BlockPoolUsed
}

func (m *DatanodeInfoProto) GetLastUpdate() uint64 {
	if m != nil && m.LastUpdate != nil {
		return *m.LastUpdate
	}
	return Default_DatanodeInfoProto_LastUpdate
}

func (m *DatanodeInfoProto) GetXceiverCount() uint32 {
	if m != nil && m.XceiverCount != nil {
		return *m.XceiverCount
	}
	return Default_DatanodeInfoProto_XceiverCount
}

func (m *DatanodeInfoProto) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *DatanodeInfoProto) GetAdminState() DatanodeInfoProto_AdminState {
	if m != nil && m.AdminState != nil {
		return *m.AdminState
	}
	return Default_DatanodeInfoProto_AdminState
}

func (m *DatanodeInfoProto) GetCacheCapacity() uint64 {
	if m != nil && m.CacheCapacity != nil {
		return *m.CacheCapacity
	}
	return Default_DatanodeInfoProto_CacheCapacity
}

func (m *DatanodeInfoProto) GetCacheUsed() uint64 {
	if m != nil && m.CacheUsed != nil {
		return *m.CacheUsed
	}
	return Default_DatanodeInfoProto_CacheUsed
}

func (m *DatanodeInfoProto) GetLastUpdateMonotonic() uint64 {
	if m != nil && m.LastUpdateMonotonic != nil {
		return *m.LastUpdateMonotonic
	}
	return Default_DatanodeInfoProto_LastUpdateMonotonic
}

func (m *DatanodeInfoProto) GetUpgradeDomain() string {
	if m != nil && m.UpgradeDomain != nil {
		return *m.UpgradeDomain
	}
	return ""
}

// *
// Represents a storage available on the datanode
type DatanodeStorageProto struct {
	StorageUuid      *string                            `protobuf:"bytes,1,req,name=storageUuid" json:"storageUuid,omitempty"`
	State            *DatanodeStorageProto_StorageState `protobuf:"varint,2,opt,name=state,enum=hproto.hdfs.DatanodeStorageProto_StorageState,def=0" json:"state,omitempty"`
	StorageType      *StorageTypeProto                  `protobuf:"varint,3,opt,name=storageType,enum=hproto.hdfs.StorageTypeProto,def=1" json:"storageType,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *DatanodeStorageProto) Reset()                    { *m = DatanodeStorageProto{} }
func (m *DatanodeStorageProto) String() string            { return proto.CompactTextString(m) }
func (*DatanodeStorageProto) ProtoMessage()               {}
func (*DatanodeStorageProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{5} }

const Default_DatanodeStorageProto_State DatanodeStorageProto_StorageState = DatanodeStorageProto_NORMAL
const Default_DatanodeStorageProto_StorageType StorageTypeProto = StorageTypeProto_DISK

func (m *DatanodeStorageProto) GetStorageUuid() string {
	if m != nil && m.StorageUuid != nil {
		return *m.StorageUuid
	}
	return ""
}

func (m *DatanodeStorageProto) GetState() DatanodeStorageProto_StorageState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return Default_DatanodeStorageProto_State
}

func (m *DatanodeStorageProto) GetStorageType() StorageTypeProto {
	if m != nil && m.StorageType != nil {
		return *m.StorageType
	}
	return Default_DatanodeStorageProto_StorageType
}

type StorageReportProto struct {
	StorageUuid      *string               `protobuf:"bytes,1,req,name=storageUuid" json:"storageUuid,omitempty"`
	Failed           *bool                 `protobuf:"varint,2,opt,name=failed,def=0" json:"failed,omitempty"`
	Capacity         *uint64               `protobuf:"varint,3,opt,name=capacity,def=0" json:"capacity,omitempty"`
	DfsUsed          *uint64               `protobuf:"varint,4,opt,name=dfsUsed,def=0" json:"dfsUsed,omitempty"`
	Remaining        *uint64               `protobuf:"varint,5,opt,name=remaining,def=0" json:"remaining,omitempty"`
	BlockPoolUsed    *uint64               `protobuf:"varint,6,opt,name=blockPoolUsed,def=0" json:"blockPoolUsed,omitempty"`
	Storage          *DatanodeStorageProto `protobuf:"bytes,7,opt,name=storage" json:"storage,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *StorageReportProto) Reset()                    { *m = StorageReportProto{} }
func (m *StorageReportProto) String() string            { return proto.CompactTextString(m) }
func (*StorageReportProto) ProtoMessage()               {}
func (*StorageReportProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{6} }

const Default_StorageReportProto_Failed bool = false
const Default_StorageReportProto_Capacity uint64 = 0
const Default_StorageReportProto_DfsUsed uint64 = 0
const Default_StorageReportProto_Remaining uint64 = 0
const Default_StorageReportProto_BlockPoolUsed uint64 = 0

func (m *StorageReportProto) GetStorageUuid() string {
	if m != nil && m.StorageUuid != nil {
		return *m.StorageUuid
	}
	return ""
}

func (m *StorageReportProto) GetFailed() bool {
	if m != nil && m.Failed != nil {
		return *m.Failed
	}
	return Default_StorageReportProto_Failed
}

func (m *StorageReportProto) GetCapacity() uint64 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return Default_StorageReportProto_Capacity
}

func (m *StorageReportProto) GetDfsUsed() uint64 {
	if m != nil && m.DfsUsed != nil {
		return *m.DfsUsed
	}
	return Default_StorageReportProto_DfsUsed
}

func (m *StorageReportProto) GetRemaining() uint64 {
	if m != nil && m.Remaining != nil {
		return *m.Remaining
	}
	return Default_StorageReportProto_Remaining
}

func (m *StorageReportProto) GetBlockPoolUsed() uint64 {
	if m != nil && m.BlockPoolUsed != nil {
		return *m.BlockPoolUsed
	}
	return Default_StorageReportProto_BlockPoolUsed
}

func (m *StorageReportProto) GetStorage() *DatanodeStorageProto {
	if m != nil {
		return m.Storage
	}
	return nil
}

// *
// Summary of a file or directory
type ContentSummaryProto struct {
	Length           *uint64                     `protobuf:"varint,1,req,name=length" json:"length,omitempty"`
	FileCount        *uint64                     `protobuf:"varint,2,req,name=fileCount" json:"fileCount,omitempty"`
	DirectoryCount   *uint64                     `protobuf:"varint,3,req,name=directoryCount" json:"directoryCount,omitempty"`
	Quota            *uint64                     `protobuf:"varint,4,req,name=quota" json:"quota,omitempty"`
	SpaceConsumed    *uint64                     `protobuf:"varint,5,req,name=spaceConsumed" json:"spaceConsumed,omitempty"`
	SpaceQuota       *uint64                     `protobuf:"varint,6,req,name=spaceQuota" json:"spaceQuota,omitempty"`
	TypeQuotaInfos   *StorageTypeQuotaInfosProto `protobuf:"bytes,7,opt,name=typeQuotaInfos" json:"typeQuotaInfos,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *ContentSummaryProto) Reset()                    { *m = ContentSummaryProto{} }
func (m *ContentSummaryProto) String() string            { return proto.CompactTextString(m) }
func (*ContentSummaryProto) ProtoMessage()               {}
func (*ContentSummaryProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{7} }

func (m *ContentSummaryProto) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *ContentSummaryProto) GetFileCount() uint64 {
	if m != nil && m.FileCount != nil {
		return *m.FileCount
	}
	return 0
}

func (m *ContentSummaryProto) GetDirectoryCount() uint64 {
	if m != nil && m.DirectoryCount != nil {
		return *m.DirectoryCount
	}
	return 0
}

func (m *ContentSummaryProto) GetQuota() uint64 {
	if m != nil && m.Quota != nil {
		return *m.Quota
	}
	return 0
}

func (m *ContentSummaryProto) GetSpaceConsumed() uint64 {
	if m != nil && m.SpaceConsumed != nil {
		return *m.SpaceConsumed
	}
	return 0
}

func (m *ContentSummaryProto) GetSpaceQuota() uint64 {
	if m != nil && m.SpaceQuota != nil {
		return *m.SpaceQuota
	}
	return 0
}

func (m *ContentSummaryProto) GetTypeQuotaInfos() *StorageTypeQuotaInfosProto {
	if m != nil {
		return m.TypeQuotaInfos
	}
	return nil
}

// *
// Summary of quota usage of a directory
type QuotaUsageProto struct {
	FileAndDirectoryCount *uint64                     `protobuf:"varint,1,req,name=fileAndDirectoryCount" json:"fileAndDirectoryCount,omitempty"`
	Quota                 *uint64                     `protobuf:"varint,2,req,name=quota" json:"quota,omitempty"`
	SpaceConsumed         *uint64                     `protobuf:"varint,3,req,name=spaceConsumed" json:"spaceConsumed,omitempty"`
	SpaceQuota            *uint64                     `protobuf:"varint,4,req,name=spaceQuota" json:"spaceQuota,omitempty"`
	TypeQuotaInfos        *StorageTypeQuotaInfosProto `protobuf:"bytes,5,opt,name=typeQuotaInfos" json:"typeQuotaInfos,omitempty"`
	XXX_unrecognized      []byte                      `json:"-"`
}

func (m *QuotaUsageProto) Reset()                    { *m = QuotaUsageProto{} }
func (m *QuotaUsageProto) String() string            { return proto.CompactTextString(m) }
func (*QuotaUsageProto) ProtoMessage()               {}
func (*QuotaUsageProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{8} }

func (m *QuotaUsageProto) GetFileAndDirectoryCount() uint64 {
	if m != nil && m.FileAndDirectoryCount != nil {
		return *m.FileAndDirectoryCount
	}
	return 0
}

func (m *QuotaUsageProto) GetQuota() uint64 {
	if m != nil && m.Quota != nil {
		return *m.Quota
	}
	return 0
}

func (m *QuotaUsageProto) GetSpaceConsumed() uint64 {
	if m != nil && m.SpaceConsumed != nil {
		return *m.SpaceConsumed
	}
	return 0
}

func (m *QuotaUsageProto) GetSpaceQuota() uint64 {
	if m != nil && m.SpaceQuota != nil {
		return *m.SpaceQuota
	}
	return 0
}

func (m *QuotaUsageProto) GetTypeQuotaInfos() *StorageTypeQuotaInfosProto {
	if m != nil {
		return m.TypeQuotaInfos
	}
	return nil
}

// *
// Storage type quota and usage information of a file or directory
type StorageTypeQuotaInfosProto struct {
	TypeQuotaInfo    []*StorageTypeQuotaInfoProto `protobuf:"bytes,1,rep,name=typeQuotaInfo" json:"typeQuotaInfo,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *StorageTypeQuotaInfosProto) Reset()                    { *m = StorageTypeQuotaInfosProto{} }
func (m *StorageTypeQuotaInfosProto) String() string            { return proto.CompactTextString(m) }
func (*StorageTypeQuotaInfosProto) ProtoMessage()               {}
func (*StorageTypeQuotaInfosProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{9} }

func (m *StorageTypeQuotaInfosProto) GetTypeQuotaInfo() []*StorageTypeQuotaInfoProto {
	if m != nil {
		return m.TypeQuotaInfo
	}
	return nil
}

type StorageTypeQuotaInfoProto struct {
	Type             *StorageTypeProto `protobuf:"varint,1,req,name=type,enum=hproto.hdfs.StorageTypeProto" json:"type,omitempty"`
	Quota            *uint64           `protobuf:"varint,2,req,name=quota" json:"quota,omitempty"`
	Consumed         *uint64           `protobuf:"varint,3,req,name=consumed" json:"consumed,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *StorageTypeQuotaInfoProto) Reset()                    { *m = StorageTypeQuotaInfoProto{} }
func (m *StorageTypeQuotaInfoProto) String() string            { return proto.CompactTextString(m) }
func (*StorageTypeQuotaInfoProto) ProtoMessage()               {}
func (*StorageTypeQuotaInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{10} }

func (m *StorageTypeQuotaInfoProto) GetType() StorageTypeProto {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return StorageTypeProto_DISK
}

func (m *StorageTypeQuotaInfoProto) GetQuota() uint64 {
	if m != nil && m.Quota != nil {
		return *m.Quota
	}
	return 0
}

func (m *StorageTypeQuotaInfoProto) GetConsumed() uint64 {
	if m != nil && m.Consumed != nil {
		return *m.Consumed
	}
	return 0
}

// *
// Contains a list of paths corresponding to corrupt files and a cookie
// used for iterative calls to NameNode.listCorruptFileBlocks.
//
type CorruptFileBlocksProto struct {
	Files            []string `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	Cookie           *string  `protobuf:"bytes,2,req,name=cookie" json:"cookie,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CorruptFileBlocksProto) Reset()                    { *m = CorruptFileBlocksProto{} }
func (m *CorruptFileBlocksProto) String() string            { return proto.CompactTextString(m) }
func (*CorruptFileBlocksProto) ProtoMessage()               {}
func (*CorruptFileBlocksProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{11} }

func (m *CorruptFileBlocksProto) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *CorruptFileBlocksProto) GetCookie() string {
	if m != nil && m.Cookie != nil {
		return *m.Cookie
	}
	return ""
}

// *
// File or Directory permision - same spec as posix
type FsPermissionProto struct {
	Perm             *uint32 `protobuf:"varint,1,req,name=perm" json:"perm,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FsPermissionProto) Reset()                    { *m = FsPermissionProto{} }
func (m *FsPermissionProto) String() string            { return proto.CompactTextString(m) }
func (*FsPermissionProto) ProtoMessage()               {}
func (*FsPermissionProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{12} }

func (m *FsPermissionProto) GetPerm() uint32 {
	if m != nil && m.Perm != nil {
		return *m.Perm
	}
	return 0
}

// *
// A list of storage types.
type StorageTypesProto struct {
	StorageTypes     []StorageTypeProto `protobuf:"varint,1,rep,name=storageTypes,enum=hproto.hdfs.StorageTypeProto" json:"storageTypes,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *StorageTypesProto) Reset()                    { *m = StorageTypesProto{} }
func (m *StorageTypesProto) String() string            { return proto.CompactTextString(m) }
func (*StorageTypesProto) ProtoMessage()               {}
func (*StorageTypesProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{13} }

func (m *StorageTypesProto) GetStorageTypes() []StorageTypeProto {
	if m != nil {
		return m.StorageTypes
	}
	return nil
}

// *
// Block replica storage policy.
type BlockStoragePolicyProto struct {
	PolicyId *uint32 `protobuf:"varint,1,req,name=policyId" json:"policyId,omitempty"`
	Name     *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	// a list of storage types for storing the block replicas when creating a
	// block.
	CreationPolicy *StorageTypesProto `protobuf:"bytes,3,req,name=creationPolicy" json:"creationPolicy,omitempty"`
	// A list of storage types for creation fallback storage.
	CreationFallbackPolicy    *StorageTypesProto `protobuf:"bytes,4,opt,name=creationFallbackPolicy" json:"creationFallbackPolicy,omitempty"`
	ReplicationFallbackPolicy *StorageTypesProto `protobuf:"bytes,5,opt,name=replicationFallbackPolicy" json:"replicationFallbackPolicy,omitempty"`
	XXX_unrecognized          []byte             `json:"-"`
}

func (m *BlockStoragePolicyProto) Reset()                    { *m = BlockStoragePolicyProto{} }
func (m *BlockStoragePolicyProto) String() string            { return proto.CompactTextString(m) }
func (*BlockStoragePolicyProto) ProtoMessage()               {}
func (*BlockStoragePolicyProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{14} }

func (m *BlockStoragePolicyProto) GetPolicyId() uint32 {
	if m != nil && m.PolicyId != nil {
		return *m.PolicyId
	}
	return 0
}

func (m *BlockStoragePolicyProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BlockStoragePolicyProto) GetCreationPolicy() *StorageTypesProto {
	if m != nil {
		return m.CreationPolicy
	}
	return nil
}

func (m *BlockStoragePolicyProto) GetCreationFallbackPolicy() *StorageTypesProto {
	if m != nil {
		return m.CreationFallbackPolicy
	}
	return nil
}

func (m *BlockStoragePolicyProto) GetReplicationFallbackPolicy() *StorageTypesProto {
	if m != nil {
		return m.ReplicationFallbackPolicy
	}
	return nil
}

// *
// A LocatedBlock gives information about a block and its location.
type LocatedBlockProto struct {
	B            *ExtendedBlockProto       `protobuf:"bytes,1,req,name=b" json:"b,omitempty"`
	Offset       *uint64                   `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	Locs         []*DatanodeInfoProto      `protobuf:"bytes,3,rep,name=locs" json:"locs,omitempty"`
	Corrupt      *bool                     `protobuf:"varint,4,req,name=corrupt" json:"corrupt,omitempty"`
	BlockToken   *hproto_common.TokenProto `protobuf:"bytes,5,req,name=blockToken" json:"blockToken,omitempty"`
	IsCached     []bool                    `protobuf:"varint,6,rep,packed,name=isCached" json:"isCached,omitempty"`
	StorageTypes []StorageTypeProto        `protobuf:"varint,7,rep,name=storageTypes,enum=hproto.hdfs.StorageTypeProto" json:"storageTypes,omitempty"`
	StorageIDs   []string                  `protobuf:"bytes,8,rep,name=storageIDs" json:"storageIDs,omitempty"`
	// striped block related fields
	BlockIndices     []byte                      `protobuf:"bytes,9,opt,name=blockIndices" json:"blockIndices,omitempty"`
	BlockTokens      []*hproto_common.TokenProto `protobuf:"bytes,10,rep,name=blockTokens" json:"blockTokens,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *LocatedBlockProto) Reset()                    { *m = LocatedBlockProto{} }
func (m *LocatedBlockProto) String() string            { return proto.CompactTextString(m) }
func (*LocatedBlockProto) ProtoMessage()               {}
func (*LocatedBlockProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{15} }

func (m *LocatedBlockProto) GetB() *ExtendedBlockProto {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *LocatedBlockProto) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *LocatedBlockProto) GetLocs() []*DatanodeInfoProto {
	if m != nil {
		return m.Locs
	}
	return nil
}

func (m *LocatedBlockProto) GetCorrupt() bool {
	if m != nil && m.Corrupt != nil {
		return *m.Corrupt
	}
	return false
}

func (m *LocatedBlockProto) GetBlockToken() *hproto_common.TokenProto {
	if m != nil {
		return m.BlockToken
	}
	return nil
}

func (m *LocatedBlockProto) GetIsCached() []bool {
	if m != nil {
		return m.IsCached
	}
	return nil
}

func (m *LocatedBlockProto) GetStorageTypes() []StorageTypeProto {
	if m != nil {
		return m.StorageTypes
	}
	return nil
}

func (m *LocatedBlockProto) GetStorageIDs() []string {
	if m != nil {
		return m.StorageIDs
	}
	return nil
}

func (m *LocatedBlockProto) GetBlockIndices() []byte {
	if m != nil {
		return m.BlockIndices
	}
	return nil
}

func (m *LocatedBlockProto) GetBlockTokens() []*hproto_common.TokenProto {
	if m != nil {
		return m.BlockTokens
	}
	return nil
}

type DataEncryptionKeyProto struct {
	KeyId               *uint32 `protobuf:"varint,1,req,name=keyId" json:"keyId,omitempty"`
	BlockPoolId         *string `protobuf:"bytes,2,req,name=blockPoolId" json:"blockPoolId,omitempty"`
	Nonce               []byte  `protobuf:"bytes,3,req,name=nonce" json:"nonce,omitempty"`
	EncryptionKey       []byte  `protobuf:"bytes,4,req,name=encryptionKey" json:"encryptionKey,omitempty"`
	ExpiryDate          *uint64 `protobuf:"varint,5,req,name=expiryDate" json:"expiryDate,omitempty"`
	EncryptionAlgorithm *string `protobuf:"bytes,6,opt,name=encryptionAlgorithm" json:"encryptionAlgorithm,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *DataEncryptionKeyProto) Reset()                    { *m = DataEncryptionKeyProto{} }
func (m *DataEncryptionKeyProto) String() string            { return proto.CompactTextString(m) }
func (*DataEncryptionKeyProto) ProtoMessage()               {}
func (*DataEncryptionKeyProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{16} }

func (m *DataEncryptionKeyProto) GetKeyId() uint32 {
	if m != nil && m.KeyId != nil {
		return *m.KeyId
	}
	return 0
}

func (m *DataEncryptionKeyProto) GetBlockPoolId() string {
	if m != nil && m.BlockPoolId != nil {
		return *m.BlockPoolId
	}
	return ""
}

func (m *DataEncryptionKeyProto) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *DataEncryptionKeyProto) GetEncryptionKey() []byte {
	if m != nil {
		return m.EncryptionKey
	}
	return nil
}

func (m *DataEncryptionKeyProto) GetExpiryDate() uint64 {
	if m != nil && m.ExpiryDate != nil {
		return *m.ExpiryDate
	}
	return 0
}

func (m *DataEncryptionKeyProto) GetEncryptionAlgorithm() string {
	if m != nil && m.EncryptionAlgorithm != nil {
		return *m.EncryptionAlgorithm
	}
	return ""
}

// *
// Encryption information for a file.
type FileEncryptionInfoProto struct {
	Suite                 *CipherSuiteProto           `protobuf:"varint,1,req,name=suite,enum=hproto.hdfs.CipherSuiteProto" json:"suite,omitempty"`
	CryptoProtocolVersion *CryptoProtocolVersionProto `protobuf:"varint,2,req,name=cryptoProtocolVersion,enum=hproto.hdfs.CryptoProtocolVersionProto" json:"cryptoProtocolVersion,omitempty"`
	Key                   []byte                      `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Iv                    []byte                      `protobuf:"bytes,4,req,name=iv" json:"iv,omitempty"`
	KeyName               *string                     `protobuf:"bytes,5,req,name=keyName" json:"keyName,omitempty"`
	EzKeyVersionName      *string                     `protobuf:"bytes,6,req,name=ezKeyVersionName" json:"ezKeyVersionName,omitempty"`
	XXX_unrecognized      []byte                      `json:"-"`
}

func (m *FileEncryptionInfoProto) Reset()                    { *m = FileEncryptionInfoProto{} }
func (m *FileEncryptionInfoProto) String() string            { return proto.CompactTextString(m) }
func (*FileEncryptionInfoProto) ProtoMessage()               {}
func (*FileEncryptionInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{17} }

func (m *FileEncryptionInfoProto) GetSuite() CipherSuiteProto {
	if m != nil && m.Suite != nil {
		return *m.Suite
	}
	return CipherSuiteProto_UNKNOWN
}

func (m *FileEncryptionInfoProto) GetCryptoProtocolVersion() CryptoProtocolVersionProto {
	if m != nil && m.CryptoProtocolVersion != nil {
		return *m.CryptoProtocolVersion
	}
	return CryptoProtocolVersionProto_UNKNOWN_PROTOCOL_VERSION
}

func (m *FileEncryptionInfoProto) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *FileEncryptionInfoProto) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

func (m *FileEncryptionInfoProto) GetKeyName() string {
	if m != nil && m.KeyName != nil {
		return *m.KeyName
	}
	return ""
}

func (m *FileEncryptionInfoProto) GetEzKeyVersionName() string {
	if m != nil && m.EzKeyVersionName != nil {
		return *m.EzKeyVersionName
	}
	return ""
}

// *
// Encryption information for an individual
// file within an encryption zone
type PerFileEncryptionInfoProto struct {
	Key              []byte  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Iv               []byte  `protobuf:"bytes,2,req,name=iv" json:"iv,omitempty"`
	EzKeyVersionName *string `protobuf:"bytes,3,req,name=ezKeyVersionName" json:"ezKeyVersionName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PerFileEncryptionInfoProto) Reset()                    { *m = PerFileEncryptionInfoProto{} }
func (m *PerFileEncryptionInfoProto) String() string            { return proto.CompactTextString(m) }
func (*PerFileEncryptionInfoProto) ProtoMessage()               {}
func (*PerFileEncryptionInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{18} }

func (m *PerFileEncryptionInfoProto) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PerFileEncryptionInfoProto) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

func (m *PerFileEncryptionInfoProto) GetEzKeyVersionName() string {
	if m != nil && m.EzKeyVersionName != nil {
		return *m.EzKeyVersionName
	}
	return ""
}

// *
// Encryption information for an encryption
// zone
type ZoneEncryptionInfoProto struct {
	Suite                 *CipherSuiteProto           `protobuf:"varint,1,req,name=suite,enum=hproto.hdfs.CipherSuiteProto" json:"suite,omitempty"`
	CryptoProtocolVersion *CryptoProtocolVersionProto `protobuf:"varint,2,req,name=cryptoProtocolVersion,enum=hproto.hdfs.CryptoProtocolVersionProto" json:"cryptoProtocolVersion,omitempty"`
	KeyName               *string                     `protobuf:"bytes,3,req,name=keyName" json:"keyName,omitempty"`
	XXX_unrecognized      []byte                      `json:"-"`
}

func (m *ZoneEncryptionInfoProto) Reset()                    { *m = ZoneEncryptionInfoProto{} }
func (m *ZoneEncryptionInfoProto) String() string            { return proto.CompactTextString(m) }
func (*ZoneEncryptionInfoProto) ProtoMessage()               {}
func (*ZoneEncryptionInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{19} }

func (m *ZoneEncryptionInfoProto) GetSuite() CipherSuiteProto {
	if m != nil && m.Suite != nil {
		return *m.Suite
	}
	return CipherSuiteProto_UNKNOWN
}

func (m *ZoneEncryptionInfoProto) GetCryptoProtocolVersion() CryptoProtocolVersionProto {
	if m != nil && m.CryptoProtocolVersion != nil {
		return *m.CryptoProtocolVersion
	}
	return CryptoProtocolVersionProto_UNKNOWN_PROTOCOL_VERSION
}

func (m *ZoneEncryptionInfoProto) GetKeyName() string {
	if m != nil && m.KeyName != nil {
		return *m.KeyName
	}
	return ""
}

// *
// Cipher option
type CipherOptionProto struct {
	Suite            *CipherSuiteProto `protobuf:"varint,1,req,name=suite,enum=hproto.hdfs.CipherSuiteProto" json:"suite,omitempty"`
	InKey            []byte            `protobuf:"bytes,2,opt,name=inKey" json:"inKey,omitempty"`
	InIv             []byte            `protobuf:"bytes,3,opt,name=inIv" json:"inIv,omitempty"`
	OutKey           []byte            `protobuf:"bytes,4,opt,name=outKey" json:"outKey,omitempty"`
	OutIv            []byte            `protobuf:"bytes,5,opt,name=outIv" json:"outIv,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *CipherOptionProto) Reset()                    { *m = CipherOptionProto{} }
func (m *CipherOptionProto) String() string            { return proto.CompactTextString(m) }
func (*CipherOptionProto) ProtoMessage()               {}
func (*CipherOptionProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{20} }

func (m *CipherOptionProto) GetSuite() CipherSuiteProto {
	if m != nil && m.Suite != nil {
		return *m.Suite
	}
	return CipherSuiteProto_UNKNOWN
}

func (m *CipherOptionProto) GetInKey() []byte {
	if m != nil {
		return m.InKey
	}
	return nil
}

func (m *CipherOptionProto) GetInIv() []byte {
	if m != nil {
		return m.InIv
	}
	return nil
}

func (m *CipherOptionProto) GetOutKey() []byte {
	if m != nil {
		return m.OutKey
	}
	return nil
}

func (m *CipherOptionProto) GetOutIv() []byte {
	if m != nil {
		return m.OutIv
	}
	return nil
}

// *
// A set of file blocks and their locations.
type LocatedBlocksProto struct {
	FileLength          *uint64                  `protobuf:"varint,1,req,name=fileLength" json:"fileLength,omitempty"`
	Blocks              []*LocatedBlockProto     `protobuf:"bytes,2,rep,name=blocks" json:"blocks,omitempty"`
	UnderConstruction   *bool                    `protobuf:"varint,3,req,name=underConstruction" json:"underConstruction,omitempty"`
	LastBlock           *LocatedBlockProto       `protobuf:"bytes,4,opt,name=lastBlock" json:"lastBlock,omitempty"`
	IsLastBlockComplete *bool                    `protobuf:"varint,5,req,name=isLastBlockComplete" json:"isLastBlockComplete,omitempty"`
	FileEncryptionInfo  *FileEncryptionInfoProto `protobuf:"bytes,6,opt,name=fileEncryptionInfo" json:"fileEncryptionInfo,omitempty"`
	// Optional field for erasure coding
	EcPolicy         *ErasureCodingPolicyProto `protobuf:"bytes,7,opt,name=ecPolicy" json:"ecPolicy,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *LocatedBlocksProto) Reset()                    { *m = LocatedBlocksProto{} }
func (m *LocatedBlocksProto) String() string            { return proto.CompactTextString(m) }
func (*LocatedBlocksProto) ProtoMessage()               {}
func (*LocatedBlocksProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{21} }

func (m *LocatedBlocksProto) GetFileLength() uint64 {
	if m != nil && m.FileLength != nil {
		return *m.FileLength
	}
	return 0
}

func (m *LocatedBlocksProto) GetBlocks() []*LocatedBlockProto {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *LocatedBlocksProto) GetUnderConstruction() bool {
	if m != nil && m.UnderConstruction != nil {
		return *m.UnderConstruction
	}
	return false
}

func (m *LocatedBlocksProto) GetLastBlock() *LocatedBlockProto {
	if m != nil {
		return m.LastBlock
	}
	return nil
}

func (m *LocatedBlocksProto) GetIsLastBlockComplete() bool {
	if m != nil && m.IsLastBlockComplete != nil {
		return *m.IsLastBlockComplete
	}
	return false
}

func (m *LocatedBlocksProto) GetFileEncryptionInfo() *FileEncryptionInfoProto {
	if m != nil {
		return m.FileEncryptionInfo
	}
	return nil
}

func (m *LocatedBlocksProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

// *
// ECSchema options entry
type ECSchemaOptionEntryProto struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ECSchemaOptionEntryProto) Reset()                    { *m = ECSchemaOptionEntryProto{} }
func (m *ECSchemaOptionEntryProto) String() string            { return proto.CompactTextString(m) }
func (*ECSchemaOptionEntryProto) ProtoMessage()               {}
func (*ECSchemaOptionEntryProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{22} }

func (m *ECSchemaOptionEntryProto) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ECSchemaOptionEntryProto) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// *
// ECSchema for erasurecoding
type ECSchemaProto struct {
	CodecName        *string                     `protobuf:"bytes,1,req,name=codecName" json:"codecName,omitempty"`
	DataUnits        *uint32                     `protobuf:"varint,2,req,name=dataUnits" json:"dataUnits,omitempty"`
	ParityUnits      *uint32                     `protobuf:"varint,3,req,name=parityUnits" json:"parityUnits,omitempty"`
	Options          []*ECSchemaOptionEntryProto `protobuf:"bytes,4,rep,name=options" json:"options,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *ECSchemaProto) Reset()                    { *m = ECSchemaProto{} }
func (m *ECSchemaProto) String() string            { return proto.CompactTextString(m) }
func (*ECSchemaProto) ProtoMessage()               {}
func (*ECSchemaProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{23} }

func (m *ECSchemaProto) GetCodecName() string {
	if m != nil && m.CodecName != nil {
		return *m.CodecName
	}
	return ""
}

func (m *ECSchemaProto) GetDataUnits() uint32 {
	if m != nil && m.DataUnits != nil {
		return *m.DataUnits
	}
	return 0
}

func (m *ECSchemaProto) GetParityUnits() uint32 {
	if m != nil && m.ParityUnits != nil {
		return *m.ParityUnits
	}
	return 0
}

func (m *ECSchemaProto) GetOptions() []*ECSchemaOptionEntryProto {
	if m != nil {
		return m.Options
	}
	return nil
}

type ErasureCodingPolicyProto struct {
	Name             *string        `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Schema           *ECSchemaProto `protobuf:"bytes,2,req,name=schema" json:"schema,omitempty"`
	CellSize         *uint32        `protobuf:"varint,3,req,name=cellSize" json:"cellSize,omitempty"`
	Id               *uint32        `protobuf:"varint,4,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ErasureCodingPolicyProto) Reset()                    { *m = ErasureCodingPolicyProto{} }
func (m *ErasureCodingPolicyProto) String() string            { return proto.CompactTextString(m) }
func (*ErasureCodingPolicyProto) ProtoMessage()               {}
func (*ErasureCodingPolicyProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{24} }

func (m *ErasureCodingPolicyProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ErasureCodingPolicyProto) GetSchema() *ECSchemaProto {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *ErasureCodingPolicyProto) GetCellSize() uint32 {
	if m != nil && m.CellSize != nil {
		return *m.CellSize
	}
	return 0
}

func (m *ErasureCodingPolicyProto) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// *
// Status of a file, directory or symlink
// Optionally includes a file's block locations if requested by client on the rpc call.
type HdfsFileStatusProto struct {
	FileType         *HdfsFileStatusProto_FileType `protobuf:"varint,1,req,name=fileType,enum=hproto.hdfs.HdfsFileStatusProto_FileType" json:"fileType,omitempty"`
	Path             []byte                        `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	Length           *uint64                       `protobuf:"varint,3,req,name=length" json:"length,omitempty"`
	Permission       *FsPermissionProto            `protobuf:"bytes,4,req,name=permission" json:"permission,omitempty"`
	Owner            *string                       `protobuf:"bytes,5,req,name=owner" json:"owner,omitempty"`
	Group            *string                       `protobuf:"bytes,6,req,name=group" json:"group,omitempty"`
	ModificationTime *uint64                       `protobuf:"varint,7,req,name=modification_time,json=modificationTime" json:"modification_time,omitempty"`
	AccessTime       *uint64                       `protobuf:"varint,8,req,name=access_time,json=accessTime" json:"access_time,omitempty"`
	// Optional fields for symlink
	Symlink []byte `protobuf:"bytes,9,opt,name=symlink" json:"symlink,omitempty"`
	// Optional fields for file
	BlockReplication *uint32             `protobuf:"varint,10,opt,name=block_replication,json=blockReplication,def=0" json:"block_replication,omitempty"`
	Blocksize        *uint64             `protobuf:"varint,11,opt,name=blocksize,def=0" json:"blocksize,omitempty"`
	Locations        *LocatedBlocksProto `protobuf:"bytes,12,opt,name=locations" json:"locations,omitempty"`
	// Optional field for fileId
	FileId      *uint64 `protobuf:"varint,13,opt,name=fileId,def=0" json:"fileId,omitempty"`
	ChildrenNum *int32  `protobuf:"varint,14,opt,name=childrenNum,def=-1" json:"childrenNum,omitempty"`
	// Optional field for file encryption
	FileEncryptionInfo *FileEncryptionInfoProto `protobuf:"bytes,15,opt,name=fileEncryptionInfo" json:"fileEncryptionInfo,omitempty"`
	StoragePolicy      *uint32                  `protobuf:"varint,16,opt,name=storagePolicy,def=0" json:"storagePolicy,omitempty"`
	// Optional field for erasure coding
	EcPolicy         *ErasureCodingPolicyProto `protobuf:"bytes,17,opt,name=ecPolicy" json:"ecPolicy,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *HdfsFileStatusProto) Reset()                    { *m = HdfsFileStatusProto{} }
func (m *HdfsFileStatusProto) String() string            { return proto.CompactTextString(m) }
func (*HdfsFileStatusProto) ProtoMessage()               {}
func (*HdfsFileStatusProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{25} }

const Default_HdfsFileStatusProto_BlockReplication uint32 = 0
const Default_HdfsFileStatusProto_Blocksize uint64 = 0
const Default_HdfsFileStatusProto_FileId uint64 = 0
const Default_HdfsFileStatusProto_ChildrenNum int32 = -1
const Default_HdfsFileStatusProto_StoragePolicy uint32 = 0

func (m *HdfsFileStatusProto) GetFileType() HdfsFileStatusProto_FileType {
	if m != nil && m.FileType != nil {
		return *m.FileType
	}
	return HdfsFileStatusProto_IS_DIR
}

func (m *HdfsFileStatusProto) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *HdfsFileStatusProto) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *HdfsFileStatusProto) GetPermission() *FsPermissionProto {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *HdfsFileStatusProto) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

func (m *HdfsFileStatusProto) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *HdfsFileStatusProto) GetModificationTime() uint64 {
	if m != nil && m.ModificationTime != nil {
		return *m.ModificationTime
	}
	return 0
}

func (m *HdfsFileStatusProto) GetAccessTime() uint64 {
	if m != nil && m.AccessTime != nil {
		return *m.AccessTime
	}
	return 0
}

func (m *HdfsFileStatusProto) GetSymlink() []byte {
	if m != nil {
		return m.Symlink
	}
	return nil
}

func (m *HdfsFileStatusProto) GetBlockReplication() uint32 {
	if m != nil && m.BlockReplication != nil {
		return *m.BlockReplication
	}
	return Default_HdfsFileStatusProto_BlockReplication
}

func (m *HdfsFileStatusProto) GetBlocksize() uint64 {
	if m != nil && m.Blocksize != nil {
		return *m.Blocksize
	}
	return Default_HdfsFileStatusProto_Blocksize
}

func (m *HdfsFileStatusProto) GetLocations() *LocatedBlocksProto {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *HdfsFileStatusProto) GetFileId() uint64 {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return Default_HdfsFileStatusProto_FileId
}

func (m *HdfsFileStatusProto) GetChildrenNum() int32 {
	if m != nil && m.ChildrenNum != nil {
		return *m.ChildrenNum
	}
	return Default_HdfsFileStatusProto_ChildrenNum
}

func (m *HdfsFileStatusProto) GetFileEncryptionInfo() *FileEncryptionInfoProto {
	if m != nil {
		return m.FileEncryptionInfo
	}
	return nil
}

func (m *HdfsFileStatusProto) GetStoragePolicy() uint32 {
	if m != nil && m.StoragePolicy != nil {
		return *m.StoragePolicy
	}
	return Default_HdfsFileStatusProto_StoragePolicy
}

func (m *HdfsFileStatusProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

// *
// HDFS Server Defaults
type FsServerDefaultsProto struct {
	BlockSize           *uint64            `protobuf:"varint,1,req,name=blockSize" json:"blockSize,omitempty"`
	BytesPerChecksum    *uint32            `protobuf:"varint,2,req,name=bytesPerChecksum" json:"bytesPerChecksum,omitempty"`
	WritePacketSize     *uint32            `protobuf:"varint,3,req,name=writePacketSize" json:"writePacketSize,omitempty"`
	Replication         *uint32            `protobuf:"varint,4,req,name=replication" json:"replication,omitempty"`
	FileBufferSize      *uint32            `protobuf:"varint,5,req,name=fileBufferSize" json:"fileBufferSize,omitempty"`
	EncryptDataTransfer *bool              `protobuf:"varint,6,opt,name=encryptDataTransfer,def=0" json:"encryptDataTransfer,omitempty"`
	TrashInterval       *uint64            `protobuf:"varint,7,opt,name=trashInterval,def=0" json:"trashInterval,omitempty"`
	ChecksumType        *ChecksumTypeProto `protobuf:"varint,8,opt,name=checksumType,enum=hproto.hdfs.ChecksumTypeProto,def=1" json:"checksumType,omitempty"`
	XXX_unrecognized    []byte             `json:"-"`
}

func (m *FsServerDefaultsProto) Reset()                    { *m = FsServerDefaultsProto{} }
func (m *FsServerDefaultsProto) String() string            { return proto.CompactTextString(m) }
func (*FsServerDefaultsProto) ProtoMessage()               {}
func (*FsServerDefaultsProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{26} }

const Default_FsServerDefaultsProto_EncryptDataTransfer bool = false
const Default_FsServerDefaultsProto_TrashInterval uint64 = 0
const Default_FsServerDefaultsProto_ChecksumType ChecksumTypeProto = ChecksumTypeProto_CHECKSUM_CRC32

func (m *FsServerDefaultsProto) GetBlockSize() uint64 {
	if m != nil && m.BlockSize != nil {
		return *m.BlockSize
	}
	return 0
}

func (m *FsServerDefaultsProto) GetBytesPerChecksum() uint32 {
	if m != nil && m.BytesPerChecksum != nil {
		return *m.BytesPerChecksum
	}
	return 0
}

func (m *FsServerDefaultsProto) GetWritePacketSize() uint32 {
	if m != nil && m.WritePacketSize != nil {
		return *m.WritePacketSize
	}
	return 0
}

func (m *FsServerDefaultsProto) GetReplication() uint32 {
	if m != nil && m.Replication != nil {
		return *m.Replication
	}
	return 0
}

func (m *FsServerDefaultsProto) GetFileBufferSize() uint32 {
	if m != nil && m.FileBufferSize != nil {
		return *m.FileBufferSize
	}
	return 0
}

func (m *FsServerDefaultsProto) GetEncryptDataTransfer() bool {
	if m != nil && m.EncryptDataTransfer != nil {
		return *m.EncryptDataTransfer
	}
	return Default_FsServerDefaultsProto_EncryptDataTransfer
}

func (m *FsServerDefaultsProto) GetTrashInterval() uint64 {
	if m != nil && m.TrashInterval != nil {
		return *m.TrashInterval
	}
	return Default_FsServerDefaultsProto_TrashInterval
}

func (m *FsServerDefaultsProto) GetChecksumType() ChecksumTypeProto {
	if m != nil && m.ChecksumType != nil {
		return *m.ChecksumType
	}
	return Default_FsServerDefaultsProto_ChecksumType
}

// *
// Directory listing
type DirectoryListingProto struct {
	PartialListing   []*HdfsFileStatusProto `protobuf:"bytes,1,rep,name=partialListing" json:"partialListing,omitempty"`
	RemainingEntries *uint32                `protobuf:"varint,2,req,name=remainingEntries" json:"remainingEntries,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *DirectoryListingProto) Reset()                    { *m = DirectoryListingProto{} }
func (m *DirectoryListingProto) String() string            { return proto.CompactTextString(m) }
func (*DirectoryListingProto) ProtoMessage()               {}
func (*DirectoryListingProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{27} }

func (m *DirectoryListingProto) GetPartialListing() []*HdfsFileStatusProto {
	if m != nil {
		return m.PartialListing
	}
	return nil
}

func (m *DirectoryListingProto) GetRemainingEntries() uint32 {
	if m != nil && m.RemainingEntries != nil {
		return *m.RemainingEntries
	}
	return 0
}

// *
// Status of a snapshottable directory: besides the normal information for
// a directory status, also include snapshot quota, number of snapshots, and
// the full path of the parent directory.
type SnapshottableDirectoryStatusProto struct {
	DirStatus *HdfsFileStatusProto `protobuf:"bytes,1,req,name=dirStatus" json:"dirStatus,omitempty"`
	// Fields specific for snapshottable directory
	SnapshotQuota    *uint32 `protobuf:"varint,2,req,name=snapshot_quota,json=snapshotQuota" json:"snapshot_quota,omitempty"`
	SnapshotNumber   *uint32 `protobuf:"varint,3,req,name=snapshot_number,json=snapshotNumber" json:"snapshot_number,omitempty"`
	ParentFullpath   []byte  `protobuf:"bytes,4,req,name=parent_fullpath,json=parentFullpath" json:"parent_fullpath,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SnapshottableDirectoryStatusProto) Reset()         { *m = SnapshottableDirectoryStatusProto{} }
func (m *SnapshottableDirectoryStatusProto) String() string { return proto.CompactTextString(m) }
func (*SnapshottableDirectoryStatusProto) ProtoMessage()    {}
func (*SnapshottableDirectoryStatusProto) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{28}
}

func (m *SnapshottableDirectoryStatusProto) GetDirStatus() *HdfsFileStatusProto {
	if m != nil {
		return m.DirStatus
	}
	return nil
}

func (m *SnapshottableDirectoryStatusProto) GetSnapshotQuota() uint32 {
	if m != nil && m.SnapshotQuota != nil {
		return *m.SnapshotQuota
	}
	return 0
}

func (m *SnapshottableDirectoryStatusProto) GetSnapshotNumber() uint32 {
	if m != nil && m.SnapshotNumber != nil {
		return *m.SnapshotNumber
	}
	return 0
}

func (m *SnapshottableDirectoryStatusProto) GetParentFullpath() []byte {
	if m != nil {
		return m.ParentFullpath
	}
	return nil
}

// *
// Snapshottable directory listing
type SnapshottableDirectoryListingProto struct {
	SnapshottableDirListing []*SnapshottableDirectoryStatusProto `protobuf:"bytes,1,rep,name=snapshottableDirListing" json:"snapshottableDirListing,omitempty"`
	XXX_unrecognized        []byte                               `json:"-"`
}

func (m *SnapshottableDirectoryListingProto) Reset()         { *m = SnapshottableDirectoryListingProto{} }
func (m *SnapshottableDirectoryListingProto) String() string { return proto.CompactTextString(m) }
func (*SnapshottableDirectoryListingProto) ProtoMessage()    {}
func (*SnapshottableDirectoryListingProto) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{29}
}

func (m *SnapshottableDirectoryListingProto) GetSnapshottableDirListing() []*SnapshottableDirectoryStatusProto {
	if m != nil {
		return m.SnapshottableDirListing
	}
	return nil
}

// *
// Snapshot diff report entry
type SnapshotDiffReportEntryProto struct {
	Fullpath          []byte  `protobuf:"bytes,1,req,name=fullpath" json:"fullpath,omitempty"`
	ModificationLabel *string `protobuf:"bytes,2,req,name=modificationLabel" json:"modificationLabel,omitempty"`
	TargetPath        []byte  `protobuf:"bytes,3,opt,name=targetPath" json:"targetPath,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *SnapshotDiffReportEntryProto) Reset()                    { *m = SnapshotDiffReportEntryProto{} }
func (m *SnapshotDiffReportEntryProto) String() string            { return proto.CompactTextString(m) }
func (*SnapshotDiffReportEntryProto) ProtoMessage()               {}
func (*SnapshotDiffReportEntryProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{30} }

func (m *SnapshotDiffReportEntryProto) GetFullpath() []byte {
	if m != nil {
		return m.Fullpath
	}
	return nil
}

func (m *SnapshotDiffReportEntryProto) GetModificationLabel() string {
	if m != nil && m.ModificationLabel != nil {
		return *m.ModificationLabel
	}
	return ""
}

func (m *SnapshotDiffReportEntryProto) GetTargetPath() []byte {
	if m != nil {
		return m.TargetPath
	}
	return nil
}

// *
// Snapshot diff report
type SnapshotDiffReportProto struct {
	// full path of the directory where snapshots were taken
	SnapshotRoot      *string                         `protobuf:"bytes,1,req,name=snapshotRoot" json:"snapshotRoot,omitempty"`
	FromSnapshot      *string                         `protobuf:"bytes,2,req,name=fromSnapshot" json:"fromSnapshot,omitempty"`
	ToSnapshot        *string                         `protobuf:"bytes,3,req,name=toSnapshot" json:"toSnapshot,omitempty"`
	DiffReportEntries []*SnapshotDiffReportEntryProto `protobuf:"bytes,4,rep,name=diffReportEntries" json:"diffReportEntries,omitempty"`
	XXX_unrecognized  []byte                          `json:"-"`
}

func (m *SnapshotDiffReportProto) Reset()                    { *m = SnapshotDiffReportProto{} }
func (m *SnapshotDiffReportProto) String() string            { return proto.CompactTextString(m) }
func (*SnapshotDiffReportProto) ProtoMessage()               {}
func (*SnapshotDiffReportProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{31} }

func (m *SnapshotDiffReportProto) GetSnapshotRoot() string {
	if m != nil && m.SnapshotRoot != nil {
		return *m.SnapshotRoot
	}
	return ""
}

func (m *SnapshotDiffReportProto) GetFromSnapshot() string {
	if m != nil && m.FromSnapshot != nil {
		return *m.FromSnapshot
	}
	return ""
}

func (m *SnapshotDiffReportProto) GetToSnapshot() string {
	if m != nil && m.ToSnapshot != nil {
		return *m.ToSnapshot
	}
	return ""
}

func (m *SnapshotDiffReportProto) GetDiffReportEntries() []*SnapshotDiffReportEntryProto {
	if m != nil {
		return m.DiffReportEntries
	}
	return nil
}

// *
// Block information
//
// Please be wary of adding additional fields here, since INodeFiles
// need to fit in PB's default max message size of 64MB.
// We restrict the max # of blocks per file
// (dfs.namenode.fs-limits.max-blocks-per-file), but it's better
// to avoid changing this.
type BlockProto struct {
	BlockId          *uint64 `protobuf:"varint,1,req,name=blockId" json:"blockId,omitempty"`
	GenStamp         *uint64 `protobuf:"varint,2,req,name=genStamp" json:"genStamp,omitempty"`
	NumBytes         *uint64 `protobuf:"varint,3,opt,name=numBytes,def=0" json:"numBytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BlockProto) Reset()                    { *m = BlockProto{} }
func (m *BlockProto) String() string            { return proto.CompactTextString(m) }
func (*BlockProto) ProtoMessage()               {}
func (*BlockProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{32} }

const Default_BlockProto_NumBytes uint64 = 0

func (m *BlockProto) GetBlockId() uint64 {
	if m != nil && m.BlockId != nil {
		return *m.BlockId
	}
	return 0
}

func (m *BlockProto) GetGenStamp() uint64 {
	if m != nil && m.GenStamp != nil {
		return *m.GenStamp
	}
	return 0
}

func (m *BlockProto) GetNumBytes() uint64 {
	if m != nil && m.NumBytes != nil {
		return *m.NumBytes
	}
	return Default_BlockProto_NumBytes
}

// *
// Information related to a snapshot
// TODO: add more information
type SnapshotInfoProto struct {
	SnapshotName     *string            `protobuf:"bytes,1,req,name=snapshotName" json:"snapshotName,omitempty"`
	SnapshotRoot     *string            `protobuf:"bytes,2,req,name=snapshotRoot" json:"snapshotRoot,omitempty"`
	Permission       *FsPermissionProto `protobuf:"bytes,3,req,name=permission" json:"permission,omitempty"`
	Owner            *string            `protobuf:"bytes,4,req,name=owner" json:"owner,omitempty"`
	Group            *string            `protobuf:"bytes,5,req,name=group" json:"group,omitempty"`
	CreateTime       *string            `protobuf:"bytes,6,req,name=createTime" json:"createTime,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SnapshotInfoProto) Reset()                    { *m = SnapshotInfoProto{} }
func (m *SnapshotInfoProto) String() string            { return proto.CompactTextString(m) }
func (*SnapshotInfoProto) ProtoMessage()               {}
func (*SnapshotInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{33} }

func (m *SnapshotInfoProto) GetSnapshotName() string {
	if m != nil && m.SnapshotName != nil {
		return *m.SnapshotName
	}
	return ""
}

func (m *SnapshotInfoProto) GetSnapshotRoot() string {
	if m != nil && m.SnapshotRoot != nil {
		return *m.SnapshotRoot
	}
	return ""
}

func (m *SnapshotInfoProto) GetPermission() *FsPermissionProto {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *SnapshotInfoProto) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

func (m *SnapshotInfoProto) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *SnapshotInfoProto) GetCreateTime() string {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return ""
}

// *
// Rolling upgrade status
type RollingUpgradeStatusProto struct {
	BlockPoolId      *string `protobuf:"bytes,1,req,name=blockPoolId" json:"blockPoolId,omitempty"`
	Finalized        *bool   `protobuf:"varint,2,opt,name=finalized,def=0" json:"finalized,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RollingUpgradeStatusProto) Reset()                    { *m = RollingUpgradeStatusProto{} }
func (m *RollingUpgradeStatusProto) String() string            { return proto.CompactTextString(m) }
func (*RollingUpgradeStatusProto) ProtoMessage()               {}
func (*RollingUpgradeStatusProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{34} }

const Default_RollingUpgradeStatusProto_Finalized bool = false

func (m *RollingUpgradeStatusProto) GetBlockPoolId() string {
	if m != nil && m.BlockPoolId != nil {
		return *m.BlockPoolId
	}
	return ""
}

func (m *RollingUpgradeStatusProto) GetFinalized() bool {
	if m != nil && m.Finalized != nil {
		return *m.Finalized
	}
	return Default_RollingUpgradeStatusProto_Finalized
}

// *
// A list of storage IDs.
type StorageUuidsProto struct {
	StorageUuids     []string `protobuf:"bytes,1,rep,name=storageUuids" json:"storageUuids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *StorageUuidsProto) Reset()                    { *m = StorageUuidsProto{} }
func (m *StorageUuidsProto) String() string            { return proto.CompactTextString(m) }
func (*StorageUuidsProto) ProtoMessage()               {}
func (*StorageUuidsProto) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{35} }

func (m *StorageUuidsProto) GetStorageUuids() []string {
	if m != nil {
		return m.StorageUuids
	}
	return nil
}

func init() {
	proto.RegisterType((*ExtendedBlockProto)(nil), "hproto.hdfs.ExtendedBlockProto")
	proto.RegisterType((*DatanodeIDProto)(nil), "hproto.hdfs.DatanodeIDProto")
	proto.RegisterType((*DatanodeLocalInfoProto)(nil), "hproto.hdfs.DatanodeLocalInfoProto")
	proto.RegisterType((*DatanodeInfosProto)(nil), "hproto.hdfs.DatanodeInfosProto")
	proto.RegisterType((*DatanodeInfoProto)(nil), "hproto.hdfs.DatanodeInfoProto")
	proto.RegisterType((*DatanodeStorageProto)(nil), "hproto.hdfs.DatanodeStorageProto")
	proto.RegisterType((*StorageReportProto)(nil), "hproto.hdfs.StorageReportProto")
	proto.RegisterType((*ContentSummaryProto)(nil), "hproto.hdfs.ContentSummaryProto")
	proto.RegisterType((*QuotaUsageProto)(nil), "hproto.hdfs.QuotaUsageProto")
	proto.RegisterType((*StorageTypeQuotaInfosProto)(nil), "hproto.hdfs.StorageTypeQuotaInfosProto")
	proto.RegisterType((*StorageTypeQuotaInfoProto)(nil), "hproto.hdfs.StorageTypeQuotaInfoProto")
	proto.RegisterType((*CorruptFileBlocksProto)(nil), "hproto.hdfs.CorruptFileBlocksProto")
	proto.RegisterType((*FsPermissionProto)(nil), "hproto.hdfs.FsPermissionProto")
	proto.RegisterType((*StorageTypesProto)(nil), "hproto.hdfs.StorageTypesProto")
	proto.RegisterType((*BlockStoragePolicyProto)(nil), "hproto.hdfs.BlockStoragePolicyProto")
	proto.RegisterType((*LocatedBlockProto)(nil), "hproto.hdfs.LocatedBlockProto")
	proto.RegisterType((*DataEncryptionKeyProto)(nil), "hproto.hdfs.DataEncryptionKeyProto")
	proto.RegisterType((*FileEncryptionInfoProto)(nil), "hproto.hdfs.FileEncryptionInfoProto")
	proto.RegisterType((*PerFileEncryptionInfoProto)(nil), "hproto.hdfs.PerFileEncryptionInfoProto")
	proto.RegisterType((*ZoneEncryptionInfoProto)(nil), "hproto.hdfs.ZoneEncryptionInfoProto")
	proto.RegisterType((*CipherOptionProto)(nil), "hproto.hdfs.CipherOptionProto")
	proto.RegisterType((*LocatedBlocksProto)(nil), "hproto.hdfs.LocatedBlocksProto")
	proto.RegisterType((*ECSchemaOptionEntryProto)(nil), "hproto.hdfs.ECSchemaOptionEntryProto")
	proto.RegisterType((*ECSchemaProto)(nil), "hproto.hdfs.ECSchemaProto")
	proto.RegisterType((*ErasureCodingPolicyProto)(nil), "hproto.hdfs.ErasureCodingPolicyProto")
	proto.RegisterType((*HdfsFileStatusProto)(nil), "hproto.hdfs.HdfsFileStatusProto")
	proto.RegisterType((*FsServerDefaultsProto)(nil), "hproto.hdfs.FsServerDefaultsProto")
	proto.RegisterType((*DirectoryListingProto)(nil), "hproto.hdfs.DirectoryListingProto")
	proto.RegisterType((*SnapshottableDirectoryStatusProto)(nil), "hproto.hdfs.SnapshottableDirectoryStatusProto")
	proto.RegisterType((*SnapshottableDirectoryListingProto)(nil), "hproto.hdfs.SnapshottableDirectoryListingProto")
	proto.RegisterType((*SnapshotDiffReportEntryProto)(nil), "hproto.hdfs.SnapshotDiffReportEntryProto")
	proto.RegisterType((*SnapshotDiffReportProto)(nil), "hproto.hdfs.SnapshotDiffReportProto")
	proto.RegisterType((*BlockProto)(nil), "hproto.hdfs.BlockProto")
	proto.RegisterType((*SnapshotInfoProto)(nil), "hproto.hdfs.SnapshotInfoProto")
	proto.RegisterType((*RollingUpgradeStatusProto)(nil), "hproto.hdfs.RollingUpgradeStatusProto")
	proto.RegisterType((*StorageUuidsProto)(nil), "hproto.hdfs.StorageUuidsProto")
	proto.RegisterEnum("hproto.hdfs.StorageTypeProto", StorageTypeProto_name, StorageTypeProto_value)
	proto.RegisterEnum("hproto.hdfs.CipherSuiteProto", CipherSuiteProto_name, CipherSuiteProto_value)
	proto.RegisterEnum("hproto.hdfs.CryptoProtocolVersionProto", CryptoProtocolVersionProto_name, CryptoProtocolVersionProto_value)
	proto.RegisterEnum("hproto.hdfs.ChecksumTypeProto", ChecksumTypeProto_name, ChecksumTypeProto_value)
	proto.RegisterEnum("hproto.hdfs.DatanodeInfoProto_AdminState", DatanodeInfoProto_AdminState_name, DatanodeInfoProto_AdminState_value)
	proto.RegisterEnum("hproto.hdfs.DatanodeStorageProto_StorageState", DatanodeStorageProto_StorageState_name, DatanodeStorageProto_StorageState_value)
	proto.RegisterEnum("hproto.hdfs.HdfsFileStatusProto_FileType", HdfsFileStatusProto_FileType_name, HdfsFileStatusProto_FileType_value)
}

func init() { proto.RegisterFile("gopkg.in/freddierice/go-hproto.v1/hdfs/hdfs.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 2965 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x59, 0xdd, 0x73, 0x1b, 0x49,
	0x11, 0x67, 0x25, 0xd9, 0x96, 0xdb, 0xb6, 0x22, 0x4f, 0xbe, 0x9c, 0x70, 0x1f, 0xb9, 0xe5, 0x72,
	0xc9, 0x05, 0xce, 0xb9, 0x38, 0xd4, 0x5d, 0x11, 0xe0, 0x40, 0x96, 0xe4, 0x8b, 0x2a, 0xb6, 0xe4,
	0x1b, 0xd9, 0xb9, 0xba, 0x2b, 0x28, 0xd5, 0x7a, 0x35, 0x92, 0x97, 0xac, 0x76, 0xc5, 0xee, 0xca,
	0x89, 0xef, 0x89, 0x47, 0xaa, 0x28, 0xe0, 0x89, 0x37, 0x8a, 0xba, 0x2a, 0x78, 0xe6, 0xdf, 0xb8,
	0xff, 0x81, 0xa2, 0x78, 0x84, 0x7f, 0x80, 0x77, 0xe8, 0xe9, 0x99, 0xfd, 0xd2, 0x47, 0x1c, 0xee,
	0x9e, 0x78, 0x51, 0xa9, 0x7f, 0xd3, 0xd3, 0x33, 0xdd, 0x33, 0xfd, 0x31, 0xbd, 0xf0, 0x60, 0xe8,
	0x8f, 0x9f, 0x0d, 0xb7, 0x1d, 0xef, 0xfe, 0x20, 0x10, 0xfd, 0xbe, 0x23, 0x02, 0xc7, 0x16, 0xf7,
	0x87, 0xfe, 0x7b, 0xa7, 0xe3, 0xc0, 0x8f, 0xfc, 0xed, 0xb3, 0x07, 0xf7, 0x4f, 0xfb, 0x83, 0x90,
	0x7e, 0xb6, 0x09, 0x62, 0x6b, 0x7a, 0x48, 0x42, 0x37, 0x3f, 0xbc, 0x78, 0xbe, 0xed, 0x8f, 0x46,
	0xbe, 0x77, 0xbf, 0x2b, 0xec, 0x49, 0xe0, 0x44, 0xe7, 0x4a, 0x8a, 0xf9, 0x7b, 0x03, 0x58, 0xf3,
	0x45, 0x24, 0xbc, 0xbe, 0xe8, 0xef, 0xba, 0xbe, 0xfd, 0xec, 0x90, 0x84, 0x5f, 0x83, 0xe5, 0xb1,
	0xef, 0xbb, 0xad, 0xfe, 0x96, 0x71, 0xab, 0x70, 0x77, 0x95, 0x6b, 0x8a, 0x6d, 0xc1, 0xca, 0x89,
	0xe4, 0xc2, 0x81, 0x02, 0x0e, 0x94, 0x78, 0x4c, 0xb2, 0xbb, 0x70, 0x69, 0x28, 0x3c, 0x11, 0x58,
	0x91, 0xe3, 0x7b, 0xdd, 0xc8, 0x1a, 0x8d, 0xb7, 0x8a, 0xc4, 0x31, 0x0d, 0xb3, 0xd7, 0xa1, 0xec,
	0x4d, 0x46, 0xbb, 0xe7, 0x91, 0x08, 0xb7, 0x4a, 0xb7, 0x8c, 0xbb, 0xa5, 0x47, 0xc6, 0xfb, 0x3c,
	0x81, 0xcc, 0x7f, 0x1a, 0x70, 0xa9, 0x61, 0x45, 0x96, 0xe7, 0xf7, 0x45, 0xab, 0x91, 0x6c, 0xc7,
	0x19, 0xd7, 0xfa, 0xfd, 0x20, 0xde, 0x8e, 0xa2, 0xd8, 0x4d, 0x28, 0x9f, 0xfa, 0x61, 0xd4, 0xb6,
	0x46, 0x82, 0xf6, 0xb3, 0xca, 0x13, 0x9a, 0x99, 0xb0, 0xde, 0xd7, 0x62, 0x8e, 0x27, 0x4e, 0x9f,
	0x76, 0xb3, 0xca, 0x73, 0x98, 0x9c, 0xff, 0x62, 0x20, 0x82, 0x43, 0x3f, 0x88, 0x70, 0x2b, 0x85,
	0xbb, 0x1b, 0x3c, 0xa1, 0xe5, 0x98, 0xe3, 0x0d, 0x7c, 0x1a, 0x5b, 0x52, 0x63, 0x31, 0x2d, 0xcd,
	0xe0, 0x8c, 0x6d, 0x1a, 0x5a, 0xa6, 0xa1, 0x98, 0x64, 0xef, 0x42, 0x45, 0x72, 0x91, 0x95, 0x05,
	0x31, 0xac, 0xa0, 0x8a, 0x1b, 0x52, 0xc5, 0xa9, 0x01, 0xf3, 0x57, 0x06, 0x5c, 0x8b, 0x15, 0xdd,
	0xf7, 0x6d, 0xcb, 0x6d, 0x49, 0xf1, 0xa4, 0x2f, 0x1a, 0x33, 0xf4, 0x07, 0xd1, 0x73, 0x2b, 0x10,
	0x4f, 0x45, 0x10, 0xa2, 0xe9, 0xb4, 0xe2, 0xd3, 0x30, 0x7b, 0x1b, 0x36, 0x6c, 0xdf, 0x1b, 0x38,
	0xc3, 0x98, 0x4f, 0x99, 0x21, 0x0f, 0x4a, 0xfb, 0x4d, 0xc6, 0x91, 0x83, 0x56, 0x52, 0x67, 0xa2,
	0x29, 0x93, 0x03, 0x4b, 0x4c, 0x8d, 0x8b, 0x87, 0x6a, 0xf5, 0x1f, 0xc1, 0x6a, 0x6c, 0xa5, 0x10,
	0xd7, 0x2d, 0xde, 0x5d, 0xdb, 0x79, 0x63, 0x3b, 0x73, 0xdb, 0xb6, 0xb3, 0x73, 0x68, 0x0a, 0x4f,
	0x27, 0x98, 0x7f, 0x5a, 0x82, 0xcd, 0x19, 0x06, 0xf6, 0x3d, 0x28, 0x38, 0xea, 0x32, 0xad, 0xed,
	0xbc, 0x36, 0x5f, 0x98, 0x3a, 0x6b, 0x8e, 0x7c, 0xf2, 0x8a, 0xd8, 0xd6, 0xd8, 0xb2, 0xf1, 0x9e,
	0xa2, 0x42, 0xf1, 0x15, 0x89, 0x21, 0xf6, 0x6d, 0x58, 0xc1, 0x99, 0xc7, 0xa1, 0x90, 0xa7, 0xaa,
	0x47, 0x63, 0x84, 0xbd, 0x09, 0xab, 0x81, 0x18, 0x59, 0x8e, 0xe7, 0x78, 0xc3, 0xf4, 0x7e, 0xa5,
	0x18, 0xbb, 0x03, 0x1b, 0x74, 0x69, 0x0f, 0xf1, 0x4a, 0x93, 0x8c, 0xa5, 0x98, 0x29, 0x8f, 0xb3,
	0xb7, 0x00, 0x5c, 0x2b, 0x8c, 0x8e, 0xc7, 0xa8, 0x9c, 0xc0, 0x83, 0xd6, 0x5c, 0x19, 0x90, 0xdd,
	0x86, 0xf5, 0x17, 0xb6, 0x70, 0xce, 0x44, 0x50, 0xf7, 0x27, 0x5e, 0xe6, 0xb0, 0x73, 0xb0, 0xbc,
	0x4b, 0x28, 0x99, 0x7c, 0x60, 0xab, 0x8c, 0x2c, 0x78, 0x4f, 0x63, 0x9a, 0x7d, 0x02, 0x60, 0xf5,
	0x47, 0x8e, 0x74, 0x0e, 0x5c, 0x05, 0x70, 0xb4, 0xb2, 0xf3, 0xee, 0xcb, 0xcd, 0xbd, 0x5d, 0x4b,
	0x26, 0x3c, 0x5a, 0x6e, 0x77, 0xf8, 0x41, 0x6d, 0x9f, 0x67, 0x84, 0x48, 0x0d, 0x6d, 0xcb, 0x3e,
	0x15, 0xf5, 0xd8, 0x86, 0x6b, 0x89, 0x86, 0x39, 0x5c, 0xda, 0x8a, 0x00, 0x32, 0xc3, 0x7a, 0x62,
	0xab, 0x04, 0x63, 0x0f, 0xe1, 0x72, 0xaa, 0xed, 0x81, 0xef, 0xe1, 0xe2, 0x9e, 0x63, 0x6f, 0x6d,
	0xc4, 0xac, 0xf3, 0x46, 0xe5, 0x9d, 0x9c, 0x8c, 0x87, 0x81, 0xd5, 0x17, 0x0d, 0x5f, 0x1a, 0x7d,
	0xab, 0x42, 0x2a, 0xe7, 0x41, 0xf3, 0x39, 0x40, 0xaa, 0x06, 0x03, 0xd0, 0x8a, 0x54, 0xbf, 0x85,
	0xc7, 0x7b, 0xbd, 0xd1, 0xac, 0x77, 0x0e, 0x0e, 0x5a, 0xdd, 0x6e, 0xab, 0xd3, 0xee, 0xb5, 0xda,
	0x87, 0xbc, 0xf3, 0x31, 0x6f, 0x76, 0xbb, 0x55, 0x83, 0x31, 0xa8, 0x64, 0x07, 0x9b, 0x8d, 0x6a,
	0x01, 0xdd, 0xf1, 0x4a, 0xb3, 0x7d, 0xd4, 0xe4, 0xad, 0xf6, 0xc7, 0xbd, 0x83, 0x5a, 0x0b, 0xff,
	0xb6, 0x6b, 0xed, 0x7a, 0xb3, 0x5a, 0x94, 0xdc, 0xad, 0x76, 0x0e, 0x2b, 0x99, 0xff, 0x31, 0xe0,
	0x4a, 0x6c, 0xd2, 0x6e, 0xe4, 0x07, 0xd6, 0x50, 0xa8, 0x3b, 0x7a, 0x0b, 0xd6, 0x42, 0x45, 0x53,
	0xc0, 0x50, 0x1e, 0x97, 0x85, 0xd8, 0x3e, 0x2c, 0x85, 0x74, 0x4c, 0x05, 0x3a, 0xa6, 0xed, 0xb9,
	0xc7, 0x94, 0x95, 0xb9, 0xad, 0x89, 0xfc, 0x59, 0x29, 0x21, 0xac, 0x99, 0xac, 0x77, 0x74, 0x3e,
	0x16, 0x74, 0x95, 0x2b, 0x3b, 0xaf, 0xe7, 0x64, 0x76, 0xd3, 0x71, 0x92, 0xf7, 0xa8, 0xd4, 0x68,
	0x75, 0x9f, 0xf0, 0xec, 0x3c, 0xf3, 0x7d, 0x58, 0xcf, 0xae, 0x92, 0x33, 0xe5, 0x15, 0xa8, 0xf2,
	0x66, 0xad, 0xd1, 0xeb, 0xb4, 0xf7, 0x3f, 0xeb, 0x75, 0x1f, 0xd7, 0x38, 0xda, 0xcb, 0x30, 0xff,
	0x58, 0x00, 0xa6, 0xa7, 0x70, 0x31, 0xc6, 0x58, 0xa4, 0xf4, 0x7f, 0x7b, 0x8e, 0xfe, 0xbb, 0x85,
	0x2d, 0x23, 0x6f, 0x83, 0xd7, 0x61, 0x79, 0x60, 0x39, 0xae, 0xe8, 0x93, 0x11, 0xca, 0x8f, 0x96,
	0x06, 0x96, 0x1b, 0x0a, 0xae, 0xc1, 0x9c, 0xeb, 0x16, 0x5f, 0xea, 0xba, 0xa5, 0x97, 0xbb, 0xee,
	0xd2, 0xab, 0xb8, 0xee, 0xf2, 0x02, 0xd7, 0xfd, 0x21, 0xac, 0xe8, 0x3d, 0x93, 0x4b, 0xae, 0xed,
	0xbc, 0x75, 0xe1, 0x51, 0xf1, 0x78, 0x86, 0xf9, 0x65, 0x01, 0x2e, 0xd7, 0x7d, 0x0f, 0x93, 0x62,
	0xd4, 0x9d, 0x8c, 0x46, 0x56, 0x70, 0x9e, 0x64, 0x21, 0x57, 0x78, 0xc3, 0xe8, 0x94, 0x4c, 0x83,
	0x51, 0x54, 0x51, 0xec, 0x35, 0x58, 0x1d, 0xa0, 0xee, 0x2a, 0x02, 0xa8, 0xb4, 0x98, 0x02, 0xec,
	0x1d, 0xa8, 0xf4, 0x9d, 0x40, 0xd8, 0x28, 0xfc, 0x5c, 0xb1, 0xa8, 0x18, 0x3c, 0x85, 0xe2, 0x51,
	0x2d, 0xfd, 0x72, 0xe2, 0x47, 0x16, 0x25, 0xa2, 0x12, 0x57, 0x84, 0xf4, 0xa5, 0x10, 0x4d, 0x87,
	0xb2, 0xbc, 0x70, 0x32, 0xa2, 0x60, 0x25, 0x47, 0xf3, 0x20, 0x7b, 0x03, 0x80, 0x80, 0x4f, 0x48,
	0xc0, 0x32, 0xb1, 0x64, 0x10, 0xd6, 0x81, 0x4a, 0x84, 0x57, 0x85, 0x08, 0x0a, 0xf4, 0xda, 0x2a,
	0x77, 0x16, 0x5d, 0xb6, 0x94, 0x53, 0xd9, 0x66, 0x6a, 0xba, 0xf9, 0x6f, 0x4c, 0xd2, 0x44, 0x1e,
	0x87, 0x89, 0xfb, 0x7c, 0x1f, 0xae, 0x4a, 0xad, 0x6b, 0x5e, 0xbf, 0x91, 0xd7, 0x57, 0x59, 0x6b,
	0xfe, 0x60, 0xaa, 0x76, 0xe1, 0xa5, 0x6a, 0x17, 0x2f, 0x56, 0xbb, 0xf4, 0x0a, 0x6a, 0x2f, 0x7d,
	0x33, 0xb5, 0x7f, 0x01, 0x37, 0x17, 0x73, 0x63, 0x74, 0xd8, 0xc8, 0xf1, 0xeb, 0xdc, 0xf9, 0xce,
	0x85, 0xab, 0xa9, 0xc5, 0xf2, 0x93, 0x65, 0x79, 0x70, 0x63, 0x21, 0x33, 0x7b, 0x00, 0x25, 0xc9,
	0x4e, 0xb6, 0xbd, 0x28, 0x68, 0x70, 0x62, 0x5d, 0x60, 0x69, 0x4c, 0x4d, 0x76, 0xde, 0xc8, 0x09,
	0x6d, 0xee, 0xc1, 0xb5, 0xba, 0x1f, 0x04, 0x58, 0x2c, 0xec, 0xe1, 0xd9, 0x51, 0x79, 0xa8, 0x55,
	0x45, 0x59, 0xf2, 0x38, 0x55, 0x79, 0xb0, 0xca, 0x15, 0x21, 0x1d, 0xc4, 0xf6, 0xfd, 0x67, 0x4e,
	0x5c, 0x8c, 0x69, 0xca, 0xbc, 0x03, 0x9b, 0x7b, 0xe1, 0xa1, 0x08, 0x46, 0x4e, 0x28, 0xcb, 0x11,
	0x25, 0x82, 0x41, 0x69, 0x8c, 0x10, 0x69, 0xb0, 0xc1, 0xe9, 0xbf, 0xf9, 0x14, 0x36, 0x33, 0x9b,
	0xd7, 0x6b, 0xd5, 0x60, 0x3d, 0x13, 0xee, 0xd4, 0x92, 0x17, 0xaa, 0x9c, 0x9b, 0x62, 0x7e, 0x55,
	0x80, 0xeb, 0xb4, 0xfd, 0xd8, 0xe1, 0x7d, 0xd7, 0xb1, 0xb5, 0x57, 0xa3, 0x01, 0xc6, 0x44, 0xea,
	0x62, 0x17, 0xeb, 0xbc, 0x98, 0x96, 0x7b, 0xf4, 0xd2, 0xda, 0x92, 0xfe, 0xb3, 0x3d, 0xa8, 0xd8,
	0x81, 0xa0, 0xdc, 0xad, 0xc4, 0x90, 0xd9, 0xa6, 0x4b, 0xa4, 0x19, 0x35, 0xf8, 0xd4, 0x2c, 0xf6,
	0x14, 0xae, 0xc5, 0xc8, 0x9e, 0xe5, 0xba, 0x27, 0x96, 0x0c, 0x5f, 0x24, 0xaf, 0x44, 0x97, 0xf4,
	0x22, 0x79, 0x0b, 0x66, 0xb3, 0x9f, 0xc1, 0x8d, 0x40, 0x8c, 0xf1, 0xef, 0x3c, 0xd1, 0x4b, 0xaf,
	0x24, 0x7a, 0xb1, 0x00, 0xf3, 0xab, 0x22, 0x6c, 0xca, 0x62, 0x35, 0xca, 0x3d, 0x17, 0xde, 0x03,
	0xe3, 0x44, 0x17, 0x77, 0x6f, 0xe6, 0x64, 0xcf, 0x3e, 0x2d, 0xb8, 0x71, 0x22, 0xef, 0x89, 0x3f,
	0x18, 0x84, 0x22, 0x8e, 0x96, 0x9a, 0x62, 0x3b, 0x50, 0x42, 0xbe, 0x10, 0x0d, 0xfa, 0x2a, 0x35,
	0x27, 0xf1, 0xca, 0x52, 0xdc, 0x56, 0x77, 0x94, 0x02, 0x40, 0x99, 0xc7, 0x24, 0xfb, 0x01, 0x00,
	0x25, 0x85, 0x23, 0xff, 0x99, 0xf0, 0x28, 0x6e, 0xae, 0xed, 0xdc, 0x88, 0x65, 0xaa, 0xd7, 0xd0,
	0x36, 0x8d, 0x29, 0x71, 0x19, 0x66, 0x0c, 0x2c, 0x65, 0x27, 0xac, 0xcb, 0x2a, 0x48, 0xa6, 0x98,
	0xe2, 0xdd, 0xf2, 0x6e, 0xa1, 0x6a, 0xf0, 0x04, 0x9b, 0xb9, 0x92, 0x2b, 0xff, 0xf3, 0x95, 0xa4,
	0xd8, 0xa5, 0xe8, 0x56, 0x23, 0xc4, 0xa2, 0x50, 0xba, 0x51, 0x06, 0x91, 0xcf, 0x17, 0xf5, 0xb4,
	0xf2, 0xfa, 0xf8, 0x94, 0x0b, 0xb7, 0x56, 0xf1, 0xe4, 0xd6, 0x79, 0x0e, 0xc3, 0x2c, 0xb7, 0x96,
	0x6e, 0x3a, 0xc4, 0xda, 0xb1, 0xf8, 0x72, 0x15, 0xb3, 0xdc, 0xe6, 0x3f, 0xf4, 0xf3, 0xa3, 0xe9,
	0xd9, 0xc1, 0xf9, 0x58, 0x1e, 0xf5, 0x13, 0x71, 0x9e, 0x78, 0xf7, 0x33, 0x91, 0xfa, 0x83, 0x22,
	0x64, 0x79, 0x94, 0x24, 0x59, 0xfd, 0xfe, 0x5b, 0xe5, 0x59, 0x48, 0xce, 0xf3, 0x7c, 0xcf, 0x56,
	0xaf, 0x8c, 0x75, 0xae, 0x08, 0x19, 0xcb, 0x45, 0x76, 0x0d, 0x3a, 0xa7, 0x75, 0x9e, 0x07, 0xa5,
	0x3d, 0xc4, 0x8b, 0xb1, 0x13, 0x9c, 0x37, 0x64, 0x7d, 0xa5, 0xb2, 0x5c, 0x06, 0x61, 0xef, 0xc3,
	0xe5, 0x74, 0x42, 0xcd, 0x1d, 0xfa, 0xf8, 0x88, 0x3d, 0x1d, 0x51, 0x01, 0xb0, 0xca, 0xe7, 0x0d,
	0x99, 0x7f, 0x40, 0xa7, 0x97, 0x71, 0x2b, 0x55, 0x30, 0x0d, 0x9f, 0x0f, 0xb1, 0x90, 0x9b, 0x38,
	0xd1, 0xfc, 0xf8, 0x59, 0x77, 0xc6, 0xa7, 0x22, 0xe8, 0xca, 0x71, 0x65, 0x37, 0xc5, 0xcb, 0x7e,
	0x0e, 0x57, 0x49, 0x92, 0x92, 0x61, 0xfb, 0x6e, 0xf6, 0xcd, 0x55, 0x99, 0xca, 0x2a, 0xf5, 0x79,
	0x9c, 0x4a, 0xdc, 0x7c, 0x29, 0xac, 0x0a, 0x45, 0x34, 0xb4, 0xb6, 0x9d, 0xfc, 0xcb, 0x2a, 0xf8,
	0x68, 0x3a, 0xd3, 0xe6, 0xc2, 0x7f, 0xf2, 0xae, 0x23, 0x4c, 0xaf, 0xdd, 0x25, 0xb2, 0x7e, 0x4c,
	0xb2, 0x7b, 0x50, 0x15, 0x5f, 0xa0, 0x19, 0xb5, 0x2c, 0x62, 0x59, 0x26, 0x96, 0x19, 0x5c, 0x26,
	0x31, 0x8c, 0xc5, 0x8b, 0x2c, 0xa3, 0x77, 0x61, 0x4c, 0xef, 0xa2, 0x90, 0xec, 0x62, 0xde, 0x5a,
	0xc5, 0x05, 0x6b, 0x7d, 0x65, 0xc0, 0xf5, 0xcf, 0x7d, 0xef, 0xff, 0xe6, 0x0c, 0x32, 0x16, 0x2e,
	0xe6, 0x2c, 0x6c, 0x7e, 0x69, 0xc0, 0xa6, 0xda, 0x54, 0x87, 0xf4, 0xf8, 0x06, 0x3a, 0xa0, 0x9b,
	0x38, 0xe4, 0x08, 0x05, 0xf2, 0x69, 0x45, 0xc8, 0x5c, 0xe3, 0x78, 0xad, 0x33, 0x2a, 0x9a, 0xd7,
	0x39, 0xfd, 0xa7, 0x40, 0x39, 0x89, 0x94, 0xcf, 0x48, 0x54, 0x53, 0x52, 0x02, 0xfe, 0x43, 0xe6,
	0x25, 0x25, 0x81, 0x08, 0xf3, 0xcf, 0x45, 0x60, 0xd9, 0xd8, 0xac, 0xf3, 0x27, 0x7a, 0x96, 0x4c,
	0xcf, 0xfb, 0xd9, 0xd2, 0x35, 0x83, 0xb0, 0x0f, 0x60, 0x99, 0x9c, 0x38, 0xc4, 0xfd, 0xcc, 0xc6,
	0xdd, 0x99, 0x60, 0xcf, 0x35, 0x37, 0x3e, 0xe9, 0x37, 0x27, 0x18, 0xdb, 0x03, 0x59, 0x8e, 0x45,
	0xc1, 0xc4, 0xa6, 0xd7, 0x6d, 0x91, 0x62, 0xf0, 0xec, 0x80, 0x6c, 0x2a, 0xc8, 0xb7, 0x22, 0xc9,
	0x99, 0x9b, 0xe1, 0x66, 0x17, 0x4a, 0x27, 0x48, 0xef, 0x77, 0xc2, 0xfd, 0x98, 0xac, 0xfb, 0xa3,
	0xb1, 0x2b, 0x74, 0x98, 0x28, 0xf3, 0x79, 0x43, 0xec, 0x08, 0xd8, 0x60, 0xe6, 0x8a, 0x53, 0xb8,
	0x58, 0xdb, 0x79, 0x3b, 0xb7, 0xf0, 0x02, 0x4f, 0xe0, 0x73, 0xe6, 0x63, 0xe0, 0x2f, 0x0b, 0x5b,
	0xe7, 0x52, 0x55, 0x42, 0xdf, 0xce, 0xe7, 0xbb, 0xc0, 0x0a, 0x27, 0x01, 0x56, 0xa8, 0x7d, 0x7c,
	0xae, 0x64, 0xaa, 0x0c, 0x9e, 0x4c, 0x33, 0x77, 0x61, 0xab, 0x59, 0xef, 0x62, 0x1a, 0x19, 0x59,
	0xea, 0x26, 0x35, 0xbd, 0x28, 0x7e, 0x61, 0x64, 0x9c, 0x6f, 0x55, 0x39, 0x1f, 0x9e, 0xf4, 0x99,
	0xe5, 0x4e, 0xe2, 0x12, 0x44, 0x11, 0xe6, 0x5f, 0x0d, 0xd8, 0x88, 0x85, 0xa8, 0x99, 0xf8, 0x06,
	0xb1, 0x31, 0x3b, 0xda, 0x74, 0x75, 0xd5, 0xfc, 0x14, 0x90, 0xa3, 0xb2, 0x41, 0x73, 0xec, 0x39,
	0x51, 0x48, 0x92, 0x36, 0x78, 0x0a, 0xc8, 0xc0, 0x3e, 0xb6, 0x64, 0x4f, 0x50, 0x8d, 0x17, 0x69,
	0x3c, 0x0b, 0xb1, 0x9f, 0xc0, 0x8a, 0x4f, 0x7b, 0x95, 0x1d, 0xbb, 0xe2, 0xac, 0xd6, 0x0b, 0xf4,
	0xe1, 0xf1, 0x2c, 0xf3, 0x77, 0x06, 0x6a, 0xbd, 0xc0, 0x36, 0x49, 0x95, 0x65, 0x64, 0xaa, 0xac,
	0x1d, 0x58, 0x0e, 0x49, 0x26, 0x6d, 0x77, 0x6d, 0xe7, 0xe6, 0xdc, 0x05, 0xf5, 0x85, 0x54, 0x9c,
	0x54, 0xca, 0x0a, 0xd7, 0xed, 0x3a, 0x5f, 0x08, 0xad, 0x44, 0x42, 0x53, 0x10, 0xeb, 0xeb, 0x1e,
	0x1f, 0xfe, 0x33, 0xff, 0xb2, 0x0c, 0x97, 0x1f, 0xa3, 0x28, 0x79, 0xf8, 0xf2, 0xd9, 0x3c, 0xd1,
	0xce, 0xd2, 0x84, 0xb2, 0x3c, 0xf6, 0xa3, 0xb4, 0xb6, 0xce, 0xf7, 0x62, 0xe6, 0xcc, 0xa1, 0x0b,
	0x24, 0x27, 0xf0, 0x64, 0x2a, 0x15, 0xb7, 0x16, 0x7a, 0x9b, 0x8a, 0x9a, 0xf4, 0x3f, 0xf3, 0x7c,
	0x2c, 0xe6, 0x9e, 0x8f, 0x1f, 0x01, 0x8c, 0x93, 0xda, 0x98, 0xb6, 0x38, 0xed, 0x1a, 0x33, 0xc5,
	0x33, 0xcf, 0xcc, 0xa0, 0x60, 0xf0, 0xdc, 0x13, 0x81, 0xce, 0x09, 0x8a, 0x90, 0xe8, 0x30, 0xf0,
	0x27, 0x63, 0x9d, 0x06, 0x14, 0xc1, 0xbe, 0x0b, 0x9b, 0x23, 0xb4, 0xff, 0x40, 0x17, 0x77, 0x3d,
	0xea, 0x09, 0xae, 0xd0, 0x76, 0xaa, 0xd9, 0x81, 0x23, 0xc4, 0xf1, 0x39, 0xbe, 0x66, 0xd9, 0x58,
	0x67, 0x84, 0x8a, 0xad, 0xac, 0x22, 0x87, 0x82, 0x88, 0x01, 0xa3, 0x65, 0x78, 0x3e, 0x72, 0x1d,
	0xef, 0x99, 0x2e, 0x4f, 0x62, 0x92, 0x6d, 0xc3, 0x26, 0x45, 0x89, 0x5e, 0xa6, 0x92, 0xa4, 0xde,
	0x16, 0x35, 0xc7, 0xaa, 0x34, 0xc6, 0xd3, 0x21, 0xf9, 0xf2, 0x57, 0x51, 0x45, 0x9e, 0x5d, 0xd2,
	0xad, 0x4a, 0x31, 0xf6, 0x63, 0x0c, 0x1f, 0xba, 0x63, 0x16, 0x52, 0xa7, 0x6a, 0xba, 0xd2, 0x9c,
	0x0d, 0x7c, 0x3c, 0x9d, 0xc1, 0x6e, 0xc0, 0xb2, 0x3c, 0x1b, 0x2c, 0x5b, 0x92, 0xd6, 0x95, 0x06,
	0x64, 0xd7, 0xc3, 0x3e, 0x75, 0xdc, 0x7e, 0x20, 0xbc, 0xf6, 0x64, 0x44, 0xbd, 0xaa, 0xa5, 0x47,
	0x85, 0xf7, 0x1e, 0xf0, 0x2c, 0xbc, 0x20, 0x9c, 0x5c, 0xfa, 0x86, 0xe1, 0xe4, 0x0e, 0x3e, 0x73,
	0xb3, 0x2f, 0x92, 0xad, 0x6a, 0x6c, 0xa2, 0x3c, 0x9e, 0x8b, 0x3b, 0x9b, 0x5f, 0x2f, 0xee, 0x3c,
	0x84, 0x72, 0x7c, 0x51, 0x65, 0x8b, 0xa8, 0xd5, 0xed, 0x35, 0x5a, 0xbc, 0x6a, 0xb0, 0x35, 0x58,
	0xc1, 0xff, 0x7b, 0xad, 0xfd, 0x66, 0xb5, 0x80, 0x6e, 0x02, 0x48, 0x74, 0x3f, 0x3b, 0xd8, 0x6f,
	0xb5, 0x9f, 0x54, 0x8b, 0xe6, 0x6f, 0x8a, 0x70, 0x75, 0x2f, 0xec, 0x8a, 0xe0, 0x4c, 0x04, 0x0d,
	0x31, 0xb0, 0x26, 0x6e, 0x14, 0x26, 0x01, 0x87, 0x4e, 0x87, 0xbc, 0x4d, 0x25, 0x95, 0x14, 0x90,
	0x35, 0xc2, 0x89, 0xec, 0xe6, 0xe3, 0xbd, 0xad, 0x9f, 0x0a, 0x3c, 0x11, 0xb4, 0xac, 0x8a, 0x3b,
	0x33, 0xb8, 0x6c, 0x76, 0x3f, 0x0f, 0x64, 0x8e, 0xc4, 0x57, 0x86, 0x88, 0x32, 0xde, 0x3b, 0x0d,
	0xcb, 0x40, 0x95, 0xbd, 0x4f, 0xca, 0x9b, 0xb3, 0x90, 0x6c, 0xb6, 0x48, 0x33, 0xef, 0x4e, 0x06,
	0x03, 0xcc, 0xbc, 0x52, 0x94, 0x6a, 0xdd, 0x4f, 0xa1, 0xec, 0xc3, 0xa4, 0x9a, 0x94, 0x25, 0xf0,
	0x51, 0x60, 0x79, 0x21, 0x0e, 0x51, 0x7a, 0x48, 0x3a, 0x5a, 0xf3, 0x38, 0xe4, 0x89, 0x45, 0x68,
	0xeb, 0xd3, 0x96, 0x17, 0xa1, 0x51, 0x2c, 0x97, 0xb2, 0x80, 0xea, 0x40, 0xe5, 0x70, 0xc6, 0x61,
	0xdd, 0xd6, 0x1a, 0x52, 0x30, 0x29, 0x53, 0x77, 0x2f, 0xef, 0xd7, 0xf5, 0x0c, 0x83, 0x6a, 0xef,
	0x55, 0xea, 0x8f, 0x9b, 0xf5, 0x27, 0xdd, 0xe3, 0x83, 0x5e, 0x9d, 0xd7, 0x1f, 0xee, 0xf0, 0x9c,
	0x0c, 0xf3, 0xb7, 0x06, 0x5c, 0x4d, 0xda, 0x27, 0xfb, 0x4e, 0x18, 0xc9, 0xc3, 0xa6, 0xd3, 0x78,
	0x0c, 0x15, 0x8c, 0xd7, 0x91, 0x63, 0xb9, 0x1a, 0xd6, 0xbd, 0x87, 0x5b, 0x17, 0x05, 0x2f, 0x3e,
	0x35, 0x4f, 0x9e, 0x5c, 0xd2, 0x6f, 0x93, 0x91, 0xdc, 0x11, 0x71, 0xc6, 0x98, 0xc1, 0xcd, 0xbf,
	0x1b, 0xf0, 0x56, 0xd7, 0xb3, 0xc6, 0xe1, 0xa9, 0x1f, 0x45, 0xd6, 0x89, 0x2b, 0x92, 0xcd, 0x65,
	0x43, 0xea, 0x47, 0x98, 0x7c, 0x9c, 0x40, 0x21, 0xfa, 0x91, 0x78, 0xf1, 0xb6, 0xd2, 0x29, 0xec,
	0x36, 0x54, 0x42, 0xbd, 0x48, 0x2f, 0x6d, 0x60, 0x6c, 0xa0, 0x8b, 0x68, 0x54, 0x35, 0x7b, 0xee,
	0xc0, 0xa5, 0x84, 0xcd, 0x9b, 0x8c, 0x4e, 0xf0, 0x38, 0xd5, 0x35, 0x4a, 0x66, 0xb7, 0x09, 0x95,
	0x8c, 0xa8, 0xb3, 0xf0, 0xa2, 0xde, 0x60, 0xe2, 0xba, 0x14, 0xa6, 0x55, 0x89, 0x5d, 0x51, 0xf0,
	0x9e, 0x46, 0x65, 0xd2, 0x32, 0xe7, 0xab, 0x97, 0xb3, 0xfd, 0x29, 0x5c, 0x0f, 0xa7, 0xb8, 0xf2,
	0x87, 0x90, 0x6f, 0x13, 0x5f, 0x68, 0x30, 0xbe, 0x48, 0x9c, 0xf9, 0x6b, 0x03, 0x5e, 0x8b, 0xa7,
	0x37, 0x9c, 0xc1, 0x40, 0x35, 0x6f, 0x33, 0xf5, 0x03, 0x66, 0xc0, 0x44, 0x27, 0x55, 0xc1, 0x27,
	0xb4, 0x2c, 0xd7, 0xb2, 0x11, 0x7e, 0xdf, 0x3a, 0x11, 0xae, 0xae, 0x2a, 0x66, 0x07, 0x64, 0xd1,
	0x18, 0x59, 0xc1, 0x50, 0x44, 0x87, 0x16, 0x25, 0x2c, 0x19, 0xdd, 0x33, 0x88, 0xf9, 0x37, 0x2c,
	0xec, 0x67, 0xb7, 0xa2, 0x76, 0x81, 0x4f, 0xd7, 0x58, 0x03, 0xee, 0xfb, 0x91, 0xce, 0xeb, 0x39,
	0x4c, 0xf2, 0x0c, 0x02, 0x7f, 0x14, 0x8b, 0xd0, 0x1b, 0xc9, 0x61, 0xb4, 0x07, 0x3f, 0xe1, 0x50,
	0xf5, 0x78, 0x06, 0x61, 0x9f, 0xc2, 0x66, 0x3f, 0x67, 0x05, 0x47, 0xc4, 0xf5, 0xc9, 0xbb, 0x73,
	0x4d, 0x3e, 0xcf, 0x66, 0x7c, 0x56, 0x86, 0x69, 0x01, 0x64, 0x9a, 0x1b, 0x99, 0x6f, 0x9e, 0x46,
	0xfe, 0x9b, 0x27, 0x9a, 0x7b, 0x28, 0xf4, 0xc7, 0x4e, 0xd5, 0xc9, 0x48, 0xe8, 0xdc, 0x57, 0xce,
	0xe2, 0xec, 0x57, 0xce, 0x7f, 0xe1, 0x73, 0x22, 0xde, 0x56, 0xfa, 0x24, 0xca, 0x58, 0x2e, 0x53,
	0xc8, 0xe5, 0xb0, 0x19, 0xeb, 0x16, 0xe6, 0x58, 0x37, 0x5f, 0x52, 0x14, 0xbf, 0x7e, 0x49, 0x51,
	0x9a, 0x5b, 0x52, 0x2c, 0x65, 0x4b, 0x0a, 0x3c, 0x25, 0xea, 0x44, 0x09, 0x59, 0x12, 0xe8, 0x6a,
	0x23, 0x83, 0x98, 0x27, 0x70, 0x83, 0xfb, 0x2e, 0x56, 0x05, 0xc3, 0x63, 0xf5, 0xfd, 0x27, 0x1b,
	0x1b, 0xa6, 0x7a, 0x0a, 0xc6, 0x6c, 0x4f, 0xe1, 0x3b, 0xb2, 0xb9, 0xee, 0x59, 0x2e, 0x46, 0xed,
	0xa9, 0x2f, 0x0e, 0x29, 0x6e, 0x7e, 0x98, 0xf4, 0x0d, 0xe5, 0x27, 0x8a, 0x30, 0x35, 0x66, 0x06,
	0xd4, 0xad, 0xca, 0x1c, 0x76, 0xef, 0xa7, 0x50, 0x9d, 0xee, 0xd3, 0xb0, 0x32, 0xd0, 0x47, 0x16,
	0x4c, 0x8d, 0x2b, 0x50, 0xec, 0x76, 0xe5, 0x07, 0x26, 0xcc, 0x91, 0x35, 0x5e, 0x7f, 0xdc, 0x7a,
	0x2a, 0xbf, 0x29, 0xad, 0x43, 0x99, 0xd7, 0x0e, 0x7a, 0xc4, 0x53, 0xba, 0xf7, 0x01, 0x54, 0xa7,
	0xdf, 0x79, 0x92, 0xfd, 0xb8, 0xfd, 0xa4, 0xdd, 0xf9, 0xb4, 0x8d, 0x42, 0xae, 0xc2, 0x66, 0xad,
	0xd9, 0xed, 0xd5, 0x8f, 0x78, 0xaf, 0xdd, 0x39, 0xac, 0x35, 0x1a, 0xad, 0xf6, 0xc7, 0xd5, 0xc2,
	0xbd, 0x43, 0xb8, 0xb9, 0xf8, 0x79, 0x8a, 0xd9, 0x75, 0x4b, 0x4b, 0xe8, 0x1d, 0xf2, 0xce, 0x51,
	0xa7, 0xde, 0xd9, 0xef, 0x3d, 0x6d, 0x72, 0xf9, 0xc5, 0x0b, 0x45, 0x5e, 0x81, 0x6a, 0xb3, 0x5d,
	0xe7, 0x9f, 0x1d, 0x1e, 0xc9, 0xcf, 0x63, 0x9f, 0x77, 0xda, 0xcd, 0x2e, 0x4a, 0xec, 0xe0, 0x03,
	0x75, 0x3a, 0xa1, 0xb0, 0x4d, 0xd8, 0x48, 0x52, 0x4a, 0xfb, 0x78, 0x5f, 0x7e, 0x13, 0x62, 0x30,
	0x95, 0x65, 0x50, 0xe2, 0x65, 0xb8, 0x94, 0xc7, 0xea, 0xd5, 0xc2, 0xee, 0x07, 0x70, 0xdb, 0x0f,
	0x86, 0xdb, 0xf2, 0xd3, 0xcd, 0xa9, 0xc8, 0xdd, 0x9e, 0xb1, 0xde, 0xb3, 0xfa, 0xb3, 0x0b, 0x32,
	0x82, 0xd3, 0x7a, 0xe1, 0x97, 0x86, 0xf1, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xb2, 0x6c,
	0xe2, 0xcd, 0x20, 0x00, 0x00,
}
