// Code generated by protoc-gen-go.
// source: gopkg.in/freddierice/go-hproto.v1/hdfs/ReconfigurationProtocol.proto
// DO NOT EDIT!

package hproto_hdfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// * Asks NN/DN to reload configuration file.
type StartReconfigurationRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StartReconfigurationRequestProto) Reset()         { *m = StartReconfigurationRequestProto{} }
func (m *StartReconfigurationRequestProto) String() string { return proto.CompactTextString(m) }
func (*StartReconfigurationRequestProto) ProtoMessage()    {}
func (*StartReconfigurationRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{0}
}

type StartReconfigurationResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StartReconfigurationResponseProto) Reset()         { *m = StartReconfigurationResponseProto{} }
func (m *StartReconfigurationResponseProto) String() string { return proto.CompactTextString(m) }
func (*StartReconfigurationResponseProto) ProtoMessage()    {}
func (*StartReconfigurationResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{1}
}

// * Query the running status of reconfiguration process
type GetReconfigurationStatusRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetReconfigurationStatusRequestProto) Reset()         { *m = GetReconfigurationStatusRequestProto{} }
func (m *GetReconfigurationStatusRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetReconfigurationStatusRequestProto) ProtoMessage()    {}
func (*GetReconfigurationStatusRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{2}
}

type GetReconfigurationStatusConfigChangeProto struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	OldValue         *string `protobuf:"bytes,2,req,name=oldValue" json:"oldValue,omitempty"`
	NewValue         *string `protobuf:"bytes,3,opt,name=newValue" json:"newValue,omitempty"`
	ErrorMessage     *string `protobuf:"bytes,4,opt,name=errorMessage" json:"errorMessage,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetReconfigurationStatusConfigChangeProto) Reset() {
	*m = GetReconfigurationStatusConfigChangeProto{}
}
func (m *GetReconfigurationStatusConfigChangeProto) String() string { return proto.CompactTextString(m) }
func (*GetReconfigurationStatusConfigChangeProto) ProtoMessage()    {}
func (*GetReconfigurationStatusConfigChangeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{3}
}

func (m *GetReconfigurationStatusConfigChangeProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GetReconfigurationStatusConfigChangeProto) GetOldValue() string {
	if m != nil && m.OldValue != nil {
		return *m.OldValue
	}
	return ""
}

func (m *GetReconfigurationStatusConfigChangeProto) GetNewValue() string {
	if m != nil && m.NewValue != nil {
		return *m.NewValue
	}
	return ""
}

func (m *GetReconfigurationStatusConfigChangeProto) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type GetReconfigurationStatusResponseProto struct {
	StartTime        *int64                                       `protobuf:"varint,1,req,name=startTime" json:"startTime,omitempty"`
	EndTime          *int64                                       `protobuf:"varint,2,opt,name=endTime" json:"endTime,omitempty"`
	Changes          []*GetReconfigurationStatusConfigChangeProto `protobuf:"bytes,3,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte                                       `json:"-"`
}

func (m *GetReconfigurationStatusResponseProto) Reset()         { *m = GetReconfigurationStatusResponseProto{} }
func (m *GetReconfigurationStatusResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetReconfigurationStatusResponseProto) ProtoMessage()    {}
func (*GetReconfigurationStatusResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{4}
}

func (m *GetReconfigurationStatusResponseProto) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *GetReconfigurationStatusResponseProto) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *GetReconfigurationStatusResponseProto) GetChanges() []*GetReconfigurationStatusConfigChangeProto {
	if m != nil {
		return m.Changes
	}
	return nil
}

// * Query the reconfigurable properties on NN/DN.
type ListReconfigurablePropertiesRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ListReconfigurablePropertiesRequestProto) Reset() {
	*m = ListReconfigurablePropertiesRequestProto{}
}
func (m *ListReconfigurablePropertiesRequestProto) String() string { return proto.CompactTextString(m) }
func (*ListReconfigurablePropertiesRequestProto) ProtoMessage()    {}
func (*ListReconfigurablePropertiesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{5}
}

type ListReconfigurablePropertiesResponseProto struct {
	Name             []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ListReconfigurablePropertiesResponseProto) Reset() {
	*m = ListReconfigurablePropertiesResponseProto{}
}
func (m *ListReconfigurablePropertiesResponseProto) String() string { return proto.CompactTextString(m) }
func (*ListReconfigurablePropertiesResponseProto) ProtoMessage()    {}
func (*ListReconfigurablePropertiesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{6}
}

func (m *ListReconfigurablePropertiesResponseProto) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*StartReconfigurationRequestProto)(nil), "hproto.hdfs.StartReconfigurationRequestProto")
	proto.RegisterType((*StartReconfigurationResponseProto)(nil), "hproto.hdfs.StartReconfigurationResponseProto")
	proto.RegisterType((*GetReconfigurationStatusRequestProto)(nil), "hproto.hdfs.GetReconfigurationStatusRequestProto")
	proto.RegisterType((*GetReconfigurationStatusConfigChangeProto)(nil), "hproto.hdfs.GetReconfigurationStatusConfigChangeProto")
	proto.RegisterType((*GetReconfigurationStatusResponseProto)(nil), "hproto.hdfs.GetReconfigurationStatusResponseProto")
	proto.RegisterType((*ListReconfigurablePropertiesRequestProto)(nil), "hproto.hdfs.ListReconfigurablePropertiesRequestProto")
	proto.RegisterType((*ListReconfigurablePropertiesResponseProto)(nil), "hproto.hdfs.ListReconfigurablePropertiesResponseProto")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ReconfigurationProtocolService service

type ReconfigurationProtocolServiceClient interface {
	GetReconfigurationStatus(ctx context.Context, in *GetReconfigurationStatusRequestProto, opts ...grpc.CallOption) (*GetReconfigurationStatusResponseProto, error)
	StartReconfiguration(ctx context.Context, in *StartReconfigurationRequestProto, opts ...grpc.CallOption) (*StartReconfigurationResponseProto, error)
	ListReconfigurableProperties(ctx context.Context, in *ListReconfigurablePropertiesRequestProto, opts ...grpc.CallOption) (*ListReconfigurablePropertiesResponseProto, error)
}

type reconfigurationProtocolServiceClient struct {
	cc *grpc.ClientConn
}

func NewReconfigurationProtocolServiceClient(cc *grpc.ClientConn) ReconfigurationProtocolServiceClient {
	return &reconfigurationProtocolServiceClient{cc}
}

func (c *reconfigurationProtocolServiceClient) GetReconfigurationStatus(ctx context.Context, in *GetReconfigurationStatusRequestProto, opts ...grpc.CallOption) (*GetReconfigurationStatusResponseProto, error) {
	out := new(GetReconfigurationStatusResponseProto)
	err := grpc.Invoke(ctx, "/hproto.hdfs.ReconfigurationProtocolService/getReconfigurationStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconfigurationProtocolServiceClient) StartReconfiguration(ctx context.Context, in *StartReconfigurationRequestProto, opts ...grpc.CallOption) (*StartReconfigurationResponseProto, error) {
	out := new(StartReconfigurationResponseProto)
	err := grpc.Invoke(ctx, "/hproto.hdfs.ReconfigurationProtocolService/startReconfiguration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconfigurationProtocolServiceClient) ListReconfigurableProperties(ctx context.Context, in *ListReconfigurablePropertiesRequestProto, opts ...grpc.CallOption) (*ListReconfigurablePropertiesResponseProto, error) {
	out := new(ListReconfigurablePropertiesResponseProto)
	err := grpc.Invoke(ctx, "/hproto.hdfs.ReconfigurationProtocolService/listReconfigurableProperties", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ReconfigurationProtocolService service

type ReconfigurationProtocolServiceServer interface {
	GetReconfigurationStatus(context.Context, *GetReconfigurationStatusRequestProto) (*GetReconfigurationStatusResponseProto, error)
	StartReconfiguration(context.Context, *StartReconfigurationRequestProto) (*StartReconfigurationResponseProto, error)
	ListReconfigurableProperties(context.Context, *ListReconfigurablePropertiesRequestProto) (*ListReconfigurablePropertiesResponseProto, error)
}

func RegisterReconfigurationProtocolServiceServer(s *grpc.Server, srv ReconfigurationProtocolServiceServer) {
	s.RegisterService(&_ReconfigurationProtocolService_serviceDesc, srv)
}

func _ReconfigurationProtocolService_GetReconfigurationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReconfigurationStatusRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconfigurationProtocolServiceServer).GetReconfigurationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.hdfs.ReconfigurationProtocolService/GetReconfigurationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconfigurationProtocolServiceServer).GetReconfigurationStatus(ctx, req.(*GetReconfigurationStatusRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReconfigurationProtocolService_StartReconfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartReconfigurationRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconfigurationProtocolServiceServer).StartReconfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.hdfs.ReconfigurationProtocolService/StartReconfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconfigurationProtocolServiceServer).StartReconfiguration(ctx, req.(*StartReconfigurationRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReconfigurationProtocolService_ListReconfigurableProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReconfigurablePropertiesRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconfigurationProtocolServiceServer).ListReconfigurableProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.hdfs.ReconfigurationProtocolService/ListReconfigurableProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconfigurationProtocolServiceServer).ListReconfigurableProperties(ctx, req.(*ListReconfigurablePropertiesRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReconfigurationProtocolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hproto.hdfs.ReconfigurationProtocolService",
	HandlerType: (*ReconfigurationProtocolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getReconfigurationStatus",
			Handler:    _ReconfigurationProtocolService_GetReconfigurationStatus_Handler,
		},
		{
			MethodName: "startReconfiguration",
			Handler:    _ReconfigurationProtocolService_StartReconfiguration_Handler,
		},
		{
			MethodName: "listReconfigurableProperties",
			Handler:    _ReconfigurationProtocolService_ListReconfigurableProperties_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor8,
}

func init() {
	proto.RegisterFile("gopkg.in/freddierice/go-hproto.v1/hdfs/ReconfigurationProtocol.proto", fileDescriptor8)
}

var fileDescriptor8 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x96, 0x9b, 0x49, 0x63, 0x6f, 0x9c, 0x2c, 0x0e, 0x51, 0x34, 0x50, 0x09, 0x0c, 0x75, 0x48,
	0x4b, 0xb4, 0x4a, 0xec, 0x8a, 0xb4, 0x21, 0x71, 0x19, 0xd2, 0x94, 0x21, 0xee, 0x26, 0x79, 0x75,
	0x2c, 0x82, 0x1d, 0xec, 0xa4, 0x9c, 0xb9, 0x71, 0xe1, 0x17, 0x70, 0xe1, 0xce, 0x89, 0x7f, 0x48,
	0xe2, 0x36, 0xd4, 0xa9, 0x9a, 0x92, 0x9d, 0x5a, 0xbf, 0xf7, 0x7d, 0x9f, 0xdf, 0xf7, 0xf9, 0x29,
	0xf0, 0x86, 0xab, 0xf2, 0x13, 0x8f, 0x84, 0x8c, 0x17, 0x1a, 0xb3, 0x4c, 0xa0, 0x16, 0x29, 0xc6,
	0x5c, 0x9d, 0xe7, 0xa5, 0x56, 0x95, 0x8a, 0x96, 0x17, 0x71, 0x9e, 0x2d, 0x4c, 0x9c, 0x60, 0xaa,
	0xe4, 0x42, 0xf0, 0x5a, 0xb3, 0x4a, 0x28, 0x79, 0xdb, 0x36, 0x53, 0x55, 0x44, 0x16, 0x45, 0x8f,
	0xd7, 0xe8, 0x16, 0x1a, 0x86, 0x30, 0xbd, 0xab, 0x98, 0xae, 0xb6, 0x28, 0x09, 0x7e, 0xa9, 0xd1,
	0x54, 0x96, 0x19, 0x3e, 0x83, 0xa7, 0xbb, 0x31, 0xa6, 0x54, 0xd2, 0xe0, 0x0a, 0xf4, 0x02, 0x9e,
	0xbf, 0xc5, 0x6d, 0x48, 0x43, 0xab, 0x6a, 0xd3, 0x13, 0xfb, 0x49, 0xe0, 0x6c, 0x08, 0x78, 0x6d,
	0x4b, 0xd7, 0x39, 0x93, 0x7c, 0xa5, 0x4a, 0x29, 0x1c, 0x48, 0xf6, 0x19, 0x7d, 0x32, 0x9d, 0xcc,
	0x8e, 0x12, 0xfb, 0x9f, 0x06, 0xf0, 0x40, 0x15, 0xd9, 0x07, 0x56, 0xd4, 0xe8, 0x4f, 0x6c, 0xfd,
	0xdf, 0xb9, 0xed, 0x49, 0xfc, 0xba, 0xea, 0x79, 0x53, 0xd2, 0xf6, 0xba, 0x33, 0x0d, 0xe1, 0x21,
	0x6a, 0xad, 0xf4, 0x3b, 0x34, 0x86, 0x71, 0xf4, 0x0f, 0x6c, 0xbf, 0x57, 0x0b, 0xff, 0x10, 0x38,
	0x1d, 0xb6, 0xe1, 0xf8, 0xa5, 0x27, 0x70, 0x64, 0xda, 0x50, 0xde, 0x8b, 0xf5, 0x78, 0x5e, 0xb2,
	0x29, 0x50, 0x1f, 0x0e, 0x51, 0x66, 0xb6, 0x37, 0x69, 0xae, 0xf1, 0x92, 0xee, 0x48, 0x6f, 0xe1,
	0x30, 0xb5, 0x06, 0x4d, 0x33, 0xa0, 0x37, 0x3b, 0x9e, 0x5f, 0x46, 0xce, 0x7b, 0x44, 0xa3, 0xa3,
	0x49, 0x3a, 0x99, 0xf0, 0x25, 0xcc, 0x6e, 0x84, 0x71, 0x69, 0x1f, 0x8b, 0x16, 0x53, 0xa2, 0xae,
	0x04, 0xf6, 0xd3, 0x7f, 0x0d, 0x67, 0xfb, 0xb1, 0xae, 0xc5, 0x4d, 0xf8, 0x5e, 0x17, 0xfe, 0xfc,
	0xb7, 0x07, 0x4f, 0x06, 0xd6, 0xeb, 0x0e, 0xf5, 0xb2, 0xd9, 0x47, 0xfa, 0x8d, 0x80, 0xcf, 0x07,
	0x6c, 0xd0, 0x8b, 0x51, 0x6e, 0xdd, 0x99, 0x83, 0xf9, 0x48, 0x8a, 0x3b, 0x7a, 0x0d, 0x8f, 0xcc,
	0x8e, 0x95, 0xa5, 0xe7, 0x3d, 0xad, 0xff, 0x6d, 0x7e, 0x10, 0x8d, 0x80, 0xbb, 0xd7, 0xfe, 0x20,
	0x70, 0x52, 0xec, 0xc9, 0x97, 0xbe, 0xea, 0x09, 0x8e, 0x7d, 0xb6, 0xe0, 0xf2, 0x1e, 0x34, 0x67,
	0x9e, 0xab, 0x1b, 0x38, 0x55, 0x9a, 0x47, 0xac, 0x64, 0x69, 0x8e, 0x3d, 0x8d, 0xb2, 0xf7, 0x4d,
	0xb8, 0x7a, 0x3c, 0xf0, 0xa6, 0xf6, 0xd7, 0x7c, 0x27, 0xe4, 0x17, 0x21, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x30, 0x58, 0xd3, 0x20, 0x7f, 0x04, 0x00, 0x00,
}
