// Code generated by protoc-gen-go.
// source: gopkg.in/freddierice/go-hproto.v1/yarn/applicationmaster_protocol.proto
// DO NOT EDIT!

package hproto_yarn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ApplicationMasterProtocolService service

type ApplicationMasterProtocolServiceClient interface {
	RegisterApplicationMaster(ctx context.Context, in *RegisterApplicationMasterRequestProto, opts ...grpc.CallOption) (*RegisterApplicationMasterResponseProto, error)
	FinishApplicationMaster(ctx context.Context, in *FinishApplicationMasterRequestProto, opts ...grpc.CallOption) (*FinishApplicationMasterResponseProto, error)
	Allocate(ctx context.Context, in *AllocateRequestProto, opts ...grpc.CallOption) (*AllocateResponseProto, error)
}

type applicationMasterProtocolServiceClient struct {
	cc *grpc.ClientConn
}

func NewApplicationMasterProtocolServiceClient(cc *grpc.ClientConn) ApplicationMasterProtocolServiceClient {
	return &applicationMasterProtocolServiceClient{cc}
}

func (c *applicationMasterProtocolServiceClient) RegisterApplicationMaster(ctx context.Context, in *RegisterApplicationMasterRequestProto, opts ...grpc.CallOption) (*RegisterApplicationMasterResponseProto, error) {
	out := new(RegisterApplicationMasterResponseProto)
	err := grpc.Invoke(ctx, "/hproto.yarn.ApplicationMasterProtocolService/registerApplicationMaster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationMasterProtocolServiceClient) FinishApplicationMaster(ctx context.Context, in *FinishApplicationMasterRequestProto, opts ...grpc.CallOption) (*FinishApplicationMasterResponseProto, error) {
	out := new(FinishApplicationMasterResponseProto)
	err := grpc.Invoke(ctx, "/hproto.yarn.ApplicationMasterProtocolService/finishApplicationMaster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationMasterProtocolServiceClient) Allocate(ctx context.Context, in *AllocateRequestProto, opts ...grpc.CallOption) (*AllocateResponseProto, error) {
	out := new(AllocateResponseProto)
	err := grpc.Invoke(ctx, "/hproto.yarn.ApplicationMasterProtocolService/allocate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApplicationMasterProtocolService service

type ApplicationMasterProtocolServiceServer interface {
	RegisterApplicationMaster(context.Context, *RegisterApplicationMasterRequestProto) (*RegisterApplicationMasterResponseProto, error)
	FinishApplicationMaster(context.Context, *FinishApplicationMasterRequestProto) (*FinishApplicationMasterResponseProto, error)
	Allocate(context.Context, *AllocateRequestProto) (*AllocateResponseProto, error)
}

func RegisterApplicationMasterProtocolServiceServer(s *grpc.Server, srv ApplicationMasterProtocolServiceServer) {
	s.RegisterService(&_ApplicationMasterProtocolService_serviceDesc, srv)
}

func _ApplicationMasterProtocolService_RegisterApplicationMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterApplicationMasterRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationMasterProtocolServiceServer).RegisterApplicationMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.yarn.ApplicationMasterProtocolService/RegisterApplicationMaster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationMasterProtocolServiceServer).RegisterApplicationMaster(ctx, req.(*RegisterApplicationMasterRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationMasterProtocolService_FinishApplicationMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishApplicationMasterRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationMasterProtocolServiceServer).FinishApplicationMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.yarn.ApplicationMasterProtocolService/FinishApplicationMaster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationMasterProtocolServiceServer).FinishApplicationMaster(ctx, req.(*FinishApplicationMasterRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationMasterProtocolService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationMasterProtocolServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.yarn.ApplicationMasterProtocolService/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationMasterProtocolServiceServer).Allocate(ctx, req.(*AllocateRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApplicationMasterProtocolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hproto.yarn.ApplicationMasterProtocolService",
	HandlerType: (*ApplicationMasterProtocolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registerApplicationMaster",
			Handler:    _ApplicationMasterProtocolService_RegisterApplicationMaster_Handler,
		},
		{
			MethodName: "finishApplicationMaster",
			Handler:    _ApplicationMasterProtocolService_FinishApplicationMaster_Handler,
		},
		{
			MethodName: "allocate",
			Handler:    _ApplicationMasterProtocolService_Allocate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor2,
}

func init() {
	proto.RegisterFile("gopkg.in/freddierice/go-hproto.v1/yarn/applicationmaster_protocol.proto", fileDescriptor2)
}

var fileDescriptor2 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x72, 0x4f, 0xcf, 0x2f, 0xc8,
	0x4e, 0xd7, 0xcb, 0xcc, 0xd3, 0x4f, 0x2b, 0x4a, 0x4d, 0x49, 0xc9, 0x4c, 0x2d, 0xca, 0x4c, 0x4e,
	0xd5, 0x4f, 0xcf, 0xd7, 0xcd, 0x28, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2b, 0x33, 0xd4, 0xaf, 0x4c,
	0x2c, 0xca, 0xd3, 0x4f, 0x2c, 0x28, 0xc8, 0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xcb, 0x4d,
	0x2c, 0x2e, 0x49, 0x2d, 0x8a, 0x07, 0xcb, 0x27, 0xe7, 0xe7, 0xe8, 0x81, 0x19, 0x42, 0xdc, 0x50,
	0x0d, 0x20, 0xd5, 0x52, 0x0e, 0x44, 0x9a, 0x0a, 0x22, 0xe2, 0x8b, 0x53, 0x8b, 0xca, 0x80, 0xd2,
	0x10, 0x03, 0x8b, 0x21, 0xc6, 0x19, 0xfd, 0x61, 0xe2, 0x52, 0x70, 0x44, 0xd8, 0xe9, 0x0b, 0xb6,
	0x33, 0x00, 0x6a, 0x65, 0x30, 0x44, 0x87, 0x50, 0x0b, 0x23, 0x97, 0x64, 0x51, 0x6a, 0x7a, 0x26,
	0x48, 0x0e, 0x43, 0xb1, 0x90, 0x91, 0x1e, 0x92, 0x93, 0xf4, 0x82, 0x70, 0xa9, 0x0b, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x01, 0x9b, 0x2d, 0x65, 0x4c, 0xac, 0x9e, 0xe2, 0x82, 0xfc, 0xbc, 0xe2,
	0x54, 0xb0, 0x26, 0xa1, 0x3a, 0x2e, 0xf1, 0xb4, 0xcc, 0xbc, 0xcc, 0xe2, 0x0c, 0x4c, 0x37, 0x18,
	0xa0, 0x98, 0xe7, 0x86, 0x5d, 0x15, 0x8a, 0x0b, 0x0c, 0x89, 0xd3, 0x81, 0x6c, 0x7f, 0x20, 0x17,
	0x47, 0x62, 0x4e, 0x4e, 0x3e, 0x50, 0x41, 0xaa, 0x90, 0x22, 0x8a, 0x76, 0x47, 0xa8, 0x30, 0x8a,
	0x0d, 0x4a, 0x38, 0x94, 0x20, 0x19, 0xe9, 0x64, 0xcf, 0x25, 0x93, 0x5f, 0x94, 0xae, 0x97, 0x58,
	0x90, 0x98, 0x9c, 0x91, 0x8a, 0xa2, 0x1e, 0xcc, 0x74, 0x92, 0xc4, 0x19, 0x37, 0x1d, 0x8c, 0x8c,
	0x0b, 0x18, 0x19, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0x88, 0x7b, 0x61, 0x58, 0x02, 0x00,
	0x00,
}
