// Code generated by protoc-gen-go.
// source: gopkg.in/freddierice/go-hproto.v1/yarn/ResourceTracker.proto
// DO NOT EDIT!

package hproto_yarn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ResourceTrackerService service

type ResourceTrackerServiceClient interface {
	RegisterNodeManager(ctx context.Context, in *RegisterNodeManagerRequestProto, opts ...grpc.CallOption) (*RegisterNodeManagerResponseProto, error)
	NodeHeartbeat(ctx context.Context, in *NodeHeartbeatRequestProto, opts ...grpc.CallOption) (*NodeHeartbeatResponseProto, error)
	UnRegisterNodeManager(ctx context.Context, in *UnRegisterNodeManagerRequestProto, opts ...grpc.CallOption) (*UnRegisterNodeManagerResponseProto, error)
}

type resourceTrackerServiceClient struct {
	cc *grpc.ClientConn
}

func NewResourceTrackerServiceClient(cc *grpc.ClientConn) ResourceTrackerServiceClient {
	return &resourceTrackerServiceClient{cc}
}

func (c *resourceTrackerServiceClient) RegisterNodeManager(ctx context.Context, in *RegisterNodeManagerRequestProto, opts ...grpc.CallOption) (*RegisterNodeManagerResponseProto, error) {
	out := new(RegisterNodeManagerResponseProto)
	err := grpc.Invoke(ctx, "/hproto.yarn.ResourceTrackerService/registerNodeManager", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTrackerServiceClient) NodeHeartbeat(ctx context.Context, in *NodeHeartbeatRequestProto, opts ...grpc.CallOption) (*NodeHeartbeatResponseProto, error) {
	out := new(NodeHeartbeatResponseProto)
	err := grpc.Invoke(ctx, "/hproto.yarn.ResourceTrackerService/nodeHeartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTrackerServiceClient) UnRegisterNodeManager(ctx context.Context, in *UnRegisterNodeManagerRequestProto, opts ...grpc.CallOption) (*UnRegisterNodeManagerResponseProto, error) {
	out := new(UnRegisterNodeManagerResponseProto)
	err := grpc.Invoke(ctx, "/hproto.yarn.ResourceTrackerService/unRegisterNodeManager", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ResourceTrackerService service

type ResourceTrackerServiceServer interface {
	RegisterNodeManager(context.Context, *RegisterNodeManagerRequestProto) (*RegisterNodeManagerResponseProto, error)
	NodeHeartbeat(context.Context, *NodeHeartbeatRequestProto) (*NodeHeartbeatResponseProto, error)
	UnRegisterNodeManager(context.Context, *UnRegisterNodeManagerRequestProto) (*UnRegisterNodeManagerResponseProto, error)
}

func RegisterResourceTrackerServiceServer(s *grpc.Server, srv ResourceTrackerServiceServer) {
	s.RegisterService(&_ResourceTrackerService_serviceDesc, srv)
}

func _ResourceTrackerService_RegisterNodeManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeManagerRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTrackerServiceServer).RegisterNodeManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.yarn.ResourceTrackerService/RegisterNodeManager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTrackerServiceServer).RegisterNodeManager(ctx, req.(*RegisterNodeManagerRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTrackerService_NodeHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHeartbeatRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTrackerServiceServer).NodeHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.yarn.ResourceTrackerService/NodeHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTrackerServiceServer).NodeHeartbeat(ctx, req.(*NodeHeartbeatRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTrackerService_UnRegisterNodeManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnRegisterNodeManagerRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTrackerServiceServer).UnRegisterNodeManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.yarn.ResourceTrackerService/UnRegisterNodeManager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTrackerServiceServer).UnRegisterNodeManager(ctx, req.(*UnRegisterNodeManagerRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceTrackerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hproto.yarn.ResourceTrackerService",
	HandlerType: (*ResourceTrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registerNodeManager",
			Handler:    _ResourceTrackerService_RegisterNodeManager_Handler,
		},
		{
			MethodName: "nodeHeartbeat",
			Handler:    _ResourceTrackerService_NodeHeartbeat_Handler,
		},
		{
			MethodName: "unRegisterNodeManager",
			Handler:    _ResourceTrackerService_UnRegisterNodeManager_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor9,
}

func init() {
	proto.RegisterFile("gopkg.in/freddierice/go-hproto.v1/yarn/ResourceTracker.proto", fileDescriptor9)
}

var fileDescriptor9 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0xd1, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0x60, 0x85, 0xd1, 0x08, 0x21, 0x19, 0xc1, 0x50, 0x31, 0xc3, 0x42, 0x6d, 0x81, 0xc4,
	0xc6, 0xd4, 0x89, 0x85, 0x08, 0x05, 0x98, 0x83, 0x71, 0x7e, 0xdc, 0xa8, 0xaa, 0x2f, 0x9c, 0x9d,
	0x0a, 0xde, 0x80, 0xc7, 0xe0, 0xf1, 0x78, 0x0c, 0x9a, 0x84, 0x21, 0x29, 0xa8, 0xcd, 0x12, 0xc5,
	0xba, 0xef, 0xee, 0x3f, 0xcb, 0xe2, 0xc6, 0x51, 0xb5, 0x70, 0xaa, 0xf4, 0xfa, 0x95, 0x51, 0x14,
	0x25, 0xb8, 0xb4, 0xd0, 0x8e, 0xa6, 0xf3, 0x8a, 0x29, 0x92, 0x5a, 0x5d, 0xea, 0x0f, 0xc3, 0x5e,
	0x67, 0x08, 0x54, 0xb3, 0xc5, 0x23, 0x1b, 0xbb, 0x00, 0xab, 0xb6, 0x2a, 0xf7, 0x7f, 0x55, 0x43,
	0x26, 0xe9, 0xc8, 0x51, 0xcd, 0x27, 0x0f, 0xe0, 0x15, 0x38, 0xb7, 0xb4, 0x5c, 0x52, 0x77, 0x5a,
	0xe3, 0xbc, 0x85, 0xa1, 0x1b, 0x7e, 0xf5, 0xbd, 0x27, 0x4e, 0x36, 0x62, 0x1f, 0x3a, 0x27, 0x59,
	0x1c, 0x31, 0x5c, 0x19, 0x22, 0x38, 0xa5, 0x02, 0x77, 0xc6, 0x1b, 0x07, 0x96, 0x17, 0xaa, 0xb7,
	0x8f, 0xca, 0xfe, 0x8a, 0x0c, 0x6f, 0x35, 0x42, 0xbc, 0x6f, 0xd0, 0x64, 0xba, 0x5b, 0x87, 0x8a,
	0x7c, 0x40, 0xcb, 0xe5, 0xb3, 0x38, 0xf0, 0xeb, 0xda, 0x2d, 0x0c, 0xc7, 0x17, 0x98, 0x28, 0xcf,
	0x06, 0xfd, 0x69, 0xbf, 0x36, 0xc8, 0x39, 0xdf, 0xe6, 0xfa, 0x09, 0xef, 0xe2, 0xb8, 0xf6, 0xff,
	0xec, 0x21, 0xd5, 0x60, 0xc2, 0x93, 0xdf, 0x75, 0x33, 0x3d, 0xc6, 0xf7, 0x92, 0x67, 0xd7, 0xe2,
	0x94, 0xd8, 0x29, 0x53, 0x19, 0x3b, 0xc7, 0xa0, 0xb9, 0xfd, 0x9d, 0x1d, 0x6e, 0xbc, 0xc3, 0x67,
	0x92, 0x7c, 0x25, 0xc9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x64, 0xed, 0xef, 0x3d, 0x02,
	0x00, 0x00,
}
