// Code generated by protoc-gen-go.
// source: gopkg.in/freddierice/go-hproto.v1/yarn/yarn_server_nodemanager_service_protos.proto
// DO NOT EDIT!

package hproto_yarn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ResourceStatusTypeProto int32

const (
	ResourceStatusTypeProto_FETCH_PENDING ResourceStatusTypeProto = 1
	ResourceStatusTypeProto_FETCH_SUCCESS ResourceStatusTypeProto = 2
	ResourceStatusTypeProto_FETCH_FAILURE ResourceStatusTypeProto = 3
)

var ResourceStatusTypeProto_name = map[int32]string{
	1: "FETCH_PENDING",
	2: "FETCH_SUCCESS",
	3: "FETCH_FAILURE",
}
var ResourceStatusTypeProto_value = map[string]int32{
	"FETCH_PENDING": 1,
	"FETCH_SUCCESS": 2,
	"FETCH_FAILURE": 3,
}

func (x ResourceStatusTypeProto) Enum() *ResourceStatusTypeProto {
	p := new(ResourceStatusTypeProto)
	*p = x
	return p
}
func (x ResourceStatusTypeProto) String() string {
	return proto.EnumName(ResourceStatusTypeProto_name, int32(x))
}
func (x *ResourceStatusTypeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResourceStatusTypeProto_value, data, "ResourceStatusTypeProto")
	if err != nil {
		return err
	}
	*x = ResourceStatusTypeProto(value)
	return nil
}
func (ResourceStatusTypeProto) EnumDescriptor() ([]byte, []int) { return fileDescriptor17, []int{0} }

type LocalizerActionProto int32

const (
	LocalizerActionProto_LIVE LocalizerActionProto = 1
	LocalizerActionProto_DIE  LocalizerActionProto = 2
)

var LocalizerActionProto_name = map[int32]string{
	1: "LIVE",
	2: "DIE",
}
var LocalizerActionProto_value = map[string]int32{
	"LIVE": 1,
	"DIE":  2,
}

func (x LocalizerActionProto) Enum() *LocalizerActionProto {
	p := new(LocalizerActionProto)
	*p = x
	return p
}
func (x LocalizerActionProto) String() string {
	return proto.EnumName(LocalizerActionProto_name, int32(x))
}
func (x *LocalizerActionProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LocalizerActionProto_value, data, "LocalizerActionProto")
	if err != nil {
		return err
	}
	*x = LocalizerActionProto(value)
	return nil
}
func (LocalizerActionProto) EnumDescriptor() ([]byte, []int) { return fileDescriptor17, []int{1} }

type LocalResourceStatusProto struct {
	Resource         *LocalResourceProto       `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	Status           *ResourceStatusTypeProto  `protobuf:"varint,2,opt,name=status,enum=hproto.yarn.ResourceStatusTypeProto" json:"status,omitempty"`
	LocalPath        *URLProto                 `protobuf:"bytes,3,opt,name=localPath" json:"localPath,omitempty"`
	LocalSize        *int64                    `protobuf:"varint,4,opt,name=localSize" json:"localSize,omitempty"`
	Exception        *SerializedExceptionProto `protobuf:"bytes,5,opt,name=exception" json:"exception,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *LocalResourceStatusProto) Reset()                    { *m = LocalResourceStatusProto{} }
func (m *LocalResourceStatusProto) String() string            { return proto.CompactTextString(m) }
func (*LocalResourceStatusProto) ProtoMessage()               {}
func (*LocalResourceStatusProto) Descriptor() ([]byte, []int) { return fileDescriptor17, []int{0} }

func (m *LocalResourceStatusProto) GetResource() *LocalResourceProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *LocalResourceStatusProto) GetStatus() ResourceStatusTypeProto {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ResourceStatusTypeProto_FETCH_PENDING
}

func (m *LocalResourceStatusProto) GetLocalPath() *URLProto {
	if m != nil {
		return m.LocalPath
	}
	return nil
}

func (m *LocalResourceStatusProto) GetLocalSize() int64 {
	if m != nil && m.LocalSize != nil {
		return *m.LocalSize
	}
	return 0
}

func (m *LocalResourceStatusProto) GetException() *SerializedExceptionProto {
	if m != nil {
		return m.Exception
	}
	return nil
}

type LocalizerStatusProto struct {
	LocalizerId      *string                     `protobuf:"bytes,1,opt,name=localizer_id,json=localizerId" json:"localizer_id,omitempty"`
	Resources        []*LocalResourceStatusProto `protobuf:"bytes,2,rep,name=resources" json:"resources,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *LocalizerStatusProto) Reset()                    { *m = LocalizerStatusProto{} }
func (m *LocalizerStatusProto) String() string            { return proto.CompactTextString(m) }
func (*LocalizerStatusProto) ProtoMessage()               {}
func (*LocalizerStatusProto) Descriptor() ([]byte, []int) { return fileDescriptor17, []int{1} }

func (m *LocalizerStatusProto) GetLocalizerId() string {
	if m != nil && m.LocalizerId != nil {
		return *m.LocalizerId
	}
	return ""
}

func (m *LocalizerStatusProto) GetResources() []*LocalResourceStatusProto {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ResourceLocalizationSpecProto struct {
	Resource             *LocalResourceProto `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	DestinationDirectory *URLProto           `protobuf:"bytes,2,opt,name=destination_directory,json=destinationDirectory" json:"destination_directory,omitempty"`
	XXX_unrecognized     []byte              `json:"-"`
}

func (m *ResourceLocalizationSpecProto) Reset()                    { *m = ResourceLocalizationSpecProto{} }
func (m *ResourceLocalizationSpecProto) String() string            { return proto.CompactTextString(m) }
func (*ResourceLocalizationSpecProto) ProtoMessage()               {}
func (*ResourceLocalizationSpecProto) Descriptor() ([]byte, []int) { return fileDescriptor17, []int{2} }

func (m *ResourceLocalizationSpecProto) GetResource() *LocalResourceProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ResourceLocalizationSpecProto) GetDestinationDirectory() *URLProto {
	if m != nil {
		return m.DestinationDirectory
	}
	return nil
}

type LocalizerHeartbeatResponseProto struct {
	Action           *LocalizerActionProto            `protobuf:"varint,1,opt,name=action,enum=hproto.yarn.LocalizerActionProto" json:"action,omitempty"`
	Resources        []*ResourceLocalizationSpecProto `protobuf:"bytes,2,rep,name=resources" json:"resources,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *LocalizerHeartbeatResponseProto) Reset()         { *m = LocalizerHeartbeatResponseProto{} }
func (m *LocalizerHeartbeatResponseProto) String() string { return proto.CompactTextString(m) }
func (*LocalizerHeartbeatResponseProto) ProtoMessage()    {}
func (*LocalizerHeartbeatResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor17, []int{3}
}

func (m *LocalizerHeartbeatResponseProto) GetAction() LocalizerActionProto {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return LocalizerActionProto_LIVE
}

func (m *LocalizerHeartbeatResponseProto) GetResources() []*ResourceLocalizationSpecProto {
	if m != nil {
		return m.Resources
	}
	return nil
}

func init() {
	proto.RegisterType((*LocalResourceStatusProto)(nil), "hproto.yarn.LocalResourceStatusProto")
	proto.RegisterType((*LocalizerStatusProto)(nil), "hproto.yarn.LocalizerStatusProto")
	proto.RegisterType((*ResourceLocalizationSpecProto)(nil), "hproto.yarn.ResourceLocalizationSpecProto")
	proto.RegisterType((*LocalizerHeartbeatResponseProto)(nil), "hproto.yarn.LocalizerHeartbeatResponseProto")
	proto.RegisterEnum("hproto.yarn.ResourceStatusTypeProto", ResourceStatusTypeProto_name, ResourceStatusTypeProto_value)
	proto.RegisterEnum("hproto.yarn.LocalizerActionProto", LocalizerActionProto_name, LocalizerActionProto_value)
}

func init() {
	proto.RegisterFile("gopkg.in/freddierice/go-hproto.v1/yarn/yarn_server_nodemanager_service_protos.proto", fileDescriptor17)
}

var fileDescriptor17 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x94, 0xc1, 0x8b, 0xd3, 0x40,
	0x14, 0xc6, 0x99, 0x66, 0x5d, 0xb7, 0x53, 0x95, 0x1a, 0x76, 0x31, 0xc8, 0xca, 0xba, 0x41, 0x41,
	0x0b, 0xa6, 0xb8, 0x5e, 0x14, 0xbd, 0xec, 0xb6, 0x59, 0x1b, 0x29, 0xa5, 0x64, 0xb6, 0x82, 0xa7,
	0x30, 0x4e, 0xc6, 0x34, 0x58, 0x33, 0x61, 0x32, 0xbb, 0x58, 0x0f, 0x9e, 0xfd, 0x33, 0x3c, 0x89,
	0x17, 0xff, 0x47, 0x27, 0xaf, 0x49, 0x93, 0xd0, 0xed, 0x41, 0xf0, 0xd2, 0x0e, 0x8f, 0xf7, 0xfb,
	0xbe, 0xc9, 0xf7, 0x1e, 0x83, 0x49, 0x24, 0xd2, 0xcf, 0x91, 0x13, 0x27, 0xfd, 0x4f, 0x92, 0x87,
	0x61, 0xcc, 0x65, 0xcc, 0x78, 0x3f, 0x12, 0xcf, 0xe6, 0xa9, 0x14, 0x4a, 0x38, 0x57, 0xcf, 0xfb,
	0x4b, 0x2a, 0x13, 0xf8, 0x09, 0x32, 0x2e, 0xaf, 0xb8, 0x0c, 0x12, 0x11, 0xf2, 0x2f, 0x34, 0xa1,
	0x91, 0x3e, 0xe7, 0x25, 0x4d, 0x04, 0xd0, 0x9d, 0x39, 0xf0, 0x67, 0x76, 0x0a, 0x38, 0x87, 0xee,
	0xbf, 0xfc, 0x17, 0x87, 0xba, 0x8c, 0xfd, 0xa7, 0x85, 0xad, 0xb1, 0x60, 0x74, 0xe1, 0xf3, 0x4c,
	0x5c, 0x4a, 0xc6, 0x89, 0xa2, 0xea, 0x32, 0x9b, 0x82, 0xc7, 0x6b, 0xbc, 0x27, 0x8b, 0xb2, 0x85,
	0x1e, 0xa2, 0x27, 0x9d, 0x93, 0x23, 0xa7, 0x66, 0xeb, 0x34, 0x40, 0x40, 0xfc, 0x35, 0x60, 0xbe,
	0xc1, 0xbb, 0x19, 0x68, 0x59, 0x2d, 0x8d, 0xde, 0x39, 0x79, 0xd4, 0x40, 0x9b, 0x76, 0x17, 0xcb,
	0xb4, 0xe0, 0x0b, 0xc6, 0x7c, 0x81, 0xdb, 0x8b, 0x5c, 0x7d, 0x4a, 0xd5, 0xdc, 0x32, 0xc0, 0xfb,
	0xa0, 0x21, 0x30, 0xf3, 0xc7, 0x2b, 0xa2, 0xea, 0x33, 0x0f, 0x0b, 0x88, 0xc4, 0xdf, 0xb8, 0xb5,
	0xa3, 0x21, 0xc3, 0xaf, 0x0a, 0xe6, 0x00, 0xb7, 0xf9, 0x57, 0xc6, 0x53, 0x15, 0x8b, 0xc4, 0xba,
	0x01, 0x92, 0x8f, 0x1b, 0x92, 0x44, 0xc7, 0x46, 0x17, 0xba, 0x35, 0x74, 0xcb, 0xbe, 0xc2, 0x62,
	0xcd, 0xd9, 0xdf, 0xf1, 0x3e, 0x7c, 0xb5, 0xee, 0x92, 0xf5, 0xa8, 0x8e, 0xf1, 0xad, 0x45, 0x59,
	0x0f, 0xe2, 0x10, 0xe2, 0x6a, 0xfb, 0x9d, 0x75, 0xcd, 0x0b, 0x73, 0xff, 0x32, 0x9c, 0x3c, 0x13,
	0x63, 0xc3, 0x7f, 0xdb, 0x1c, 0xfc, 0x8a, 0xb3, 0x7f, 0x23, 0xfc, 0xa0, 0x6c, 0x29, 0x2e, 0x42,
	0xf3, 0x8b, 0x91, 0x94, 0xb3, 0xff, 0x30, 0xb4, 0x77, 0xf8, 0x20, 0xe4, 0x99, 0x8a, 0x13, 0x10,
	0x0d, 0xc2, 0x58, 0x72, 0xa6, 0x84, 0x5c, 0xc2, 0x0c, 0xb7, 0x8e, 0x60, 0xbf, 0xc6, 0x0c, 0x4b,
	0xc4, 0xfe, 0x85, 0xf0, 0xd1, 0x3a, 0xab, 0x11, 0xa7, 0x52, 0x7d, 0xe4, 0x54, 0x69, 0xe7, 0x54,
	0x24, 0xd9, 0xca, 0xd9, 0x7c, 0x85, 0x77, 0x29, 0x83, 0x81, 0x20, 0x58, 0x92, 0xe3, 0xcd, 0xab,
	0xe6, 0xf4, 0x29, 0xab, 0x86, 0x51, 0x00, 0xe6, 0x68, 0x33, 0xce, 0xde, 0xb5, 0x2b, 0x76, 0x6d,
	0x4c, 0xb5, 0x4c, 0x7b, 0x3e, 0xbe, 0xb7, 0x65, 0x1d, 0xcd, 0xbb, 0xf8, 0xf6, 0xb9, 0x7b, 0x31,
	0x18, 0x05, 0x53, 0x77, 0x32, 0xf4, 0x26, 0x6f, 0xbb, 0xa8, 0x2a, 0x91, 0xd9, 0x60, 0xe0, 0x12,
	0xd2, 0x6d, 0x55, 0xa5, 0xf3, 0x53, 0x6f, 0x3c, 0xf3, 0xdd, 0xae, 0xd1, 0x7b, 0x5a, 0xdb, 0x93,
	0xda, 0xed, 0xcd, 0x3d, 0xbc, 0x33, 0xf6, 0xde, 0xbb, 0x5a, 0xe7, 0x26, 0x36, 0x86, 0x9e, 0xdb,
	0x6d, 0x9d, 0x8d, 0xf0, 0xa1, 0x90, 0x91, 0x43, 0x53, 0xca, 0xe6, 0xbc, 0xf1, 0x05, 0x70, 0x3c,
	0xb3, 0x3f, 0xe8, 0x33, 0x81, 0x67, 0x61, 0x52, 0xbd, 0x0a, 0x64, 0xf5, 0x28, 0x80, 0x6a, 0xf6,
	0x03, 0xa1, 0x9f, 0x08, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x24, 0x42, 0xb9, 0xc2, 0x69, 0x04,
	0x00, 0x00,
}
