// Code generated by protoc-gen-go.
// source: gopkg.in/freddierice/go-hproto.v1/yarn/yarn_server_resourcemanager_recovery.proto
// DO NOT EDIT!

package hproto_yarn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hproto_common1 "gopkg.in/freddierice/go-hproto.v1/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// //////////////////////////////////////////////////////////////////////
// //// RM recovery related records /////////////////////////////////////
// //////////////////////////////////////////////////////////////////////
type RMAppAttemptStateProto int32

const (
	RMAppAttemptStateProto_RMATTEMPT_NEW                       RMAppAttemptStateProto = 1
	RMAppAttemptStateProto_RMATTEMPT_SUBMITTED                 RMAppAttemptStateProto = 2
	RMAppAttemptStateProto_RMATTEMPT_SCHEDULED                 RMAppAttemptStateProto = 3
	RMAppAttemptStateProto_RMATTEMPT_ALLOCATED                 RMAppAttemptStateProto = 4
	RMAppAttemptStateProto_RMATTEMPT_LAUNCHED                  RMAppAttemptStateProto = 5
	RMAppAttemptStateProto_RMATTEMPT_FAILED                    RMAppAttemptStateProto = 6
	RMAppAttemptStateProto_RMATTEMPT_RUNNING                   RMAppAttemptStateProto = 7
	RMAppAttemptStateProto_RMATTEMPT_FINISHING                 RMAppAttemptStateProto = 8
	RMAppAttemptStateProto_RMATTEMPT_FINISHED                  RMAppAttemptStateProto = 9
	RMAppAttemptStateProto_RMATTEMPT_KILLED                    RMAppAttemptStateProto = 10
	RMAppAttemptStateProto_RMATTEMPT_ALLOCATED_SAVING          RMAppAttemptStateProto = 11
	RMAppAttemptStateProto_RMATTEMPT_LAUNCHED_UNMANAGED_SAVING RMAppAttemptStateProto = 12
	RMAppAttemptStateProto_RMATTEMPT_RECOVERED                 RMAppAttemptStateProto = 13
	RMAppAttemptStateProto_RMATTEMPT_FINAL_SAVING              RMAppAttemptStateProto = 14
)

var RMAppAttemptStateProto_name = map[int32]string{
	1:  "RMATTEMPT_NEW",
	2:  "RMATTEMPT_SUBMITTED",
	3:  "RMATTEMPT_SCHEDULED",
	4:  "RMATTEMPT_ALLOCATED",
	5:  "RMATTEMPT_LAUNCHED",
	6:  "RMATTEMPT_FAILED",
	7:  "RMATTEMPT_RUNNING",
	8:  "RMATTEMPT_FINISHING",
	9:  "RMATTEMPT_FINISHED",
	10: "RMATTEMPT_KILLED",
	11: "RMATTEMPT_ALLOCATED_SAVING",
	12: "RMATTEMPT_LAUNCHED_UNMANAGED_SAVING",
	13: "RMATTEMPT_RECOVERED",
	14: "RMATTEMPT_FINAL_SAVING",
}
var RMAppAttemptStateProto_value = map[string]int32{
	"RMATTEMPT_NEW":                       1,
	"RMATTEMPT_SUBMITTED":                 2,
	"RMATTEMPT_SCHEDULED":                 3,
	"RMATTEMPT_ALLOCATED":                 4,
	"RMATTEMPT_LAUNCHED":                  5,
	"RMATTEMPT_FAILED":                    6,
	"RMATTEMPT_RUNNING":                   7,
	"RMATTEMPT_FINISHING":                 8,
	"RMATTEMPT_FINISHED":                  9,
	"RMATTEMPT_KILLED":                    10,
	"RMATTEMPT_ALLOCATED_SAVING":          11,
	"RMATTEMPT_LAUNCHED_UNMANAGED_SAVING": 12,
	"RMATTEMPT_RECOVERED":                 13,
	"RMATTEMPT_FINAL_SAVING":              14,
}

func (x RMAppAttemptStateProto) Enum() *RMAppAttemptStateProto {
	p := new(RMAppAttemptStateProto)
	*p = x
	return p
}
func (x RMAppAttemptStateProto) String() string {
	return proto.EnumName(RMAppAttemptStateProto_name, int32(x))
}
func (x *RMAppAttemptStateProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RMAppAttemptStateProto_value, data, "RMAppAttemptStateProto")
	if err != nil {
		return err
	}
	*x = RMAppAttemptStateProto(value)
	return nil
}
func (RMAppAttemptStateProto) EnumDescriptor() ([]byte, []int) { return fileDescriptor18, []int{0} }

type RMAppStateProto int32

const (
	RMAppStateProto_RMAPP_NEW          RMAppStateProto = 1
	RMAppStateProto_RMAPP_NEW_SAVING   RMAppStateProto = 2
	RMAppStateProto_RMAPP_SUBMITTED    RMAppStateProto = 3
	RMAppStateProto_RMAPP_ACCEPTED     RMAppStateProto = 4
	RMAppStateProto_RMAPP_RUNNING      RMAppStateProto = 5
	RMAppStateProto_RMAPP_FINAL_SAVING RMAppStateProto = 6
	RMAppStateProto_RMAPP_FINISHING    RMAppStateProto = 7
	RMAppStateProto_RMAPP_FINISHED     RMAppStateProto = 8
	RMAppStateProto_RMAPP_FAILED       RMAppStateProto = 9
	RMAppStateProto_RMAPP_KILLED       RMAppStateProto = 10
)

var RMAppStateProto_name = map[int32]string{
	1:  "RMAPP_NEW",
	2:  "RMAPP_NEW_SAVING",
	3:  "RMAPP_SUBMITTED",
	4:  "RMAPP_ACCEPTED",
	5:  "RMAPP_RUNNING",
	6:  "RMAPP_FINAL_SAVING",
	7:  "RMAPP_FINISHING",
	8:  "RMAPP_FINISHED",
	9:  "RMAPP_FAILED",
	10: "RMAPP_KILLED",
}
var RMAppStateProto_value = map[string]int32{
	"RMAPP_NEW":          1,
	"RMAPP_NEW_SAVING":   2,
	"RMAPP_SUBMITTED":    3,
	"RMAPP_ACCEPTED":     4,
	"RMAPP_RUNNING":      5,
	"RMAPP_FINAL_SAVING": 6,
	"RMAPP_FINISHING":    7,
	"RMAPP_FINISHED":     8,
	"RMAPP_FAILED":       9,
	"RMAPP_KILLED":       10,
}

func (x RMAppStateProto) Enum() *RMAppStateProto {
	p := new(RMAppStateProto)
	*p = x
	return p
}
func (x RMAppStateProto) String() string {
	return proto.EnumName(RMAppStateProto_name, int32(x))
}
func (x *RMAppStateProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RMAppStateProto_value, data, "RMAppStateProto")
	if err != nil {
		return err
	}
	*x = RMAppStateProto(value)
	return nil
}
func (RMAppStateProto) EnumDescriptor() ([]byte, []int) { return fileDescriptor18, []int{1} }

type ApplicationStateDataProto struct {
	SubmitTime                   *int64                                `protobuf:"varint,1,opt,name=submit_time,json=submitTime" json:"submit_time,omitempty"`
	ApplicationSubmissionContext *ApplicationSubmissionContextProto    `protobuf:"bytes,2,opt,name=application_submission_context,json=applicationSubmissionContext" json:"application_submission_context,omitempty"`
	User                         *string                               `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	StartTime                    *int64                                `protobuf:"varint,4,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	ApplicationState             *RMAppStateProto                      `protobuf:"varint,5,opt,name=application_state,json=applicationState,enum=hproto.yarn.RMAppStateProto" json:"application_state,omitempty"`
	Diagnostics                  *string                               `protobuf:"bytes,6,opt,name=diagnostics,def=N/A" json:"diagnostics,omitempty"`
	FinishTime                   *int64                                `protobuf:"varint,7,opt,name=finish_time,json=finishTime" json:"finish_time,omitempty"`
	CallerContext                *hproto_common1.RPCCallerContextProto `protobuf:"bytes,8,opt,name=caller_context,json=callerContext" json:"caller_context,omitempty"`
	XXX_unrecognized             []byte                                `json:"-"`
}

func (m *ApplicationStateDataProto) Reset()                    { *m = ApplicationStateDataProto{} }
func (m *ApplicationStateDataProto) String() string            { return proto.CompactTextString(m) }
func (*ApplicationStateDataProto) ProtoMessage()               {}
func (*ApplicationStateDataProto) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{0} }

const Default_ApplicationStateDataProto_Diagnostics string = "N/A"

func (m *ApplicationStateDataProto) GetSubmitTime() int64 {
	if m != nil && m.SubmitTime != nil {
		return *m.SubmitTime
	}
	return 0
}

func (m *ApplicationStateDataProto) GetApplicationSubmissionContext() *ApplicationSubmissionContextProto {
	if m != nil {
		return m.ApplicationSubmissionContext
	}
	return nil
}

func (m *ApplicationStateDataProto) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *ApplicationStateDataProto) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *ApplicationStateDataProto) GetApplicationState() RMAppStateProto {
	if m != nil && m.ApplicationState != nil {
		return *m.ApplicationState
	}
	return RMAppStateProto_RMAPP_NEW
}

func (m *ApplicationStateDataProto) GetDiagnostics() string {
	if m != nil && m.Diagnostics != nil {
		return *m.Diagnostics
	}
	return Default_ApplicationStateDataProto_Diagnostics
}

func (m *ApplicationStateDataProto) GetFinishTime() int64 {
	if m != nil && m.FinishTime != nil {
		return *m.FinishTime
	}
	return 0
}

func (m *ApplicationStateDataProto) GetCallerContext() *hproto_common1.RPCCallerContextProto {
	if m != nil {
		return m.CallerContext
	}
	return nil
}

type ApplicationAttemptStateDataProto struct {
	AttemptId              *ApplicationAttemptIdProto   `protobuf:"bytes,1,opt,name=attemptId" json:"attemptId,omitempty"`
	MasterContainer        *ContainerProto              `protobuf:"bytes,2,opt,name=master_container,json=masterContainer" json:"master_container,omitempty"`
	AppAttemptTokens       []byte                       `protobuf:"bytes,3,opt,name=app_attempt_tokens,json=appAttemptTokens" json:"app_attempt_tokens,omitempty"`
	AppAttemptState        *RMAppAttemptStateProto      `protobuf:"varint,4,opt,name=app_attempt_state,json=appAttemptState,enum=hproto.yarn.RMAppAttemptStateProto" json:"app_attempt_state,omitempty"`
	FinalTrackingUrl       *string                      `protobuf:"bytes,5,opt,name=final_tracking_url,json=finalTrackingUrl" json:"final_tracking_url,omitempty"`
	Diagnostics            *string                      `protobuf:"bytes,6,opt,name=diagnostics,def=N/A" json:"diagnostics,omitempty"`
	StartTime              *int64                       `protobuf:"varint,7,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	FinalApplicationStatus *FinalApplicationStatusProto `protobuf:"varint,8,opt,name=final_application_status,json=finalApplicationStatus,enum=hproto.yarn.FinalApplicationStatusProto" json:"final_application_status,omitempty"`
	AmContainerExitStatus  *int32                       `protobuf:"varint,9,opt,name=am_container_exit_status,json=amContainerExitStatus,def=-1000" json:"am_container_exit_status,omitempty"`
	MemorySeconds          *int64                       `protobuf:"varint,10,opt,name=memory_seconds,json=memorySeconds" json:"memory_seconds,omitempty"`
	VcoreSeconds           *int64                       `protobuf:"varint,11,opt,name=vcore_seconds,json=vcoreSeconds" json:"vcore_seconds,omitempty"`
	FinishTime             *int64                       `protobuf:"varint,12,opt,name=finish_time,json=finishTime" json:"finish_time,omitempty"`
	XXX_unrecognized       []byte                       `json:"-"`
}

func (m *ApplicationAttemptStateDataProto) Reset()         { *m = ApplicationAttemptStateDataProto{} }
func (m *ApplicationAttemptStateDataProto) String() string { return proto.CompactTextString(m) }
func (*ApplicationAttemptStateDataProto) ProtoMessage()    {}
func (*ApplicationAttemptStateDataProto) Descriptor() ([]byte, []int) {
	return fileDescriptor18, []int{1}
}

const Default_ApplicationAttemptStateDataProto_Diagnostics string = "N/A"
const Default_ApplicationAttemptStateDataProto_AmContainerExitStatus int32 = -1000

func (m *ApplicationAttemptStateDataProto) GetAttemptId() *ApplicationAttemptIdProto {
	if m != nil {
		return m.AttemptId
	}
	return nil
}

func (m *ApplicationAttemptStateDataProto) GetMasterContainer() *ContainerProto {
	if m != nil {
		return m.MasterContainer
	}
	return nil
}

func (m *ApplicationAttemptStateDataProto) GetAppAttemptTokens() []byte {
	if m != nil {
		return m.AppAttemptTokens
	}
	return nil
}

func (m *ApplicationAttemptStateDataProto) GetAppAttemptState() RMAppAttemptStateProto {
	if m != nil && m.AppAttemptState != nil {
		return *m.AppAttemptState
	}
	return RMAppAttemptStateProto_RMATTEMPT_NEW
}

func (m *ApplicationAttemptStateDataProto) GetFinalTrackingUrl() string {
	if m != nil && m.FinalTrackingUrl != nil {
		return *m.FinalTrackingUrl
	}
	return ""
}

func (m *ApplicationAttemptStateDataProto) GetDiagnostics() string {
	if m != nil && m.Diagnostics != nil {
		return *m.Diagnostics
	}
	return Default_ApplicationAttemptStateDataProto_Diagnostics
}

func (m *ApplicationAttemptStateDataProto) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *ApplicationAttemptStateDataProto) GetFinalApplicationStatus() FinalApplicationStatusProto {
	if m != nil && m.FinalApplicationStatus != nil {
		return *m.FinalApplicationStatus
	}
	return FinalApplicationStatusProto_APP_UNDEFINED
}

func (m *ApplicationAttemptStateDataProto) GetAmContainerExitStatus() int32 {
	if m != nil && m.AmContainerExitStatus != nil {
		return *m.AmContainerExitStatus
	}
	return Default_ApplicationAttemptStateDataProto_AmContainerExitStatus
}

func (m *ApplicationAttemptStateDataProto) GetMemorySeconds() int64 {
	if m != nil && m.MemorySeconds != nil {
		return *m.MemorySeconds
	}
	return 0
}

func (m *ApplicationAttemptStateDataProto) GetVcoreSeconds() int64 {
	if m != nil && m.VcoreSeconds != nil {
		return *m.VcoreSeconds
	}
	return 0
}

func (m *ApplicationAttemptStateDataProto) GetFinishTime() int64 {
	if m != nil && m.FinishTime != nil {
		return *m.FinishTime
	}
	return 0
}

type EpochProto struct {
	Epoch            *int64 `protobuf:"varint,1,opt,name=epoch" json:"epoch,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EpochProto) Reset()                    { *m = EpochProto{} }
func (m *EpochProto) String() string            { return proto.CompactTextString(m) }
func (*EpochProto) ProtoMessage()               {}
func (*EpochProto) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{2} }

func (m *EpochProto) GetEpoch() int64 {
	if m != nil && m.Epoch != nil {
		return *m.Epoch
	}
	return 0
}

type AMRMTokenSecretManagerStateProto struct {
	CurrentMasterKey *MasterKeyProto `protobuf:"bytes,1,opt,name=current_master_key,json=currentMasterKey" json:"current_master_key,omitempty"`
	NextMasterKey    *MasterKeyProto `protobuf:"bytes,2,opt,name=next_master_key,json=nextMasterKey" json:"next_master_key,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *AMRMTokenSecretManagerStateProto) Reset()         { *m = AMRMTokenSecretManagerStateProto{} }
func (m *AMRMTokenSecretManagerStateProto) String() string { return proto.CompactTextString(m) }
func (*AMRMTokenSecretManagerStateProto) ProtoMessage()    {}
func (*AMRMTokenSecretManagerStateProto) Descriptor() ([]byte, []int) {
	return fileDescriptor18, []int{3}
}

func (m *AMRMTokenSecretManagerStateProto) GetCurrentMasterKey() *MasterKeyProto {
	if m != nil {
		return m.CurrentMasterKey
	}
	return nil
}

func (m *AMRMTokenSecretManagerStateProto) GetNextMasterKey() *MasterKeyProto {
	if m != nil {
		return m.NextMasterKey
	}
	return nil
}

type RMDelegationTokenIdentifierDataProto struct {
	TokenIdentifier  *YARNDelegationTokenIdentifierProto `protobuf:"bytes,1,opt,name=token_identifier,json=tokenIdentifier" json:"token_identifier,omitempty"`
	RenewDate        *int64                              `protobuf:"varint,2,opt,name=renewDate" json:"renewDate,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *RMDelegationTokenIdentifierDataProto) Reset()         { *m = RMDelegationTokenIdentifierDataProto{} }
func (m *RMDelegationTokenIdentifierDataProto) String() string { return proto.CompactTextString(m) }
func (*RMDelegationTokenIdentifierDataProto) ProtoMessage()    {}
func (*RMDelegationTokenIdentifierDataProto) Descriptor() ([]byte, []int) {
	return fileDescriptor18, []int{4}
}

func (m *RMDelegationTokenIdentifierDataProto) GetTokenIdentifier() *YARNDelegationTokenIdentifierProto {
	if m != nil {
		return m.TokenIdentifier
	}
	return nil
}

func (m *RMDelegationTokenIdentifierDataProto) GetRenewDate() int64 {
	if m != nil && m.RenewDate != nil {
		return *m.RenewDate
	}
	return 0
}

func init() {
	proto.RegisterType((*ApplicationStateDataProto)(nil), "hproto.yarn.ApplicationStateDataProto")
	proto.RegisterType((*ApplicationAttemptStateDataProto)(nil), "hproto.yarn.ApplicationAttemptStateDataProto")
	proto.RegisterType((*EpochProto)(nil), "hproto.yarn.EpochProto")
	proto.RegisterType((*AMRMTokenSecretManagerStateProto)(nil), "hproto.yarn.AMRMTokenSecretManagerStateProto")
	proto.RegisterType((*RMDelegationTokenIdentifierDataProto)(nil), "hproto.yarn.RMDelegationTokenIdentifierDataProto")
	proto.RegisterEnum("hproto.yarn.RMAppAttemptStateProto", RMAppAttemptStateProto_name, RMAppAttemptStateProto_value)
	proto.RegisterEnum("hproto.yarn.RMAppStateProto", RMAppStateProto_name, RMAppStateProto_value)
}

func init() {
	proto.RegisterFile("gopkg.in/freddierice/go-hproto.v1/yarn/yarn_server_resourcemanager_recovery.proto", fileDescriptor18)
}

var fileDescriptor18 = []byte{
	// 1063 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x56, 0xdf, 0x72, 0xda, 0xc6,
	0x1b, 0x1d, 0x19, 0x63, 0x9b, 0x0f, 0x83, 0xe5, 0xcd, 0x2f, 0xfe, 0x51, 0xd7, 0x4d, 0x33, 0x38,
	0x69, 0x32, 0x99, 0x06, 0x1c, 0x5f, 0x75, 0x72, 0xd1, 0xa9, 0x2c, 0x20, 0x66, 0x8c, 0x64, 0x2a,
	0x20, 0x9d, 0xf4, 0x46, 0xb3, 0x11, 0x6b, 0xac, 0x31, 0x92, 0x98, 0xd5, 0xe2, 0x86, 0xbb, 0x5e,
	0xf6, 0x31, 0xf2, 0x0c, 0x9d, 0xbe, 0x42, 0x9f, 0xa1, 0xaf, 0xd3, 0xd5, 0xee, 0x22, 0x21, 0xe2,
	0xb4, 0x49, 0x6f, 0x3c, 0xd2, 0xf9, 0xfe, 0x9d, 0x3d, 0xe7, 0x5b, 0x19, 0xf8, 0x71, 0x12, 0xcd,
	0x6e, 0x26, 0x0d, 0x3f, 0x6c, 0x5e, 0x51, 0x32, 0x1e, 0xfb, 0x84, 0xfa, 0x1e, 0x69, 0x4e, 0xa2,
	0xe7, 0xd7, 0x33, 0x1a, 0xb1, 0xa8, 0x71, 0xfb, 0xa2, 0xb9, 0xc0, 0x34, 0x14, 0x7f, 0xdc, 0x98,
	0xd0, 0x5b, 0x42, 0x5d, 0x4a, 0xe2, 0x68, 0x4e, 0x3d, 0x12, 0xe0, 0x10, 0x4f, 0xc4, 0xbb, 0x17,
	0x71, 0x7c, 0xd1, 0x10, 0x25, 0xa8, 0xac, 0x4a, 0x93, 0x92, 0xc3, 0xce, 0x7f, 0xe8, 0xef, 0x45,
	0x41, 0x10, 0x85, 0xae, 0x48, 0x88, 0x65, 0xd3, 0xc3, 0xef, 0x3e, 0xa7, 0x4f, 0xae, 0xf2, 0x87,
	0xcf, 0x63, 0xe0, 0xcd, 0xa9, 0xcf, 0x16, 0x2e, 0x8b, 0x6e, 0x48, 0xf8, 0xe9, 0xb3, 0x25, 0xe5,
	0xa6, 0x33, 0xf3, 0xce, 0x09, 0x1e, 0x13, 0x2a, 0x2b, 0xeb, 0x7f, 0x16, 0xe0, 0x0b, 0x63, 0x36,
	0x9b, 0xfa, 0x1e, 0x66, 0x7e, 0x14, 0x0e, 0x18, 0x66, 0xa4, 0x85, 0x19, 0xee, 0x0b, 0xa1, 0xbe,
	0x86, 0x72, 0x3c, 0x7f, 0x1b, 0xf8, 0xcc, 0x65, 0x7e, 0x40, 0x6a, 0xda, 0x43, 0xed, 0x69, 0xc1,
	0x01, 0x09, 0x0d, 0x39, 0x82, 0x18, 0x3c, 0xc0, 0x59, 0xb5, 0x2b, 0x22, 0x71, 0x9c, 0x3c, 0x7a,
	0x51, 0xc8, 0xc8, 0x3b, 0x56, 0xdb, 0xe0, 0x35, 0xe5, 0xd3, 0x46, 0x63, 0x45, 0xf2, 0xc6, 0xea,
	0xc0, 0xb4, 0xc2, 0x94, 0x05, 0x62, 0xb0, 0x73, 0x84, 0xff, 0x21, 0x05, 0x21, 0xd8, 0x9c, 0x73,
	0x27, 0x6a, 0x05, 0xde, 0xbb, 0xe4, 0x88, 0x67, 0xf4, 0x15, 0x40, 0xcc, 0x30, 0x55, 0x4c, 0x37,
	0x05, 0xd3, 0x92, 0x40, 0x04, 0xd1, 0x2e, 0xec, 0xe7, 0x88, 0x26, 0xe7, 0xac, 0x15, 0x79, 0x56,
	0xf5, 0xf4, 0x28, 0xc7, 0xcd, 0xb1, 0x38, 0x3b, 0x21, 0x83, 0x64, 0xa2, 0xe3, 0x35, 0x75, 0xd0,
	0x63, 0x28, 0x8f, 0x7d, 0x3c, 0x09, 0xa3, 0x98, 0xf9, 0x5e, 0x5c, 0xdb, 0x4a, 0x48, 0xbc, 0x2c,
	0xd8, 0x4d, 0xc3, 0x59, 0xc5, 0x13, 0xed, 0xae, 0xfc, 0xd0, 0x8f, 0xaf, 0x25, 0xa3, 0x6d, 0xa9,
	0x9d, 0x84, 0x04, 0xa5, 0x0b, 0xa8, 0x7a, 0x78, 0x3a, 0x15, 0xeb, 0x24, 0xb5, 0xda, 0x11, 0x5a,
	0x3d, 0x5a, 0xf2, 0x91, 0x96, 0x35, 0x9c, 0xbe, 0x69, 0x8a, 0xbc, 0x9c, 0x42, 0x15, 0x6f, 0x15,
	0xab, 0xff, 0x51, 0x84, 0x87, 0x2b, 0xb2, 0x1a, 0x8c, 0x91, 0x60, 0xc6, 0xd6, 0xec, 0x6c, 0x41,
	0x09, 0xcb, 0x40, 0x77, 0x2c, 0xcc, 0x2c, 0x9f, 0x7e, 0xf3, 0x31, 0x63, 0x8c, 0x65, 0xa2, 0x1c,
	0x97, 0x15, 0xa2, 0x0e, 0xe8, 0x01, 0x8e, 0x99, 0xe2, 0x8d, 0xfd, 0x90, 0x3b, 0x21, 0x5d, 0xfe,
	0x32, 0xd7, 0xcc, 0x5c, 0x46, 0x65, 0x87, 0x3d, 0x59, 0x94, 0xa2, 0xe8, 0x5b, 0x40, 0x5c, 0x5b,
	0x57, 0x35, 0x96, 0xfb, 0x1c, 0x0b, 0x4f, 0x77, 0x85, 0xea, 0x8a, 0xc1, 0x50, 0xe0, 0xe8, 0x52,
	0x18, 0x98, 0x66, 0x4b, 0x03, 0x37, 0x85, 0x81, 0xc7, 0x1f, 0x1a, 0xb8, 0x7a, 0x7e, 0x35, 0x1e,
	0xe7, 0xd1, 0x64, 0x3c, 0x37, 0x03, 0x4f, 0x5d, 0x46, 0xb1, 0x77, 0xe3, 0x87, 0x13, 0x77, 0x4e,
	0xa7, 0x62, 0x25, 0x4a, 0x8e, 0x2e, 0x22, 0x43, 0x15, 0x18, 0xd1, 0xe9, 0xa7, 0x9a, 0x9e, 0xdf,
	0xc2, 0xed, 0xf5, 0x2d, 0x7c, 0x0b, 0x35, 0x39, 0x73, 0x7d, 0x17, 0xe7, 0xb1, 0x30, 0xbf, 0x7a,
	0xfa, 0x34, 0x77, 0x96, 0x4e, 0x92, 0xbc, 0x76, 0x3d, 0xe7, 0xb1, 0x3c, 0xd0, 0xc1, 0xd5, 0x9d,
	0x41, 0xf4, 0x3d, 0xd4, 0x70, 0x90, 0x59, 0xe3, 0x92, 0x77, 0x3e, 0x5b, 0xce, 0x28, 0xf1, 0x19,
	0xc5, 0x97, 0xc5, 0xe7, 0x2f, 0x4e, 0x4e, 0x4e, 0x9c, 0xfb, 0x38, 0x48, 0xcd, 0x68, 0xf3, 0x24,
	0x55, 0xff, 0x18, 0xaa, 0x01, 0x09, 0x22, 0xba, 0x48, 0x3e, 0x35, 0x51, 0x38, 0x8e, 0x6b, 0x20,
	0x8e, 0x51, 0x91, 0xe8, 0x40, 0x82, 0xe8, 0x18, 0x2a, 0xb7, 0x5e, 0x44, 0x49, 0x9a, 0x55, 0x16,
	0x59, 0xbb, 0x02, 0x5c, 0x26, 0xad, 0xdd, 0x81, 0xdd, 0xf5, 0x3b, 0x50, 0xaf, 0x03, 0xb4, 0x67,
	0x91, 0x77, 0x2d, 0xf7, 0xf3, 0x7f, 0x50, 0x24, 0xc9, 0x9b, 0xfa, 0xd0, 0xc8, 0x97, 0xfa, 0xef,
	0x1a, 0x5f, 0x6d, 0xcb, 0xb1, 0xc4, 0x22, 0xf0, 0xce, 0x94, 0x30, 0x4b, 0x7e, 0xd7, 0x33, 0x7b,
	0xf9, 0xfd, 0x46, 0xfc, 0xbb, 0x48, 0x49, 0xc8, 0x5c, 0xb5, 0x9c, 0x37, 0x64, 0xa1, 0x76, 0x3c,
	0xbf, 0x96, 0x96, 0x08, 0x5f, 0x90, 0x85, 0xba, 0xdf, 0xaa, 0x2c, 0x85, 0x91, 0x09, 0x7b, 0x21,
	0xbf, 0x52, 0xab, 0x7d, 0x36, 0xfe, 0xbd, 0x4f, 0x25, 0xa9, 0x49, 0xb1, 0xfa, 0x7b, 0x0d, 0x1e,
	0x39, 0x56, 0x8b, 0x4c, 0xc9, 0x44, 0x98, 0x23, 0xc8, 0x77, 0xc7, 0x7c, 0x90, 0x7f, 0xc5, 0x3f,
	0xcf, 0xd9, 0x9d, 0xfc, 0x19, 0x74, 0xb1, 0xf9, 0xae, 0x9f, 0x06, 0x15, 0xed, 0x66, 0x6e, 0xdc,
	0x1b, 0xc3, 0xb1, 0x3f, 0xda, 0x4e, 0xad, 0x38, 0xcb, 0xa3, 0xe8, 0x08, 0x4a, 0xfc, 0x68, 0xe4,
	0x97, 0x56, 0x72, 0x57, 0x36, 0xe4, 0x32, 0xa6, 0xc0, 0xb3, 0x5f, 0x0b, 0x70, 0x70, 0xf7, 0x65,
	0x41, 0xfb, 0x50, 0xe1, 0x91, 0xe1, 0xb0, 0x6d, 0xf5, 0x87, 0xae, 0xdd, 0xfe, 0x49, 0xd7, 0xd0,
	0xff, 0xe1, 0x5e, 0x06, 0x0d, 0x46, 0x67, 0x56, 0x97, 0x3f, 0xb7, 0xf4, 0x8d, 0xb5, 0x80, 0x79,
	0xde, 0x6e, 0x8d, 0x7a, 0x3c, 0x50, 0xc8, 0x07, 0x8c, 0x5e, 0xef, 0xd2, 0x34, 0x92, 0x8a, 0x4d,
	0x74, 0x00, 0x28, 0x0b, 0xf4, 0x8c, 0x91, 0x9d, 0x14, 0xe9, 0x45, 0x6e, 0xbf, 0x9e, 0xe1, 0x1d,
	0xa3, 0x9b, 0xb4, 0xd9, 0x42, 0xf7, 0x61, 0x3f, 0x43, 0x9d, 0x91, 0x6d, 0x77, 0xed, 0x57, 0xfa,
	0x76, 0xbe, 0x7b, 0xa7, 0x6b, 0x77, 0x07, 0xe7, 0x49, 0x60, 0x27, 0xdf, 0x5d, 0x06, 0x78, 0x9f,
	0x52, 0xbe, 0xfb, 0x45, 0xb7, 0x97, 0x74, 0x07, 0xf4, 0x00, 0x0e, 0xef, 0x20, 0xe9, 0x0e, 0x8c,
	0xd7, 0x49, 0xb7, 0x32, 0x7a, 0x02, 0xc7, 0x1f, 0x72, 0x75, 0x47, 0xb6, 0x65, 0xd8, 0xc6, 0xab,
	0x2c, 0x71, 0x37, 0xcf, 0xc7, 0x69, 0x9b, 0x97, 0xaf, 0xdb, 0x0e, 0x9f, 0x50, 0x41, 0x87, 0x42,
	0xe5, 0x8c, 0x8f, 0xd1, 0x5b, 0x16, 0x55, 0x9f, 0xfd, 0xa5, 0xc1, 0xde, 0xda, 0x3f, 0x1c, 0x54,
	0x81, 0x12, 0x87, 0xfa, 0x7d, 0xa5, 0xbb, 0xa4, 0x2d, 0x5f, 0x97, 0x85, 0x1b, 0xe8, 0x9e, 0xa8,
	0xe3, 0x68, 0xe6, 0x44, 0x81, 0xff, 0x5b, 0xac, 0x4a, 0xd0, 0x30, 0xcd, 0x76, 0x5f, 0x6a, 0x2d,
	0x9d, 0xe4, 0xd8, 0x52, 0xb9, 0xa2, 0x12, 0x88, 0x43, 0x39, 0x32, 0x5b, 0x59, 0xcf, 0x4c, 0xcd,
	0xed, 0xac, 0x67, 0xaa, 0xe4, 0x0e, 0xd2, 0x61, 0x57, 0x61, 0xd2, 0xa3, 0x52, 0x86, 0x2c, 0x75,
	0x3d, 0xb3, 0xe0, 0x28, 0xa2, 0x93, 0x06, 0x9e, 0x61, 0xef, 0x9a, 0xe4, 0x16, 0x59, 0x3c, 0x9e,
	0x3d, 0x79, 0xc3, 0x9f, 0x07, 0xe2, 0xd7, 0x94, 0xa3, 0x7e, 0xac, 0xa9, 0x4b, 0xed, 0xa8, 0xdf,
	0x6a, 0x42, 0x8d, 0xf8, 0x37, 0x4d, 0x7b, 0xaf, 0x69, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd0,
	0x1c, 0x0a, 0xf9, 0x05, 0x0a, 0x00, 0x00,
}
