// Code generated by protoc-gen-go.
// source: gopkg.in/freddierice/go-hproto.v1/mapreduce/HSAdminRefreshProtocol.proto
// DO NOT EDIT!

/*
Package hproto_mapreduce is a generated protocol buffer package.

It is generated from these files:
	gopkg.in/freddierice/go-hproto.v1/mapreduce/HSAdminRefreshProtocol.proto
	gopkg.in/freddierice/go-hproto.v1/mapreduce/MRClientProtocol.proto
	gopkg.in/freddierice/go-hproto.v1/mapreduce/mr_protos.proto
	gopkg.in/freddierice/go-hproto.v1/mapreduce/mr_service_protos.proto
	gopkg.in/freddierice/go-hproto.v1/mapreduce/ShuffleHandlerRecovery.proto

It has these top-level messages:
	RefreshAdminAclsRequestProto
	RefreshAdminAclsResponseProto
	RefreshLoadedJobCacheRequestProto
	RefreshLoadedJobCacheResponseProto
	RefreshJobRetentionSettingsRequestProto
	RefreshJobRetentionSettingsResponseProto
	RefreshLogRetentionSettingsRequestProto
	RefreshLogRetentionSettingsResponseProto
	JobIdProto
	TaskIdProto
	TaskAttemptIdProto
	CounterProto
	CounterGroupProto
	CountersProto
	TaskReportProto
	TaskAttemptReportProto
	JobReportProto
	AMInfoProto
	TaskAttemptCompletionEventProto
	StringCounterMapProto
	StringCounterGroupMapProto
	GetJobReportRequestProto
	GetJobReportResponseProto
	GetTaskReportRequestProto
	GetTaskReportResponseProto
	GetTaskAttemptReportRequestProto
	GetTaskAttemptReportResponseProto
	GetCountersRequestProto
	GetCountersResponseProto
	GetTaskAttemptCompletionEventsRequestProto
	GetTaskAttemptCompletionEventsResponseProto
	GetTaskReportsRequestProto
	GetTaskReportsResponseProto
	GetDiagnosticsRequestProto
	GetDiagnosticsResponseProto
	KillJobRequestProto
	KillJobResponseProto
	KillTaskRequestProto
	KillTaskResponseProto
	KillTaskAttemptRequestProto
	KillTaskAttemptResponseProto
	FailTaskAttemptRequestProto
	FailTaskAttemptResponseProto
	JobShuffleInfoProto
*/
package hproto_mapreduce

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//  refresh admin acls request.
type RefreshAdminAclsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshAdminAclsRequestProto) Reset()                    { *m = RefreshAdminAclsRequestProto{} }
func (m *RefreshAdminAclsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshAdminAclsRequestProto) ProtoMessage()               {}
func (*RefreshAdminAclsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// *
// Response for refresh admin acls.
type RefreshAdminAclsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshAdminAclsResponseProto) Reset()                    { *m = RefreshAdminAclsResponseProto{} }
func (m *RefreshAdminAclsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshAdminAclsResponseProto) ProtoMessage()               {}
func (*RefreshAdminAclsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// *
//  refresh loaded job cache request.
type RefreshLoadedJobCacheRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshLoadedJobCacheRequestProto) Reset()         { *m = RefreshLoadedJobCacheRequestProto{} }
func (m *RefreshLoadedJobCacheRequestProto) String() string { return proto.CompactTextString(m) }
func (*RefreshLoadedJobCacheRequestProto) ProtoMessage()    {}
func (*RefreshLoadedJobCacheRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2}
}

// *
// Response for refresh loaded job cache.
type RefreshLoadedJobCacheResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshLoadedJobCacheResponseProto) Reset()         { *m = RefreshLoadedJobCacheResponseProto{} }
func (m *RefreshLoadedJobCacheResponseProto) String() string { return proto.CompactTextString(m) }
func (*RefreshLoadedJobCacheResponseProto) ProtoMessage()    {}
func (*RefreshLoadedJobCacheResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3}
}

// *
//  refresh job retention settings request.
type RefreshJobRetentionSettingsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshJobRetentionSettingsRequestProto) Reset() {
	*m = RefreshJobRetentionSettingsRequestProto{}
}
func (m *RefreshJobRetentionSettingsRequestProto) String() string { return proto.CompactTextString(m) }
func (*RefreshJobRetentionSettingsRequestProto) ProtoMessage()    {}
func (*RefreshJobRetentionSettingsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4}
}

// *
// Response for refresh job retention.
type RefreshJobRetentionSettingsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshJobRetentionSettingsResponseProto) Reset() {
	*m = RefreshJobRetentionSettingsResponseProto{}
}
func (m *RefreshJobRetentionSettingsResponseProto) String() string { return proto.CompactTextString(m) }
func (*RefreshJobRetentionSettingsResponseProto) ProtoMessage()    {}
func (*RefreshJobRetentionSettingsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

//
//  refresh log retention request.
type RefreshLogRetentionSettingsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshLogRetentionSettingsRequestProto) Reset() {
	*m = RefreshLogRetentionSettingsRequestProto{}
}
func (m *RefreshLogRetentionSettingsRequestProto) String() string { return proto.CompactTextString(m) }
func (*RefreshLogRetentionSettingsRequestProto) ProtoMessage()    {}
func (*RefreshLogRetentionSettingsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6}
}

// *
// Response for refresh log retention.
type RefreshLogRetentionSettingsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshLogRetentionSettingsResponseProto) Reset() {
	*m = RefreshLogRetentionSettingsResponseProto{}
}
func (m *RefreshLogRetentionSettingsResponseProto) String() string { return proto.CompactTextString(m) }
func (*RefreshLogRetentionSettingsResponseProto) ProtoMessage()    {}
func (*RefreshLogRetentionSettingsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7}
}

func init() {
	proto.RegisterType((*RefreshAdminAclsRequestProto)(nil), "hproto.mapreduce.RefreshAdminAclsRequestProto")
	proto.RegisterType((*RefreshAdminAclsResponseProto)(nil), "hproto.mapreduce.RefreshAdminAclsResponseProto")
	proto.RegisterType((*RefreshLoadedJobCacheRequestProto)(nil), "hproto.mapreduce.RefreshLoadedJobCacheRequestProto")
	proto.RegisterType((*RefreshLoadedJobCacheResponseProto)(nil), "hproto.mapreduce.RefreshLoadedJobCacheResponseProto")
	proto.RegisterType((*RefreshJobRetentionSettingsRequestProto)(nil), "hproto.mapreduce.RefreshJobRetentionSettingsRequestProto")
	proto.RegisterType((*RefreshJobRetentionSettingsResponseProto)(nil), "hproto.mapreduce.RefreshJobRetentionSettingsResponseProto")
	proto.RegisterType((*RefreshLogRetentionSettingsRequestProto)(nil), "hproto.mapreduce.RefreshLogRetentionSettingsRequestProto")
	proto.RegisterType((*RefreshLogRetentionSettingsResponseProto)(nil), "hproto.mapreduce.RefreshLogRetentionSettingsResponseProto")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for HSAdminRefreshProtocolService service

type HSAdminRefreshProtocolServiceClient interface {
	// *
	// Refresh admin acls
	RefreshAdminAcls(ctx context.Context, in *RefreshAdminAclsRequestProto, opts ...grpc.CallOption) (*RefreshAdminAclsResponseProto, error)
	// *
	// Refresh loaded job cache
	RefreshLoadedJobCache(ctx context.Context, in *RefreshLoadedJobCacheRequestProto, opts ...grpc.CallOption) (*RefreshLoadedJobCacheResponseProto, error)
	// *
	// Refresh job retention.
	RefreshJobRetentionSettings(ctx context.Context, in *RefreshJobRetentionSettingsRequestProto, opts ...grpc.CallOption) (*RefreshJobRetentionSettingsResponseProto, error)
	// *
	// Refresh log retention
	RefreshLogRetentionSettings(ctx context.Context, in *RefreshLogRetentionSettingsRequestProto, opts ...grpc.CallOption) (*RefreshLogRetentionSettingsResponseProto, error)
}

type hSAdminRefreshProtocolServiceClient struct {
	cc *grpc.ClientConn
}

func NewHSAdminRefreshProtocolServiceClient(cc *grpc.ClientConn) HSAdminRefreshProtocolServiceClient {
	return &hSAdminRefreshProtocolServiceClient{cc}
}

func (c *hSAdminRefreshProtocolServiceClient) RefreshAdminAcls(ctx context.Context, in *RefreshAdminAclsRequestProto, opts ...grpc.CallOption) (*RefreshAdminAclsResponseProto, error) {
	out := new(RefreshAdminAclsResponseProto)
	err := grpc.Invoke(ctx, "/hproto.mapreduce.HSAdminRefreshProtocolService/refreshAdminAcls", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hSAdminRefreshProtocolServiceClient) RefreshLoadedJobCache(ctx context.Context, in *RefreshLoadedJobCacheRequestProto, opts ...grpc.CallOption) (*RefreshLoadedJobCacheResponseProto, error) {
	out := new(RefreshLoadedJobCacheResponseProto)
	err := grpc.Invoke(ctx, "/hproto.mapreduce.HSAdminRefreshProtocolService/refreshLoadedJobCache", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hSAdminRefreshProtocolServiceClient) RefreshJobRetentionSettings(ctx context.Context, in *RefreshJobRetentionSettingsRequestProto, opts ...grpc.CallOption) (*RefreshJobRetentionSettingsResponseProto, error) {
	out := new(RefreshJobRetentionSettingsResponseProto)
	err := grpc.Invoke(ctx, "/hproto.mapreduce.HSAdminRefreshProtocolService/refreshJobRetentionSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hSAdminRefreshProtocolServiceClient) RefreshLogRetentionSettings(ctx context.Context, in *RefreshLogRetentionSettingsRequestProto, opts ...grpc.CallOption) (*RefreshLogRetentionSettingsResponseProto, error) {
	out := new(RefreshLogRetentionSettingsResponseProto)
	err := grpc.Invoke(ctx, "/hproto.mapreduce.HSAdminRefreshProtocolService/refreshLogRetentionSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HSAdminRefreshProtocolService service

type HSAdminRefreshProtocolServiceServer interface {
	// *
	// Refresh admin acls
	RefreshAdminAcls(context.Context, *RefreshAdminAclsRequestProto) (*RefreshAdminAclsResponseProto, error)
	// *
	// Refresh loaded job cache
	RefreshLoadedJobCache(context.Context, *RefreshLoadedJobCacheRequestProto) (*RefreshLoadedJobCacheResponseProto, error)
	// *
	// Refresh job retention.
	RefreshJobRetentionSettings(context.Context, *RefreshJobRetentionSettingsRequestProto) (*RefreshJobRetentionSettingsResponseProto, error)
	// *
	// Refresh log retention
	RefreshLogRetentionSettings(context.Context, *RefreshLogRetentionSettingsRequestProto) (*RefreshLogRetentionSettingsResponseProto, error)
}

func RegisterHSAdminRefreshProtocolServiceServer(s *grpc.Server, srv HSAdminRefreshProtocolServiceServer) {
	s.RegisterService(&_HSAdminRefreshProtocolService_serviceDesc, srv)
}

func _HSAdminRefreshProtocolService_RefreshAdminAcls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAdminAclsRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshAdminAcls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.mapreduce.HSAdminRefreshProtocolService/RefreshAdminAcls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshAdminAcls(ctx, req.(*RefreshAdminAclsRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _HSAdminRefreshProtocolService_RefreshLoadedJobCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshLoadedJobCacheRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshLoadedJobCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.mapreduce.HSAdminRefreshProtocolService/RefreshLoadedJobCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshLoadedJobCache(ctx, req.(*RefreshLoadedJobCacheRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _HSAdminRefreshProtocolService_RefreshJobRetentionSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshJobRetentionSettingsRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshJobRetentionSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.mapreduce.HSAdminRefreshProtocolService/RefreshJobRetentionSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshJobRetentionSettings(ctx, req.(*RefreshJobRetentionSettingsRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _HSAdminRefreshProtocolService_RefreshLogRetentionSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshLogRetentionSettingsRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshLogRetentionSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hproto.mapreduce.HSAdminRefreshProtocolService/RefreshLogRetentionSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshLogRetentionSettings(ctx, req.(*RefreshLogRetentionSettingsRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

var _HSAdminRefreshProtocolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hproto.mapreduce.HSAdminRefreshProtocolService",
	HandlerType: (*HSAdminRefreshProtocolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "refreshAdminAcls",
			Handler:    _HSAdminRefreshProtocolService_RefreshAdminAcls_Handler,
		},
		{
			MethodName: "refreshLoadedJobCache",
			Handler:    _HSAdminRefreshProtocolService_RefreshLoadedJobCache_Handler,
		},
		{
			MethodName: "refreshJobRetentionSettings",
			Handler:    _HSAdminRefreshProtocolService_RefreshJobRetentionSettings_Handler,
		},
		{
			MethodName: "refreshLogRetentionSettings",
			Handler:    _HSAdminRefreshProtocolService_RefreshLogRetentionSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() {
	proto.RegisterFile("gopkg.in/freddierice/go-hproto.v1/mapreduce/HSAdminRefreshProtocol.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x19, 0xf8, 0x57, 0x77, 0x55, 0x06, 0xfe, 0x4d, 0x6d, 0x15, 0xab, 0x50, 0x15, 0x9c,
	0x60, 0x75, 0xa3, 0xbb, 0xd6, 0x4d, 0x91, 0x0a, 0xd2, 0x3e, 0x41, 0x4c, 0xae, 0x93, 0xc1, 0x76,
	0x26, 0xce, 0x4c, 0xfb, 0x00, 0xae, 0x7c, 0x00, 0x1f, 0xc0, 0xb7, 0xf1, 0xb5, 0x4c, 0xd3, 0x20,
	0x69, 0x3b, 0x93, 0xc4, 0x55, 0x20, 0xf7, 0xbb, 0x87, 0xc3, 0x39, 0x77, 0x60, 0xcc, 0x55, 0xfa,
	0xca, 0x99, 0x90, 0xc1, 0x8b, 0xc6, 0x38, 0x16, 0xa8, 0x45, 0x84, 0x01, 0x57, 0x97, 0x49, 0xaa,
	0x95, 0x55, 0x6c, 0x75, 0x15, 0x2c, 0xc2, 0x34, 0x1b, 0x2d, 0xb3, 0xdf, 0xe3, 0xd9, 0x30, 0x5e,
	0x08, 0x39, 0xc5, 0x8c, 0x35, 0xc9, 0xd3, 0x1a, 0x88, 0xd4, 0x9c, 0xe5, 0x24, 0x6d, 0x15, 0x1b,
	0xbf, 0x78, 0xef, 0x10, 0x3a, 0x05, 0x9a, 0xaf, 0x0d, 0xa3, 0xb9, 0x99, 0xe2, 0xdb, 0x12, 0x8d,
	0xcd, 0x57, 0x7b, 0x47, 0xd0, 0xdd, 0x9f, 0x9b, 0x54, 0x49, 0x83, 0x1b, 0xe0, 0x04, 0x8e, 0x0b,
	0x60, 0xa2, 0xc2, 0x18, 0xe3, 0x07, 0xf5, 0x7c, 0x1f, 0x46, 0x09, 0x6e, 0xa9, 0x9c, 0x42, 0xcf,
	0x03, 0x95, 0xa5, 0xce, 0xa1, 0x5f, 0x50, 0xd9, 0x7c, 0x8a, 0x16, 0xa5, 0x15, 0x4a, 0xce, 0xd0,
	0x5a, 0x21, 0xf9, 0xb6, 0xad, 0x0b, 0x38, 0xab, 0x44, 0xdd, 0xb2, 0x13, 0xc5, 0x9b, 0xca, 0xba,
	0xd1, 0x92, 0xec, 0xe0, 0xfb, 0x1f, 0x74, 0xdd, 0x61, 0xcf, 0x50, 0xaf, 0xb2, 0x86, 0xa8, 0x81,
	0x96, 0xde, 0xc9, 0x8e, 0x32, 0xb6, 0x5b, 0x01, 0xab, 0xca, 0xbf, 0x1d, 0x34, 0xe1, 0x4b, 0xb6,
	0xe8, 0x3b, 0x81, 0xff, 0xda, 0x95, 0x35, 0xbd, 0xf6, 0x4a, 0xf9, 0x9b, 0x6b, 0xdf, 0x34, 0x5e,
	0x2a, 0x9b, 0xf8, 0x24, 0x70, 0xa0, 0xfd, 0xfd, 0xd0, 0x5b, 0xaf, 0x6a, 0x5d, 0xf3, 0xed, 0xbb,
	0x3f, 0xae, 0x7a, 0x6c, 0xb9, 0xfa, 0xad, 0xb0, 0x55, 0x77, 0x39, 0x15, 0xb6, 0x6a, 0x2f, 0x69,
	0xf4, 0x08, 0x7d, 0xa5, 0x39, 0x0b, 0xd3, 0x75, 0x90, 0xfb, 0x3a, 0xab, 0x01, 0x4b, 0xcc, 0xe6,
	0x01, 0x8f, 0x3a, 0xee, 0x8b, 0xcb, 0xbf, 0xe6, 0x83, 0x90, 0x2f, 0x42, 0x7e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x20, 0x20, 0x73, 0x31, 0x2f, 0x04, 0x00, 0x00,
}
