// Code generated by protoc-gen-go.
// source: gopkg.in/freddierice/go-hproto.v1/mapreduce/mr_service_protos.proto
// DO NOT EDIT!

package hproto_mapreduce

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "gopkg.in/freddierice/go-hproto.v1/common"
import _ "gopkg.in/freddierice/go-hproto.v1/yarn"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetJobReportRequestProto struct {
	JobId            *JobIdProto `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GetJobReportRequestProto) Reset()                    { *m = GetJobReportRequestProto{} }
func (m *GetJobReportRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetJobReportRequestProto) ProtoMessage()               {}
func (*GetJobReportRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *GetJobReportRequestProto) GetJobId() *JobIdProto {
	if m != nil {
		return m.JobId
	}
	return nil
}

type GetJobReportResponseProto struct {
	JobReport        *JobReportProto `protobuf:"bytes,1,opt,name=job_report,json=jobReport" json:"job_report,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GetJobReportResponseProto) Reset()                    { *m = GetJobReportResponseProto{} }
func (m *GetJobReportResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetJobReportResponseProto) ProtoMessage()               {}
func (*GetJobReportResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *GetJobReportResponseProto) GetJobReport() *JobReportProto {
	if m != nil {
		return m.JobReport
	}
	return nil
}

type GetTaskReportRequestProto struct {
	TaskId           *TaskIdProto `protobuf:"bytes,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetTaskReportRequestProto) Reset()                    { *m = GetTaskReportRequestProto{} }
func (m *GetTaskReportRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetTaskReportRequestProto) ProtoMessage()               {}
func (*GetTaskReportRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *GetTaskReportRequestProto) GetTaskId() *TaskIdProto {
	if m != nil {
		return m.TaskId
	}
	return nil
}

type GetTaskReportResponseProto struct {
	TaskReport       *TaskReportProto `protobuf:"bytes,1,opt,name=task_report,json=taskReport" json:"task_report,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetTaskReportResponseProto) Reset()                    { *m = GetTaskReportResponseProto{} }
func (m *GetTaskReportResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetTaskReportResponseProto) ProtoMessage()               {}
func (*GetTaskReportResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *GetTaskReportResponseProto) GetTaskReport() *TaskReportProto {
	if m != nil {
		return m.TaskReport
	}
	return nil
}

type GetTaskAttemptReportRequestProto struct {
	TaskAttemptId    *TaskAttemptIdProto `protobuf:"bytes,1,opt,name=task_attempt_id,json=taskAttemptId" json:"task_attempt_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GetTaskAttemptReportRequestProto) Reset()         { *m = GetTaskAttemptReportRequestProto{} }
func (m *GetTaskAttemptReportRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetTaskAttemptReportRequestProto) ProtoMessage()    {}
func (*GetTaskAttemptReportRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{4}
}

func (m *GetTaskAttemptReportRequestProto) GetTaskAttemptId() *TaskAttemptIdProto {
	if m != nil {
		return m.TaskAttemptId
	}
	return nil
}

type GetTaskAttemptReportResponseProto struct {
	TaskAttemptReport *TaskAttemptReportProto `protobuf:"bytes,1,opt,name=task_attempt_report,json=taskAttemptReport" json:"task_attempt_report,omitempty"`
	XXX_unrecognized  []byte                  `json:"-"`
}

func (m *GetTaskAttemptReportResponseProto) Reset()         { *m = GetTaskAttemptReportResponseProto{} }
func (m *GetTaskAttemptReportResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetTaskAttemptReportResponseProto) ProtoMessage()    {}
func (*GetTaskAttemptReportResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{5}
}

func (m *GetTaskAttemptReportResponseProto) GetTaskAttemptReport() *TaskAttemptReportProto {
	if m != nil {
		return m.TaskAttemptReport
	}
	return nil
}

type GetCountersRequestProto struct {
	JobId            *JobIdProto `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GetCountersRequestProto) Reset()                    { *m = GetCountersRequestProto{} }
func (m *GetCountersRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetCountersRequestProto) ProtoMessage()               {}
func (*GetCountersRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *GetCountersRequestProto) GetJobId() *JobIdProto {
	if m != nil {
		return m.JobId
	}
	return nil
}

type GetCountersResponseProto struct {
	Counters         *CountersProto `protobuf:"bytes,1,opt,name=counters" json:"counters,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetCountersResponseProto) Reset()                    { *m = GetCountersResponseProto{} }
func (m *GetCountersResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetCountersResponseProto) ProtoMessage()               {}
func (*GetCountersResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *GetCountersResponseProto) GetCounters() *CountersProto {
	if m != nil {
		return m.Counters
	}
	return nil
}

type GetTaskAttemptCompletionEventsRequestProto struct {
	JobId            *JobIdProto `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	FromEventId      *int32      `protobuf:"varint,2,opt,name=from_event_id,json=fromEventId" json:"from_event_id,omitempty"`
	MaxEvents        *int32      `protobuf:"varint,3,opt,name=max_events,json=maxEvents" json:"max_events,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GetTaskAttemptCompletionEventsRequestProto) Reset() {
	*m = GetTaskAttemptCompletionEventsRequestProto{}
}
func (m *GetTaskAttemptCompletionEventsRequestProto) String() string {
	return proto.CompactTextString(m)
}
func (*GetTaskAttemptCompletionEventsRequestProto) ProtoMessage() {}
func (*GetTaskAttemptCompletionEventsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{8}
}

func (m *GetTaskAttemptCompletionEventsRequestProto) GetJobId() *JobIdProto {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *GetTaskAttemptCompletionEventsRequestProto) GetFromEventId() int32 {
	if m != nil && m.FromEventId != nil {
		return *m.FromEventId
	}
	return 0
}

func (m *GetTaskAttemptCompletionEventsRequestProto) GetMaxEvents() int32 {
	if m != nil && m.MaxEvents != nil {
		return *m.MaxEvents
	}
	return 0
}

type GetTaskAttemptCompletionEventsResponseProto struct {
	CompletionEvents []*TaskAttemptCompletionEventProto `protobuf:"bytes,1,rep,name=completion_events,json=completionEvents" json:"completion_events,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *GetTaskAttemptCompletionEventsResponseProto) Reset() {
	*m = GetTaskAttemptCompletionEventsResponseProto{}
}
func (m *GetTaskAttemptCompletionEventsResponseProto) String() string {
	return proto.CompactTextString(m)
}
func (*GetTaskAttemptCompletionEventsResponseProto) ProtoMessage() {}
func (*GetTaskAttemptCompletionEventsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{9}
}

func (m *GetTaskAttemptCompletionEventsResponseProto) GetCompletionEvents() []*TaskAttemptCompletionEventProto {
	if m != nil {
		return m.CompletionEvents
	}
	return nil
}

type GetTaskReportsRequestProto struct {
	JobId            *JobIdProto    `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	TaskType         *TaskTypeProto `protobuf:"varint,2,opt,name=task_type,json=taskType,enum=hproto.mapreduce.TaskTypeProto" json:"task_type,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetTaskReportsRequestProto) Reset()                    { *m = GetTaskReportsRequestProto{} }
func (m *GetTaskReportsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetTaskReportsRequestProto) ProtoMessage()               {}
func (*GetTaskReportsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *GetTaskReportsRequestProto) GetJobId() *JobIdProto {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *GetTaskReportsRequestProto) GetTaskType() TaskTypeProto {
	if m != nil && m.TaskType != nil {
		return *m.TaskType
	}
	return TaskTypeProto_MAP
}

type GetTaskReportsResponseProto struct {
	TaskReports      []*TaskReportProto `protobuf:"bytes,1,rep,name=task_reports,json=taskReports" json:"task_reports,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetTaskReportsResponseProto) Reset()                    { *m = GetTaskReportsResponseProto{} }
func (m *GetTaskReportsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetTaskReportsResponseProto) ProtoMessage()               {}
func (*GetTaskReportsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *GetTaskReportsResponseProto) GetTaskReports() []*TaskReportProto {
	if m != nil {
		return m.TaskReports
	}
	return nil
}

type GetDiagnosticsRequestProto struct {
	TaskAttemptId    *TaskAttemptIdProto `protobuf:"bytes,1,opt,name=task_attempt_id,json=taskAttemptId" json:"task_attempt_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GetDiagnosticsRequestProto) Reset()                    { *m = GetDiagnosticsRequestProto{} }
func (m *GetDiagnosticsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetDiagnosticsRequestProto) ProtoMessage()               {}
func (*GetDiagnosticsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

func (m *GetDiagnosticsRequestProto) GetTaskAttemptId() *TaskAttemptIdProto {
	if m != nil {
		return m.TaskAttemptId
	}
	return nil
}

type GetDiagnosticsResponseProto struct {
	Diagnostics      []string `protobuf:"bytes,1,rep,name=diagnostics" json:"diagnostics,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetDiagnosticsResponseProto) Reset()                    { *m = GetDiagnosticsResponseProto{} }
func (m *GetDiagnosticsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetDiagnosticsResponseProto) ProtoMessage()               {}
func (*GetDiagnosticsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{13} }

func (m *GetDiagnosticsResponseProto) GetDiagnostics() []string {
	if m != nil {
		return m.Diagnostics
	}
	return nil
}

type KillJobRequestProto struct {
	JobId            *JobIdProto `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *KillJobRequestProto) Reset()                    { *m = KillJobRequestProto{} }
func (m *KillJobRequestProto) String() string            { return proto.CompactTextString(m) }
func (*KillJobRequestProto) ProtoMessage()               {}
func (*KillJobRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{14} }

func (m *KillJobRequestProto) GetJobId() *JobIdProto {
	if m != nil {
		return m.JobId
	}
	return nil
}

type KillJobResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *KillJobResponseProto) Reset()                    { *m = KillJobResponseProto{} }
func (m *KillJobResponseProto) String() string            { return proto.CompactTextString(m) }
func (*KillJobResponseProto) ProtoMessage()               {}
func (*KillJobResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{15} }

type KillTaskRequestProto struct {
	TaskId           *TaskIdProto `protobuf:"bytes,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *KillTaskRequestProto) Reset()                    { *m = KillTaskRequestProto{} }
func (m *KillTaskRequestProto) String() string            { return proto.CompactTextString(m) }
func (*KillTaskRequestProto) ProtoMessage()               {}
func (*KillTaskRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{16} }

func (m *KillTaskRequestProto) GetTaskId() *TaskIdProto {
	if m != nil {
		return m.TaskId
	}
	return nil
}

type KillTaskResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *KillTaskResponseProto) Reset()                    { *m = KillTaskResponseProto{} }
func (m *KillTaskResponseProto) String() string            { return proto.CompactTextString(m) }
func (*KillTaskResponseProto) ProtoMessage()               {}
func (*KillTaskResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{17} }

type KillTaskAttemptRequestProto struct {
	TaskAttemptId    *TaskAttemptIdProto `protobuf:"bytes,1,opt,name=task_attempt_id,json=taskAttemptId" json:"task_attempt_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *KillTaskAttemptRequestProto) Reset()                    { *m = KillTaskAttemptRequestProto{} }
func (m *KillTaskAttemptRequestProto) String() string            { return proto.CompactTextString(m) }
func (*KillTaskAttemptRequestProto) ProtoMessage()               {}
func (*KillTaskAttemptRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{18} }

func (m *KillTaskAttemptRequestProto) GetTaskAttemptId() *TaskAttemptIdProto {
	if m != nil {
		return m.TaskAttemptId
	}
	return nil
}

type KillTaskAttemptResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *KillTaskAttemptResponseProto) Reset()                    { *m = KillTaskAttemptResponseProto{} }
func (m *KillTaskAttemptResponseProto) String() string            { return proto.CompactTextString(m) }
func (*KillTaskAttemptResponseProto) ProtoMessage()               {}
func (*KillTaskAttemptResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{19} }

type FailTaskAttemptRequestProto struct {
	TaskAttemptId    *TaskAttemptIdProto `protobuf:"bytes,1,opt,name=task_attempt_id,json=taskAttemptId" json:"task_attempt_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *FailTaskAttemptRequestProto) Reset()                    { *m = FailTaskAttemptRequestProto{} }
func (m *FailTaskAttemptRequestProto) String() string            { return proto.CompactTextString(m) }
func (*FailTaskAttemptRequestProto) ProtoMessage()               {}
func (*FailTaskAttemptRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{20} }

func (m *FailTaskAttemptRequestProto) GetTaskAttemptId() *TaskAttemptIdProto {
	if m != nil {
		return m.TaskAttemptId
	}
	return nil
}

type FailTaskAttemptResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FailTaskAttemptResponseProto) Reset()                    { *m = FailTaskAttemptResponseProto{} }
func (m *FailTaskAttemptResponseProto) String() string            { return proto.CompactTextString(m) }
func (*FailTaskAttemptResponseProto) ProtoMessage()               {}
func (*FailTaskAttemptResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{21} }

func init() {
	proto.RegisterType((*GetJobReportRequestProto)(nil), "hproto.mapreduce.GetJobReportRequestProto")
	proto.RegisterType((*GetJobReportResponseProto)(nil), "hproto.mapreduce.GetJobReportResponseProto")
	proto.RegisterType((*GetTaskReportRequestProto)(nil), "hproto.mapreduce.GetTaskReportRequestProto")
	proto.RegisterType((*GetTaskReportResponseProto)(nil), "hproto.mapreduce.GetTaskReportResponseProto")
	proto.RegisterType((*GetTaskAttemptReportRequestProto)(nil), "hproto.mapreduce.GetTaskAttemptReportRequestProto")
	proto.RegisterType((*GetTaskAttemptReportResponseProto)(nil), "hproto.mapreduce.GetTaskAttemptReportResponseProto")
	proto.RegisterType((*GetCountersRequestProto)(nil), "hproto.mapreduce.GetCountersRequestProto")
	proto.RegisterType((*GetCountersResponseProto)(nil), "hproto.mapreduce.GetCountersResponseProto")
	proto.RegisterType((*GetTaskAttemptCompletionEventsRequestProto)(nil), "hproto.mapreduce.GetTaskAttemptCompletionEventsRequestProto")
	proto.RegisterType((*GetTaskAttemptCompletionEventsResponseProto)(nil), "hproto.mapreduce.GetTaskAttemptCompletionEventsResponseProto")
	proto.RegisterType((*GetTaskReportsRequestProto)(nil), "hproto.mapreduce.GetTaskReportsRequestProto")
	proto.RegisterType((*GetTaskReportsResponseProto)(nil), "hproto.mapreduce.GetTaskReportsResponseProto")
	proto.RegisterType((*GetDiagnosticsRequestProto)(nil), "hproto.mapreduce.GetDiagnosticsRequestProto")
	proto.RegisterType((*GetDiagnosticsResponseProto)(nil), "hproto.mapreduce.GetDiagnosticsResponseProto")
	proto.RegisterType((*KillJobRequestProto)(nil), "hproto.mapreduce.KillJobRequestProto")
	proto.RegisterType((*KillJobResponseProto)(nil), "hproto.mapreduce.KillJobResponseProto")
	proto.RegisterType((*KillTaskRequestProto)(nil), "hproto.mapreduce.KillTaskRequestProto")
	proto.RegisterType((*KillTaskResponseProto)(nil), "hproto.mapreduce.KillTaskResponseProto")
	proto.RegisterType((*KillTaskAttemptRequestProto)(nil), "hproto.mapreduce.KillTaskAttemptRequestProto")
	proto.RegisterType((*KillTaskAttemptResponseProto)(nil), "hproto.mapreduce.KillTaskAttemptResponseProto")
	proto.RegisterType((*FailTaskAttemptRequestProto)(nil), "hproto.mapreduce.FailTaskAttemptRequestProto")
	proto.RegisterType((*FailTaskAttemptResponseProto)(nil), "hproto.mapreduce.FailTaskAttemptResponseProto")
}

func init() {
	proto.RegisterFile("gopkg.in/freddierice/go-hproto.v1/mapreduce/mr_service_protos.proto", fileDescriptor3)
}

var fileDescriptor3 = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x56, 0xcb, 0x4f, 0x13, 0x41,
	0x18, 0xcf, 0x4a, 0x40, 0xfb, 0x55, 0xe4, 0xa5, 0x82, 0x05, 0xb4, 0x4c, 0x38, 0x10, 0x8d, 0xdb,
	0x80, 0x89, 0x9a, 0xa0, 0x21, 0x02, 0x6a, 0xc4, 0x67, 0xb6, 0x24, 0x7a, 0x30, 0xd6, 0x65, 0x3b,
	0x94, 0x6d, 0xbb, 0x3b, 0xeb, 0xcc, 0xb4, 0xb1, 0x07, 0xef, 0x5e, 0x8c, 0xff, 0x82, 0x07, 0xff,
	0x50, 0x67, 0x67, 0xf6, 0x31, 0xbb, 0xdd, 0x50, 0x4d, 0xc1, 0x0b, 0x74, 0xbf, 0xc7, 0xef, 0xf1,
	0xed, 0x7c, 0xd3, 0xc2, 0x5e, 0x8b, 0x04, 0x9d, 0x96, 0xe9, 0xfa, 0xb5, 0x63, 0x8a, 0x9b, 0x4d,
	0x17, 0x53, 0xd7, 0xc1, 0xb5, 0x16, 0xb9, 0x7b, 0x12, 0x50, 0xc2, 0x89, 0xd9, 0xdf, 0xac, 0x79,
	0x76, 0x20, 0x52, 0x3d, 0x11, 0xf6, 0x68, 0x83, 0x61, 0xda, 0x17, 0x15, 0x0d, 0x99, 0x65, 0xa6,
	0xfc, 0x37, 0x3f, 0x1b, 0x15, 0x27, 0x95, 0x95, 0x07, 0xa3, 0x61, 0x1d, 0xe2, 0x79, 0xc4, 0xaf,
	0xd5, 0xb1, 0xd3, 0xa3, 0x2e, 0x1f, 0x28, 0xa8, 0xca, 0xf6, 0x3f, 0xea, 0xd1, 0x75, 0x54, 0x1e,
	0x8e, 0x6e, 0x1e, 0xd8, 0xd4, 0x97, 0x7f, 0x32, 0x9d, 0xe8, 0x2d, 0x2c, 0x3d, 0xc7, 0xfc, 0x80,
	0x1c, 0x59, 0x38, 0x20, 0x94, 0x5b, 0xf8, 0x4b, 0x0f, 0x33, 0xfe, 0x4e, 0xba, 0xbb, 0x07, 0x53,
	0x6d, 0x72, 0xd4, 0x70, 0x9b, 0x4b, 0x46, 0xd5, 0xd8, 0x28, 0x6f, 0xad, 0x98, 0x79, 0xbb, 0xa6,
	0x68, 0x7c, 0xd1, 0x94, 0xd5, 0xd6, 0x64, 0x3b, 0xfc, 0x8c, 0x3e, 0xc2, 0x8d, 0x2c, 0x20, 0x0b,
	0x88, 0xcf, 0xb0, 0x42, 0xdc, 0x01, 0x08, 0x11, 0xa9, 0x4c, 0x45, 0xa8, 0xd5, 0x42, 0x54, 0xd5,
	0xad, 0x90, 0x4b, 0xed, 0xf8, 0x19, 0xd5, 0x25, 0xfa, 0xa1, 0xcd, 0x3a, 0x05, 0x7a, 0xef, 0xc3,
	0x45, 0x2e, 0x32, 0xa9, 0xe0, 0xd5, 0x61, 0xe8, 0xb0, 0x35, 0x56, 0x3c, 0xc5, 0xe5, 0x03, 0xfa,
	0x0c, 0x95, 0x1c, 0xa8, 0xae, 0x79, 0x17, 0xca, 0x12, 0x35, 0x23, 0x7a, 0xad, 0x18, 0x59, 0x57,
	0x0d, 0x3c, 0x09, 0xa0, 0x00, 0xaa, 0x11, 0xc3, 0x13, 0xce, 0xb1, 0x17, 0xf0, 0x02, 0xf5, 0xaf,
	0x60, 0x46, 0xf2, 0xd8, 0xaa, 0x22, 0x75, 0xb1, 0x5e, 0xcc, 0x15, 0x21, 0xc5, 0x66, 0xa6, 0xb9,
	0x1e, 0x43, 0xdf, 0x60, 0xad, 0x98, 0x51, 0xb7, 0xf6, 0x01, 0x16, 0x32, 0x94, 0x19, 0x8b, 0x1b,
	0xa7, 0xd2, 0xea, 0x4e, 0xe7, 0x78, 0x3e, 0x8e, 0xde, 0xc0, 0xa2, 0xa0, 0xdf, 0x23, 0x3d, 0x9f,
	0x63, 0xca, 0xc6, 0x3f, 0x55, 0xef, 0xe5, 0x31, 0x4d, 0xf1, 0x74, 0x17, 0xdb, 0x70, 0xc9, 0x89,
	0x12, 0x11, 0xe4, 0xad, 0x61, 0xc8, 0xb8, 0x55, 0xa1, 0x26, 0x0d, 0xe8, 0xb7, 0x01, 0xb7, 0xb3,
	0x83, 0xda, 0x23, 0x5e, 0xd0, 0xc5, 0xdc, 0x25, 0xfe, 0xd3, 0x3e, 0xf6, 0xf9, 0xf8, 0xe2, 0xe7,
	0x11, 0x4c, 0x1f, 0x53, 0xe2, 0x35, 0x70, 0x88, 0x17, 0xf6, 0x5e, 0x10, 0xbd, 0x93, 0x56, 0x39,
	0x0c, 0x4a, 0x0e, 0x51, 0xb3, 0x0a, 0xe0, 0xd9, 0x5f, 0x55, 0x09, 0x5b, 0x9a, 0x90, 0x05, 0x25,
	0x11, 0x51, 0x1a, 0xd0, 0x0f, 0x03, 0xee, 0x8c, 0x92, 0xa9, 0xcf, 0xe4, 0x13, 0xcc, 0x39, 0x49,
	0x41, 0x8c, 0x6a, 0x54, 0x27, 0x84, 0xe4, 0xcd, 0x53, 0xdf, 0x6b, 0x0e, 0x56, 0xf9, 0x98, 0x75,
	0x72, 0x64, 0xe8, 0xa7, 0x91, 0xdb, 0x99, 0x33, 0x18, 0xd3, 0x23, 0x28, 0xc9, 0xd3, 0xc8, 0x07,
	0x01, 0x96, 0x23, 0xba, 0x52, 0xf4, 0x22, 0x43, 0xca, 0x43, 0x51, 0x11, 0xbd, 0x48, 0x1e, 0x3d,
	0x22, 0x07, 0x96, 0xf3, 0x82, 0xf4, 0x81, 0xec, 0xc3, 0x65, 0x6d, 0x8b, 0xe3, 0x59, 0xfc, 0xc5,
	0x1a, 0x97, 0xd3, 0x35, 0x66, 0xa8, 0x2d, 0x5d, 0xef, 0xbb, 0x76, 0xcb, 0x27, 0x8c, 0xbb, 0x0e,
	0x3b, 0xc7, 0x0d, 0xde, 0x91, 0x86, 0x32, 0x5c, 0xba, 0xa1, 0x2a, 0x94, 0x9b, 0x69, 0x4e, 0xfa,
	0x29, 0x59, 0x7a, 0x08, 0x1d, 0xc0, 0xc2, 0x4b, 0xb7, 0xdb, 0x95, 0x97, 0xe9, 0xb8, 0xfb, 0x77,
	0x1d, 0xae, 0x26, 0x58, 0x9a, 0x0a, 0xb1, 0xe7, 0x32, 0xae, 0x86, 0x76, 0x06, 0x57, 0xf1, 0x22,
	0x5c, 0x4b, 0xf1, 0x74, 0xa2, 0x0e, 0x2c, 0xc7, 0x89, 0xe4, 0xa6, 0x39, 0xb7, 0xd1, 0xdf, 0x84,
	0x95, 0x21, 0xb2, 0x9c, 0x98, 0x67, 0xb6, 0xfb, 0xff, 0xc4, 0x0c, 0x91, 0x69, 0x62, 0x76, 0x1f,
	0xc3, 0x3a, 0xa1, 0x2d, 0xd3, 0x0e, 0x6c, 0xe7, 0x04, 0x0f, 0x13, 0xf4, 0xb7, 0xd4, 0x37, 0xfd,
	0xee, 0xcc, 0x6b, 0xab, 0xae, 0x7e, 0xc3, 0xc8, 0x3e, 0xf6, 0xdd, 0x30, 0x7e, 0x19, 0xc6, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xee, 0x74, 0xb2, 0x08, 0x09, 0x00, 0x00,
}
